import { db } from '@/db';
import { connections } from '@/db/schema';

async function main() {
    const sampleConnections = [
        // ===== STUDENT-TO-STUDENT CONNECTIONS (80 total) =====
        // Same branch connections (40)
        {
            requesterId: 2,
            responderId: 5,
            status: 'accepted',
            message: 'Hey! We\'re in the same CS branch. Let\'s connect!',
            createdAt: new Date('2024-09-15T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-09-16T14:20:00Z').toISOString(),
        },
        {
            requesterId: 3,
            responderId: 7,
            status: 'accepted',
            message: 'Hi! Would love to collaborate on projects together.',
            createdAt: new Date('2024-09-18T08:15:00Z').toISOString(),
            respondedAt: new Date('2024-09-20T11:30:00Z').toISOString(),
        },
        {
            requesterId: 4,
            responderId: 9,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-09-22T16:45:00Z').toISOString(),
            respondedAt: new Date('2024-09-23T09:20:00Z').toISOString(),
        },
        {
            requesterId: 6,
            responderId: 11,
            status: 'accepted',
            message: 'Hello! I see we share similar interests in AI/ML. Let\'s connect!',
            createdAt: new Date('2024-09-25T13:10:00Z').toISOString(),
            respondedAt: new Date('2024-09-27T15:40:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 13,
            status: 'accepted',
            message: 'Hey! Working on a web dev project. Would be great to exchange ideas.',
            createdAt: new Date('2024-10-01T11:25:00Z').toISOString(),
            respondedAt: new Date('2024-10-02T10:15:00Z').toISOString(),
        },
        {
            requesterId: 10,
            responderId: 15,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-05T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-08T16:20:00Z').toISOString(),
        },
        {
            requesterId: 12,
            responderId: 17,
            status: 'accepted',
            message: 'Hi! Let\'s connect and share study resources.',
            createdAt: new Date('2024-10-10T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-10-11T13:55:00Z').toISOString(),
        },
        {
            requesterId: 14,
            responderId: 19,
            status: 'accepted',
            message: 'Hey! Same branch and cohort. Let\'s collaborate!',
            createdAt: new Date('2024-10-12T15:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-14T11:30:00Z').toISOString(),
        },
        {
            requesterId: 16,
            responderId: 21,
            status: 'pending',
            message: 'Hi! I\'m looking for study partners for upcoming exams. Let\'s connect!',
            createdAt: new Date('2024-12-22T10:15:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 18,
            responderId: 23,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-18T12:45:00Z').toISOString(),
            respondedAt: new Date('2024-10-20T14:10:00Z').toISOString(),
        },
        {
            requesterId: 20,
            responderId: 25,
            status: 'accepted',
            message: 'Hello! Let\'s connect and discuss career opportunities.',
            createdAt: new Date('2024-10-22T08:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-23T16:40:00Z').toISOString(),
        },
        {
            requesterId: 22,
            responderId: 27,
            status: 'accepted',
            message: 'Hey! I noticed we have similar skills. Let\'s network!',
            createdAt: new Date('2024-10-25T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-27T09:35:00Z').toISOString(),
        },
        {
            requesterId: 24,
            responderId: 29,
            status: 'pending',
            message: 'Hi! Would love to connect and share experiences.',
            createdAt: new Date('2024-12-24T14:50:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 26,
            responderId: 31,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-30T10:10:00Z').toISOString(),
            respondedAt: new Date('2024-11-01T15:25:00Z').toISOString(),
        },
        {
            requesterId: 28,
            responderId: 33,
            status: 'accepted',
            message: 'Hello! Same branch. Let\'s collaborate on hackathons!',
            createdAt: new Date('2024-11-02T13:40:00Z').toISOString(),
            respondedAt: new Date('2024-11-03T11:20:00Z').toISOString(),
        },
        {
            requesterId: 30,
            responderId: 35,
            status: 'accepted',
            message: 'Hey! Let\'s connect and build something amazing together.',
            createdAt: new Date('2024-11-05T09:15:00Z').toISOString(),
            respondedAt: new Date('2024-11-06T16:30:00Z').toISOString(),
        },
        {
            requesterId: 32,
            responderId: 37,
            status: 'rejected',
            message: 'Hi! Would like to connect.',
            createdAt: new Date('2024-11-08T14:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-15T10:40:00Z').toISOString(),
        },
        {
            requesterId: 34,
            responderId: 39,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-10T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-12T13:15:00Z').toISOString(),
        },
        {
            requesterId: 36,
            responderId: 41,
            status: 'accepted',
            message: 'Hello! Let\'s exchange notes and study materials.',
            createdAt: new Date('2024-11-12T16:20:00Z').toISOString(),
            respondedAt: new Date('2024-11-13T09:45:00Z').toISOString(),
        },
        {
            requesterId: 38,
            responderId: 43,
            status: 'accepted',
            message: 'Hey! Working on similar tech stack. Let\'s connect!',
            createdAt: new Date('2024-11-15T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-11-17T14:50:00Z').toISOString(),
        },
        {
            requesterId: 40,
            responderId: 45,
            status: 'pending',
            message: 'Hi! I see we\'re in the same batch. Would love to connect!',
            createdAt: new Date('2024-12-26T13:10:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 42,
            responderId: 47,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-20T08:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-21T15:20:00Z').toISOString(),
        },
        {
            requesterId: 44,
            responderId: 49,
            status: 'accepted',
            message: 'Hello! Let\'s connect and work on projects together.',
            createdAt: new Date('2024-11-22T12:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-24T10:15:00Z').toISOString(),
        },
        {
            requesterId: 46,
            responderId: 51,
            status: 'accepted',
            message: 'Hey! Same CS branch. Let\'s network!',
            createdAt: new Date('2024-11-25T14:55:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T16:40:00Z').toISOString(),
        },
        {
            requesterId: 5,
            responderId: 8,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-28T09:20:00Z').toISOString(),
            respondedAt: new Date('2024-11-29T13:35:00Z').toISOString(),
        },
        {
            requesterId: 7,
            responderId: 12,
            status: 'accepted',
            message: 'Hi! Let\'s connect and share placement preparation resources.',
            createdAt: new Date('2024-11-30T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-01T15:10:00Z').toISOString(),
        },
        {
            requesterId: 9,
            responderId: 14,
            status: 'accepted',
            message: 'Hey! Same branch. Would love to collaborate on coding challenges.',
            createdAt: new Date('2024-12-02T13:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T10:50:00Z').toISOString(),
        },
        {
            requesterId: 11,
            responderId: 16,
            status: 'pending',
            message: 'Hello! I noticed we have similar career interests. Let\'s connect!',
            createdAt: new Date('2024-12-28T16:30:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 13,
            responderId: 18,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-05T08:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T14:15:00Z').toISOString(),
        },
        {
            requesterId: 15,
            responderId: 20,
            status: 'accepted',
            message: 'Hi! Let\'s connect and discuss upcoming tech events.',
            createdAt: new Date('2024-12-07T12:55:00Z').toISOString(),
            respondedAt: new Date('2024-12-08T16:20:00Z').toISOString(),
        },
        {
            requesterId: 17,
            responderId: 22,
            status: 'accepted',
            message: 'Hey! Same cohort. Let\'s stay connected!',
            createdAt: new Date('2024-12-09T10:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-11T13:45:00Z').toISOString(),
        },
        {
            requesterId: 19,
            responderId: 24,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-12-10T15:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-18T09:20:00Z').toISOString(),
        },
        {
            requesterId: 21,
            responderId: 26,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-12T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-13T14:50:00Z').toISOString(),
        },
        {
            requesterId: 23,
            responderId: 28,
            status: 'accepted',
            message: 'Hi! Let\'s connect and form a study group.',
            createdAt: new Date('2024-12-14T09:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-15T16:10:00Z').toISOString(),
        },
        {
            requesterId: 25,
            responderId: 30,
            status: 'accepted',
            message: 'Hey! Same branch and year. Let\'s network!',
            createdAt: new Date('2024-12-16T13:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-17T11:55:00Z').toISOString(),
        },
        {
            requesterId: 27,
            responderId: 32,
            status: 'pending',
            message: 'Hello! Would love to connect and discuss career paths.',
            createdAt: new Date('2024-12-30T10:25:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 29,
            responderId: 34,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-18T14:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-19T09:15:00Z').toISOString(),
        },
        {
            requesterId: 31,
            responderId: 36,
            status: 'accepted',
            message: 'Hi! Let\'s connect and work on open-source projects together.',
            createdAt: new Date('2024-12-19T16:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-20T13:20:00Z').toISOString(),
        },
        {
            requesterId: 33,
            responderId: 38,
            status: 'accepted',
            message: 'Hey! Same branch. Let\'s share interview experiences!',
            createdAt: new Date('2024-12-20T11:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-21T15:35:00Z').toISOString(),
        },
        {
            requesterId: 35,
            responderId: 40,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-21T08:55:00Z').toISOString(),
            respondedAt: new Date('2024-12-22T14:20:00Z').toISOString(),
        },

        // Same cohort connections (30)
        {
            requesterId: 2,
            responderId: 3,
            status: 'accepted',
            message: 'Hey! We\'re in the same cohort. Let\'s connect!',
            createdAt: new Date('2024-09-20T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-09-21T13:45:00Z').toISOString(),
        },
        {
            requesterId: 4,
            responderId: 6,
            status: 'accepted',
            message: 'Hi! Same batch. Would love to collaborate on assignments.',
            createdAt: new Date('2024-09-25T14:20:00Z').toISOString(),
            respondedAt: new Date('2024-09-27T11:35:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 10,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-02T09:15:00Z').toISOString(),
            respondedAt: new Date('2024-10-03T16:50:00Z').toISOString(),
        },
        {
            requesterId: 12,
            responderId: 14,
            status: 'accepted',
            message: 'Hello! Same cohort. Let\'s form a study group!',
            createdAt: new Date('2024-10-08T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-10-09T15:20:00Z').toISOString(),
        },
        {
            requesterId: 16,
            responderId: 18,
            status: 'accepted',
            message: 'Hey! Let\'s connect and prepare for placements together.',
            createdAt: new Date('2024-10-15T11:25:00Z').toISOString(),
            respondedAt: new Date('2024-10-17T14:10:00Z').toISOString(),
        },
        {
            requesterId: 20,
            responderId: 22,
            status: 'pending',
            message: 'Hi! Same year and cohort. Would love to connect!',
            createdAt: new Date('2024-12-27T13:50:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 24,
            responderId: 26,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-22T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-10-23T15:45:00Z').toISOString(),
        },
        {
            requesterId: 28,
            responderId: 30,
            status: 'accepted',
            message: 'Hello! Same cohort. Let\'s network and share opportunities!',
            createdAt: new Date('2024-10-28T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-30T11:40:00Z').toISOString(),
        },
        {
            requesterId: 32,
            responderId: 34,
            status: 'accepted',
            message: 'Hey! Let\'s connect and discuss upcoming projects.',
            createdAt: new Date('2024-11-05T09:55:00Z').toISOString(),
            respondedAt: new Date('2024-11-06T14:30:00Z').toISOString(),
        },
        {
            requesterId: 36,
            responderId: 38,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-10T12:10:00Z').toISOString(),
            respondedAt: new Date('2024-11-11T16:25:00Z').toISOString(),
        },
        {
            requesterId: 40,
            responderId: 42,
            status: 'accepted',
            message: 'Hi! Same cohort. Let\'s stay connected!',
            createdAt: new Date('2024-11-15T14:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-16T10:20:00Z').toISOString(),
        },
        {
            requesterId: 44,
            responderId: 46,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-11-18T11:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T09:15:00Z').toISOString(),
        },
        {
            requesterId: 48,
            responderId: 50,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-22T13:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-23T16:10:00Z').toISOString(),
        },
        {
            requesterId: 3,
            responderId: 5,
            status: 'accepted',
            message: 'Hey! Same cohort. Let\'s collaborate on hackathons!',
            createdAt: new Date('2024-11-25T10:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T14:40:00Z').toISOString(),
        },
        {
            requesterId: 7,
            responderId: 9,
            status: 'accepted',
            message: 'Hi! Let\'s connect and share learning resources.',
            createdAt: new Date('2024-11-28T12:35:00Z').toISOString(),
            respondedAt: new Date('2024-11-29T15:55:00Z').toISOString(),
        },
        {
            requesterId: 11,
            responderId: 13,
            status: 'pending',
            message: 'Hello! Same cohort. Would love to network with you!',
            createdAt: new Date('2024-12-29T14:15:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 15,
            responderId: 17,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-02T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T13:20:00Z').toISOString(),
        },
        {
            requesterId: 19,
            responderId: 21,
            status: 'accepted',
            message: 'Hey! Let\'s connect and discuss career opportunities.',
            createdAt: new Date('2024-12-05T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T16:35:00Z').toISOString(),
        },
        {
            requesterId: 23,
            responderId: 25,
            status: 'accepted',
            message: 'Hi! Same year. Let\'s stay in touch!',
            createdAt: new Date('2024-12-08T14:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T11:45:00Z').toISOString(),
        },
        {
            requesterId: 27,
            responderId: 29,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-11T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-12T15:50:00Z').toISOString(),
        },
        {
            requesterId: 31,
            responderId: 33,
            status: 'accepted',
            message: 'Hello! Same cohort. Let\'s form a project team!',
            createdAt: new Date('2024-12-13T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-14T16:40:00Z').toISOString(),
        },
        {
            requesterId: 35,
            responderId: 37,
            status: 'pending',
            message: 'Hey! Would love to connect and collaborate on projects.',
            createdAt: new Date('2024-12-31T11:55:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 39,
            responderId: 41,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-16T09:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-17T14:15:00Z').toISOString(),
        },
        {
            requesterId: 43,
            responderId: 45,
            status: 'accepted',
            message: 'Hi! Let\'s connect and prepare for exams together.',
            createdAt: new Date('2024-12-18T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-19T16:10:00Z').toISOString(),
        },
        {
            requesterId: 47,
            responderId: 49,
            status: 'accepted',
            message: 'Hey! Same batch. Let\'s network and grow together!',
            createdAt: new Date('2024-12-20T15:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-21T11:20:00Z').toISOString(),
        },
        {
            requesterId: 6,
            responderId: 10,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-12-15T10:15:00Z').toISOString(),
            respondedAt: new Date('2024-12-23T13:45:00Z').toISOString(),
        },
        {
            requesterId: 14,
            responderId: 16,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-21T13:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-22T16:30:00Z').toISOString(),
        },
        {
            requesterId: 22,
            responderId: 24,
            status: 'accepted',
            message: 'Hi! Same cohort. Let\'s connect and share experiences!',
            createdAt: new Date('2024-12-22T11:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-23T15:25:00Z').toISOString(),
        },
        {
            requesterId: 30,
            responderId: 32,
            status: 'accepted',
            message: 'Hey! Let\'s connect and discuss placement strategies.',
            createdAt: new Date('2024-12-23T14:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-24T10:50:00Z').toISOString(),
        },
        {
            requesterId: 38,
            responderId: 40,
            status: 'pending',
            message: 'Hello! Same year. Would love to connect and collaborate!',
            createdAt: new Date('2025-01-01T09:40:00Z').toISOString(),
            respondedAt: null,
        },

        // Cross-branch connections (10)
        {
            requesterId: 2,
            responderId: 48,
            status: 'accepted',
            message: 'Hi! I see you\'re from Mechanical. Would love to learn about interdisciplinary projects!',
            createdAt: new Date('2024-10-05T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-07T14:35:00Z').toISOString(),
        },
        {
            requesterId: 12,
            responderId: 28,
            status: 'accepted',
            message: 'Hey! Cross-branch collaboration sounds exciting. Let\'s connect!',
            createdAt: new Date('2024-10-15T13:45:00Z').toISOString(),
            respondedAt: new Date('2024-10-16T16:20:00Z').toISOString(),
        },
        {
            requesterId: 20,
            responderId: 36,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-02T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-03T15:10:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 44,
            status: 'pending',
            message: 'Hello! Would love to connect and explore cross-functional opportunities.',
            createdAt: new Date('2024-12-28T12:25:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 16,
            responderId: 32,
            status: 'accepted',
            message: 'Hi! Different branches but similar interests. Let\'s network!',
            createdAt: new Date('2024-11-18T14:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-20T11:15:00Z').toISOString(),
        },
        {
            requesterId: 24,
            responderId: 40,
            status: 'accepted',
            message: 'Hey! Cross-branch projects are the future. Let\'s connect!',
            createdAt: new Date('2024-11-25T09:35:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T13:50:00Z').toISOString(),
        },
        {
            requesterId: 4,
            responderId: 50,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-11-28T15:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-05T10:25:00Z').toISOString(),
        },
        {
            requesterId: 36,
            responderId: 14,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-08T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T16:55:00Z').toISOString(),
        },
        {
            requesterId: 42,
            responderId: 18,
            status: 'accepted',
            message: 'Hi! Let\'s connect and share cross-branch insights!',
            createdAt: new Date('2024-12-15T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T14:45:00Z').toISOString(),
        },
        {
            requesterId: 46,
            responderId: 6,
            status: 'accepted',
            message: 'Hey! Different branches but let\'s collaborate on innovative ideas!',
            createdAt: new Date('2024-12-20T13:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-21T16:10:00Z').toISOString(),
        },

        // ===== STUDENT-TO-ALUMNI CONNECTIONS (70 total) =====
        // Same branch connections (40)
        {
            requesterId: 2,
            responderId: 52,
            status: 'accepted',
            message: 'Hi! Would love to connect and learn from your experience at Google.',
            createdAt: new Date('2024-09-10T10:15:00Z').toISOString(),
            respondedAt: new Date('2024-09-12T14:30:00Z').toISOString(),
        },
        {
            requesterId: 5,
            responderId: 54,
            status: 'accepted',
            message: 'Hello! I\'m from CS too. Would appreciate guidance on career paths.',
            createdAt: new Date('2024-09-18T13:25:00Z').toISOString(),
            respondedAt: new Date('2024-09-20T16:40:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 56,
            status: 'accepted',
            message: 'Hey! Same branch. Would love to hear about your journey at Microsoft.',
            createdAt: new Date('2024-09-25T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-09-27T15:10:00Z').toISOString(),
        },
        {
            requesterId: 11,
            responderId: 58,
            status: 'pending',
            message: 'Hi! I\'m looking for guidance on AI/ML career. Would appreciate your mentorship.',
            createdAt: new Date('2024-12-25T14:20:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 14,
            responderId: 60,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-08T09:35:00Z').toISOString(),
            respondedAt: new Date('2024-10-10T13:50:00Z').toISOString(),
        },
        {
            requesterId: 17,
            responderId: 62,
            status: 'accepted',
            message: 'Hello! Would love to connect and learn about your experience at Amazon.',
            createdAt: new Date('2024-10-15T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-10-17T16:25:00Z').toISOString(),
        },
        {
            requesterId: 20,
            responderId: 64,
            status: 'accepted',
            message: 'Hi! Same CS branch. Seeking advice on placement preparation.',
            createdAt: new Date('2024-10-22T14:55:00Z').toISOString(),
            respondedAt: new Date('2024-10-24T11:30:00Z').toISOString(),
        },
        {
            requesterId: 23,
            responderId: 66,
            status: 'accepted',
            message: 'Hey! Would love to hear about your career journey in tech.',
            createdAt: new Date('2024-10-28T10:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-30T15:45:00Z').toISOString(),
        },
        {
            requesterId: 26,
            responderId: 68,
            status: 'pending',
            message: 'Hello! I\'m interested in backend development. Would love your guidance.',
            createdAt: new Date('2024-12-27T13:10:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 29,
            responderId: 70,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-05T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-06T16:20:00Z').toISOString(),
        },
        {
            requesterId: 32,
            responderId: 72,
            status: 'accepted',
            message: 'Hi! Would appreciate advice on transitioning from college to corporate.',
            createdAt: new Date('2024-11-10T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-12T10:55:00Z').toISOString(),
        },
        {
            requesterId: 35,
            responderId: 74,
            status: 'accepted',
            message: 'Hey! Same branch. Would love to learn about startup culture.',
            createdAt: new Date('2024-11-15T09:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-16T13:40:00Z').toISOString(),
        },
        {
            requesterId: 38,
            responderId: 76,
            status: 'rejected',
            message: 'Hello! Would like to connect and seek career advice.',
            createdAt: new Date('2024-11-18T12:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-27T09:15:00Z').toISOString(),
        },
        {
            requesterId: 41,
            responderId: 78,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-22T15:10:00Z').toISOString(),
            respondedAt: new Date('2024-11-23T11:35:00Z').toISOString(),
        },
        {
            requesterId: 44,
            responderId: 80,
            status: 'accepted',
            message: 'Hi! Would love to connect and discuss cloud computing opportunities.',
            createdAt: new Date('2024-11-25T10:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-27T14:20:00Z').toISOString(),
        },
        {
            requesterId: 47,
            responderId: 82,
            status: 'accepted',
            message: 'Hey! Same CS branch. Seeking guidance on higher studies abroad.',
            createdAt: new Date('2024-11-28T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-11-30T16:50:00Z').toISOString(),
        },
        {
            requesterId: 50,
            responderId: 84,
            status: 'pending',
            message: 'Hello! Would appreciate your mentorship in data science field.',
            createdAt: new Date('2024-12-29T11:35:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 3,
            responderId: 86,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-02T14:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T10:25:00Z').toISOString(),
        },
        {
            requesterId: 6,
            responderId: 88,
            status: 'accepted',
            message: 'Hi! Would love to learn about your experience in product management.',
            createdAt: new Date('2024-12-05T09:15:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T15:40:00Z').toISOString(),
        },
        {
            requesterId: 9,
            responderId: 90,
            status: 'accepted',
            message: 'Hey! Same branch. Seeking advice on full-stack development career.',
            createdAt: new Date('2024-12-08T12:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T16:10:00Z').toISOString(),
        },
        {
            requesterId: 12,
            responderId: 52,
            status: 'accepted',
            message: 'Hello! Would appreciate insights on interview preparation.',
            createdAt: new Date('2024-12-10T15:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-11T11:20:00Z').toISOString(),
        },
        {
            requesterId: 15,
            responderId: 54,
            status: 'pending',
            message: 'Hi! Looking for guidance on switching from dev to AI/ML. Would love to connect!',
            createdAt: new Date('2024-12-30T10:55:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 18,
            responderId: 56,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-13T13:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-14T16:40:00Z').toISOString(),
        },
        {
            requesterId: 21,
            responderId: 58,
            status: 'accepted',
            message: 'Hey! Would love to hear about your journey from college to senior engineer.',
            createdAt: new Date('2024-12-15T11:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T14:35:00Z').toISOString(),
        },
        {
            requesterId: 24,
            responderId: 60,
            status: 'accepted',
            message: 'Hi! Same CS branch. Seeking mentorship for career growth.',
            createdAt: new Date('2024-12-17T14:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-18T10:25:00Z').toISOString(),
        },
        {
            requesterId: 27,
            responderId: 62,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-12-18T09:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-26T13:45:00Z').toISOString(),
        },
        {
            requesterId: 30,
            responderId: 64,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-19T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-20T16:15:00Z').toISOString(),
        },
        {
            requesterId: 33,
            responderId: 66,
            status: 'accepted',
            message: 'Hi! Would appreciate guidance on building strong technical foundations.',
            createdAt: new Date('2024-12-20T15:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-21T11:50:00Z').toISOString(),
        },
        {
            requesterId: 36,
            responderId: 68,
            status: 'accepted',
            message: 'Hey! Same branch. Would love to discuss emerging technologies.',
            createdAt: new Date('2024-12-21T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-22T14:10:00Z').toISOString(),
        },
        {
            requesterId: 39,
            responderId: 70,
            status: 'pending',
            message: 'Hello! Seeking guidance on DevOps career path. Would appreciate your time!',
            createdAt: new Date('2024-12-31T13:45:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 42,
            responderId: 72,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-22T11:55:00Z').toISOString(),
            respondedAt: new Date('2024-12-23T15:30:00Z').toISOString(),
        },
        {
            requesterId: 45,
            responderId: 74,
            status: 'accepted',
            message: 'Hi! Would love to learn about your experience in cybersecurity.',
            createdAt: new Date('2024-12-23T14:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-24T10:45:00Z').toISOString(),
        },
        {
            requesterId: 48,
            responderId: 76,
            status: 'accepted',
            message: 'Hey! Same CS branch. Seeking advice on work-life balance in tech.',
            createdAt: new Date('2024-12-24T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-25T13:15:00Z').toISOString(),
        },
        {
            requesterId: 51,
            responderId: 78,
            status: 'accepted',
            message: 'Hello! Would appreciate insights on transitioning to tech leadership.',
            createdAt: new Date('2024-12-25T12:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-26T16:50:00Z').toISOString(),
        },
        {
            requesterId: 4,
            responderId: 80,
            status: 'pending',
            message: 'Hi! Looking for guidance on blockchain development. Would love to connect!',
            createdAt: new Date('2025-01-01T11:20:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 7,
            responderId: 82,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-26T14:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-27T10:55:00Z').toISOString(),
        },
        {
            requesterId: 10,
            responderId: 84,
            status: 'accepted',
            message: 'Hey! Would love to discuss your journey in mobile app development.',
            createdAt: new Date('2024-12-27T13:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-28T16:40:00Z').toISOString(),
        },
        {
            requesterId: 13,
            responderId: 86,
            status: 'accepted',
            message: 'Hi! Same branch. Seeking mentorship for competitive programming.',
            createdAt: new Date('2024-12-28T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-29T15:20:00Z').toISOString(),
        },
        {
            requesterId: 16,
            responderId: 88,
            status: 'accepted',
            message: 'Hello! Would appreciate advice on building a strong GitHub profile.',
            createdAt: new Date('2024-12-29T14:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-30T10:50:00Z').toISOString(),
        },
        {
            requesterId: 19,
            responderId: 90,
            status: 'accepted',
            message: 'Hey! Would love to learn about your experience in system design.',
            createdAt: new Date('2024-12-30T09:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-31T14:15:00Z').toISOString(),
        },

        // Mentorship seeking connections (30)
        {
            requesterId: 22,
            responderId: 53,
            status: 'accepted',
            message: 'Hi! I\'m looking for mentorship in web development. Would appreciate your guidance.',
            createdAt: new Date('2024-09-12T10:20:00Z').toISOString(),
            respondedAt: new Date('2024-09-14T15:35:00Z').toISOString(),
        },
        {
            requesterId: 25,
            responderId: 55,
            status: 'accepted',
            message: 'Hello! Seeking guidance on software engineering best practices. Would love to connect!',
            createdAt: new Date('2024-09-20T13:45:00Z').toISOString(),
            respondedAt: new Date('2024-09-22T11:20:00Z').toISOString(),
        },
        {
            requesterId: 28,
            responderId: 57,
            status: 'pending',
            message: 'Hey! I\'m interested in machine learning. Would appreciate your mentorship.',
            createdAt: new Date('2024-12-26T14:50:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 31,
            responderId: 59,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-05T11:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-07T16:10:00Z').toISOString(),
        },
        {
            requesterId: 34,
            responderId: 61,
            status: 'accepted',
            message: 'Hi! Looking for mentorship on building scalable systems. Would love your guidance.',
            createdAt: new Date('2024-10-12T14:15:00Z').toISOString(),
            respondedAt: new Date('2024-10-14T10:45:00Z').toISOString(),
        },
        {
            requesterId: 37,
            responderId: 63,
            status: 'accepted',
            message: 'Hello! Seeking guidance on frontend development career path.',
            createdAt: new Date('2024-10-20T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-10-21T15:25:00Z').toISOString(),
        },
        {
            requesterId: 40,
            responderId: 65,
            status: 'accepted',
            message: 'Hey! Would appreciate mentorship on cloud technologies and DevOps.',
            createdAt: new Date('2024-10-28T12:55:00Z').toISOString(),
            respondedAt: new Date('2024-10-30T16:30:00Z').toISOString(),
        },
        {
            requesterId: 43,
            responderId: 67,
            status: 'pending',
            message: 'Hi! I\'m looking for guidance on data structures and algorithms. Would love to connect!',
            createdAt: new Date('2024-12-28T11:20:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 46,
            responderId: 69,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-08T15:35:00Z').toISOString(),
            respondedAt: new Date('2024-11-09T11:50:00Z').toISOString(),
        },
        {
            requesterId: 49,
            responderId: 71,
            status: 'accepted',
            message: 'Hello! Seeking mentorship on building a career in AI research.',
            createdAt: new Date('2024-11-15T10:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-16T14:20:00Z').toISOString(),
        },
        {
            requesterId: 2,
            responderId: 73,
            status: 'accepted',
            message: 'Hi! Would appreciate guidance on open-source contributions.',
            createdAt: new Date('2024-11-20T13:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-21T16:40:00Z').toISOString(),
        },
        {
            requesterId: 5,
            responderId: 75,
            status: 'rejected',
            message: 'Hey! Looking for mentorship in mobile development.',
            createdAt: new Date('2024-11-22T11:10:00Z').toISOString(),
            respondedAt: new Date('2024-11-30T09:35:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 77,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-25T14:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T10:25:00Z').toISOString(),
        },
        {
            requesterId: 11,
            responderId: 79,
            status: 'accepted',
            message: 'Hello! Seeking guidance on database management and optimization.',
            createdAt: new Date('2024-11-28T09:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-29T15:55:00Z').toISOString(),
        },
        {
            requesterId: 14,
            responderId: 81,
            status: 'accepted',
            message: 'Hi! Would appreciate mentorship on software architecture design.',
            createdAt: new Date('2024-12-02T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T16:15:00Z').toISOString(),
        },
        {
            requesterId: 17,
            responderId: 83,
            status: 'pending',
            message: 'Hey! I\'m looking for guidance on API development. Would love your mentorship!',
            createdAt: new Date('2024-12-29T14:25:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 20,
            responderId: 85,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-05T11:15:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T15:40:00Z').toISOString(),
        },
        {
            requesterId: 23,
            responderId: 87,
            status: 'accepted',
            message: 'Hello! Seeking guidance on building real-time applications.',
            createdAt: new Date('2024-12-08T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T10:50:00Z').toISOString(),
        },
        {
            requesterId: 26,
            responderId: 89,
            status: 'accepted',
            message: 'Hi! Would appreciate mentorship on testing and quality assurance.',
            createdAt: new Date('2024-12-10T09:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-11T14:20:00Z').toISOString(),
        },
        {
            requesterId: 29,
            responderId: 91,
            status: 'accepted',
            message: 'Hey! Looking for guidance on microservices architecture.',
            createdAt: new Date('2024-12-12T13:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-13T16:35:00Z').toISOString(),
        },
        {
            requesterId: 32,
            responderId: 53,
            status: 'pending',
            message: 'Hello! I\'m interested in GraphQL and modern APIs. Would love your guidance!',
            createdAt: new Date('2024-12-30T11:55:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 35,
            responderId: 55,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-15T15:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T11:40:00Z').toISOString(),
        },
        {
            requesterId: 38,
            responderId: 57,
            status: 'accepted',
            message: 'Hi! Seeking mentorship on containerization and Kubernetes.',
            createdAt: new Date('2024-12-17T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-18T14:50:00Z').toISOString(),
        },
        {
            requesterId: 41,
            responderId: 59,
            status: 'accepted',
            message: 'Hey! Would appreciate guidance on serverless architecture.',
            createdAt: new Date('2024-12-19T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-20T16:45:00Z').toISOString(),
        },
        {
            requesterId: 44,
            responderId: 61,
            status: 'accepted',
            message: 'Hello! Looking for mentorship on performance optimization techniques.',
            createdAt: new Date('2024-12-21T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-22T15:15:00Z').toISOString(),
        },
        {
            requesterId: 47,
            responderId: 63,
            status: 'pending',
            message: 'Hi! I\'m interested in learning about CI/CD pipelines. Would love to connect!',
            createdAt: new Date('2024-12-31T14:30:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 50,
            responderId: 65,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-23T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-24T13:25:00Z').toISOString(),
        },
        {
            requesterId: 3,
            responderId: 67,
            status: 'accepted',
            message: 'Hello! Seeking guidance on security best practices in development.',
            createdAt: new Date('2024-12-24T12:15:00Z').toISOString(),
            respondedAt: new Date('2024-12-25T16:30:00Z').toISOString(),
        },
        {
            requesterId: 6,
            responderId: 69,
            status: 'accepted',
            message: 'Hi! Would appreciate mentorship on agile methodologies and scrum.',
            createdAt: new Date('2024-12-25T14:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-26T10:20:00Z').toISOString(),
        },
        {
            requesterId: 9,
            responderId: 71,
            status: 'accepted',
            message: 'Hey! Looking for guidance on technical writing and documentation.',
            createdAt: new Date('2024-12-26T11:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-27T15:50:00Z').toISOString(),
        },

        // ===== ALUMNI-TO-ALUMNI CONNECTIONS (30 total) =====
        // Same company alumni (10)
        {
            requesterId: 52,
            responderId: 54,
            status: 'accepted',
            message: 'Hey! I see we both work at Google. Let\'s connect!',
            createdAt: new Date('2024-10-01T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-02T14:45:00Z').toISOString(),
        },
        {
            requesterId: 56,
            responderId: 58,
            status: 'accepted',
            message: 'Hi! Same company. Would love to catch up and share experiences.',
            createdAt: new Date('2024-10-10T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-12T16:35:00Z').toISOString(),
        },
        {
            requesterId: 60,
            responderId: 62,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-18T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-10-20T15:10:00Z').toISOString(),
        },
        {
            requesterId: 64,
            responderId: 66,
            status: 'accepted',
            message: 'Hello! Working at the same company. Let\'s network!',
            createdAt: new Date('2024-10-25T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-27T10:55:00Z').toISOString(),
        },
        {
            requesterId: 68,
            responderId: 70,
            status: 'pending',
            message: 'Hey! Same company and alma mater. Would love to connect!',
            createdAt: new Date('2024-12-27T12:15:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 72,
            responderId: 74,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-05T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-11-06T13:25:00Z').toISOString(),
        },
        {
            requesterId: 76,
            responderId: 78,
            status: 'accepted',
            message: 'Hi! Same company. Let\'s collaborate and exchange ideas!',
            createdAt: new Date('2024-11-12T15:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-14T11:30:00Z').toISOString(),
        },
        {
            requesterId: 80,
            responderId: 82,
            status: 'accepted',
            message: 'Hey! Working together at the same org. Let\'s connect!',
            createdAt: new Date('2024-11-20T10:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-21T14:40:00Z').toISOString(),
        },
        {
            requesterId: 84,
            responderId: 86,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-11-25T13:35:00Z').toISOString(),
            respondedAt: new Date('2024-12-02T10:15:00Z').toISOString(),
        },
        {
            requesterId: 88,
            responderId: 90,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-28T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-11-29T16:20:00Z').toISOString(),
        },

        // Same graduation year batch (10)
        {
            requesterId: 53,
            responderId: 55,
            status: 'accepted',
            message: 'Hey! Same batch of 2020. Let\'s reconnect!',
            createdAt: new Date('2024-10-03T14:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-05T11:45:00Z').toISOString(),
        },
        {
            requesterId: 57,
            responderId: 59,
            status: 'accepted',
            message: 'Hi! Remember us from the 2020 batch? Let\'s catch up!',
            createdAt: new Date('2024-10-12T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-10-13T15:50:00Z').toISOString(),
        },
        {
            requesterId: 61,
            responderId: 63,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-20T13:10:00Z').toISOString(),
            respondedAt: new Date('2024-10-22T16:25:00Z').toISOString(),
        },
        {
            requesterId: 65,
            responderId: 67,
            status: 'pending',
            message: 'Hello! Same graduation year. Would love to reconnect and share experiences!',
            createdAt: new Date('2024-12-28T14:45:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 69,
            responderId: 71,
            status: 'accepted',
            message: 'Hey! Class of 2021. Let\'s network and stay in touch!',
            createdAt: new Date('2024-11-08T11:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-09T15:15:00Z').toISOString(),
        },
        {
            requesterId: 73,
            responderId: 75,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-15T09:55:00Z').toISOString(),
            respondedAt: new Date('2024-11-16T14:20:00Z').toISOString(),
        },
        {
            requesterId: 77,
            responderId: 79,
            status: 'accepted',
            message: 'Hi! Same batch. Would love to discuss our career journeys!',
            createdAt: new Date('2024-11-22T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-11-23T16:10:00Z').toISOString(),
        },
        {
            requesterId: 81,
            responderId: 83,
            status: 'accepted',
            message: 'Hey! Remember the good old college days? Let\'s connect!',
            createdAt: new Date('2024-11-28T15:25:00Z').toISOString(),
            respondedAt: new Date('2024-11-30T11:50:00Z').toISOString(),
        },
        {
            requesterId: 85,
            responderId: 87,
            status: 'pending',
            message: 'Hello! Same graduation year. Would love to reconnect after all these years!',
            createdAt: new Date('2024-12-29T10:35:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 89,
            responderId: 91,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-05T13:45:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T16:30:00Z').toISOString(),
        },

        // Same branch alumni (10)
        {
            requesterId: 52,
            responderId: 56,
            status: 'accepted',
            message: 'Hi! Same CS branch. Let\'s connect and share insights!',
            createdAt: new Date('2024-10-08T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-09T14:35:00Z').toISOString(),
        },
        {
            requesterId: 54,
            responderId: 58,
            status: 'accepted',
            message: 'Hey! Both CS grads. Would love to discuss industry trends.',
            createdAt: new Date('2024-10-15T14:50:00Z').toISOString(),
            respondedAt: new Date('2024-10-17T11:25:00Z').toISOString(),
        },
        {
            requesterId: 60,
            responderId: 64,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-10-22T10:15:00Z').toISOString(),
            respondedAt: new Date('2024-10-24T15:40:00Z').toISOString(),
        },
        {
            requesterId: 62,
            responderId: 66,
            status: 'rejected',
            message: 'Hello! Would like to connect.',
            createdAt: new Date('2024-10-28T13:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-05T09:50:00Z').toISOString(),
        },
        {
            requesterId: 68,
            responderId: 72,
            status: 'accepted',
            message: 'Hi! Same branch. Let\'s exchange career experiences!',
            createdAt: new Date('2024-11-10T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-11T16:20:00Z').toISOString(),
        },
        {
            requesterId: 70,
            responderId: 74,
            status: 'accepted',
            message: 'Hey! CS alumni. Would love to collaborate on projects!',
            createdAt: new Date('2024-11-18T14:10:00Z').toISOString(),
            respondedAt: new Date('2024-11-19T10:35:00Z').toISOString(),
        },
        {
            requesterId: 76,
            responderId: 80,
            status: 'pending',
            message: 'Hello! Same branch background. Would love to connect and share insights!',
            createdAt: new Date('2024-12-30T12:25:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 78,
            responderId: 82,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-02T09:55:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T14:30:00Z').toISOString(),
        },
        {
            requesterId: 84,
            responderId: 88,
            status: 'accepted',
            message: 'Hi! Both from CS department. Let\'s network!',
            createdAt: new Date('2024-12-08T12:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T16:15:00Z').toISOString(),
        },
        {
            requesterId: 86,
            responderId: 90,
            status: 'accepted',
            message: 'Hey! Same CS background. Would love to discuss tech innovations!',
            createdAt: new Date('2024-12-15T15:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T11:45:00Z').toISOString(),
        },

        // ===== STUDENT-TO-FACULTY CONNECTIONS (15 total) =====
        {
            requesterId: 2,
            responderId: 92,
            status: 'accepted',
            message: 'Hi Professor! I\'m in your CS department. Would love to connect.',
            createdAt: new Date('2024-09-05T10:15:00Z').toISOString(),
            respondedAt: new Date('2024-09-06T14:30:00Z').toISOString(),
        },
        {
            requesterId: 8,
            responderId: 94,
            status: 'accepted',
            message: 'Hello Professor! Your lectures are inspiring. Would appreciate your guidance.',
            createdAt: new Date('2024-09-15T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-09-17T11:45:00Z').toISOString(),
        },
        {
            requesterId: 14,
            responderId: 96,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-09-25T11:35:00Z').toISOString(),
            respondedAt: new Date('2024-09-27T15:50:00Z').toISOString(),
        },
        {
            requesterId: 20,
            responderId: 98,
            status: 'pending',
            message: 'Hi Professor! I\'m interested in research opportunities. Would love to connect!',
            createdAt: new Date('2024-12-26T14:40:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 26,
            responderId: 100,
            status: 'accepted',
            message: 'Hello Sir! Would appreciate guidance on my final year project.',
            createdAt: new Date('2024-10-10T10:25:00Z').toISOString(),
            respondedAt: new Date('2024-10-12T14:15:00Z').toISOString(),
        },
        {
            requesterId: 32,
            responderId: 102,
            status: 'accepted',
            message: 'Hi Professor! Your course was excellent. Would love to stay connected.',
            createdAt: new Date('2024-10-20T13:50:00Z').toISOString(),
            respondedAt: new Date('2024-10-22T16:30:00Z').toISOString(),
        },
        {
            requesterId: 38,
            responderId: 104,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-01T11:15:00Z').toISOString(),
            respondedAt: new Date('2024-11-02T15:40:00Z').toISOString(),
        },
        {
            requesterId: 44,
            responderId: 106,
            status: 'accepted',
            message: 'Hello Professor! Would love to discuss career opportunities in academia.',
            createdAt: new Date('2024-11-10T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-11-12T10:55:00Z').toISOString(),
        },
        {
            requesterId: 50,
            responderId: 92,
            status: 'pending',
            message: 'Hi Sir! I\'m interested in your research area. Would appreciate your guidance!',
            createdAt: new Date('2024-12-28T12:20:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 5,
            responderId: 94,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-25T09:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-26T14:20:00Z').toISOString(),
        },
        {
            requesterId: 11,
            responderId: 96,
            status: 'accepted',
            message: 'Hello Professor! Would love to get mentorship from you.',
            createdAt: new Date('2024-12-02T12:10:00Z').toISOString(),
            respondedAt: new Date('2024-12-03T16:35:00Z').toISOString(),
        },
        {
            requesterId: 17,
            responderId: 98,
            status: 'accepted',
            message: 'Hi Sir! Your guidance would be valuable for my career.',
            createdAt: new Date('2024-12-08T15:25:00Z').toISOString(),
            respondedAt: new Date('2024-12-09T11:50:00Z').toISOString(),
        },
        {
            requesterId: 23,
            responderId: 100,
            status: 'rejected',
            message: 'Hello Professor! Would like to connect.',
            createdAt: new Date('2024-12-10T10:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-18T14:15:00Z').toISOString(),
        },
        {
            requesterId: 29,
            responderId: 102,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-15T13:55:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T16:30:00Z').toISOString(),
        },
        {
            requesterId: 35,
            responderId: 104,
            status: 'accepted',
            message: 'Hi Professor! Would appreciate your advice on higher studies.',
            createdAt: new Date('2024-12-20T11:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-21T15:45:00Z').toISOString(),
        },

        // ===== ALUMNI-TO-FACULTY CONNECTIONS (10 total) =====
        {
            requesterId: 52,
            responderId: 92,
            status: 'accepted',
            message: 'Hi Professor! I\'m your former student from 2020. Would love to reconnect.',
            createdAt: new Date('2024-10-05T10:30:00Z').toISOString(),
            respondedAt: new Date('2024-10-06T14:45:00Z').toISOString(),
        },
        {
            requesterId: 58,
            responderId: 94,
            status: 'accepted',
            message: 'Hello Sir! Remember me from the 2020 batch? Would love to catch up.',
            createdAt: new Date('2024-10-18T13:20:00Z').toISOString(),
            respondedAt: new Date('2024-10-20T16:35:00Z').toISOString(),
        },
        {
            requesterId: 64,
            responderId: 96,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-11-02T11:45:00Z').toISOString(),
            respondedAt: new Date('2024-11-03T15:10:00Z').toISOString(),
        },
        {
            requesterId: 70,
            responderId: 98,
            status: 'pending',
            message: 'Hi Professor! Your guidance shaped my career. Would love to reconnect!',
            createdAt: new Date('2024-12-29T14:25:00Z').toISOString(),
            respondedAt: null,
        },
        {
            requesterId: 76,
            responderId: 100,
            status: 'accepted',
            message: 'Hello Sir! I\'m working at Microsoft now. Would love to share my journey.',
            createdAt: new Date('2024-11-20T10:35:00Z').toISOString(),
            respondedAt: new Date('2024-11-21T14:50:00Z').toISOString(),
        },
        {
            requesterId: 82,
            responderId: 102,
            status: 'accepted',
            message: 'Hi Professor! Your teachings still guide me. Would love to reconnect.',
            createdAt: new Date('2024-11-28T13:15:00Z').toISOString(),
            respondedAt: new Date('2024-11-29T16:40:00Z').toISOString(),
        },
        {
            requesterId: 88,
            responderId: 104,
            status: 'accepted',
            message: null,
            createdAt: new Date('2024-12-05T11:50:00Z').toISOString(),
            respondedAt: new Date('2024-12-06T15:25:00Z').toISOString(),
        },
        {
            requesterId: 54,
            responderId: 106,
            status: 'rejected',
            message: 'Hello Professor! Would like to reconnect.',
            createdAt: new Date('2024-12-08T14:30:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T10:45:00Z').toISOString(),
        },
        {
            requesterId: 66,
            responderId: 92,
            status: 'accepted',
            message: 'Hi Sir! I\'m now at Amazon. Would love to share my experiences.',
            createdAt: new Date('2024-12-15T09:40:00Z').toISOString(),
            respondedAt: new Date('2024-12-16T13:55:00Z').toISOString(),
        },
        {
            requesterId: 72,
            responderId: 94,
            status: 'accepted',
            message: 'Hello Professor! Your mentorship made a difference. Let\'s stay connected.',
            createdAt: new Date('2024-12-22T12:20:00Z').toISOString(),
            respondedAt: new Date('2024-12-23T16:10:00Z').toISOString(),
        },
    ];

    await db.insert(connections).values(sampleConnections);
    
    console.log('✅ Connections seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});