import { db } from '@/db';
import { events } from '@/db/schema';

async function main() {
    const now = new Date();
    const today = now.toISOString();
    
    const sampleEvents = [
        // WORKSHOPS (12 events)
        {
            organizerId: 67,
            title: 'React & Next.js Workshop for Beginners',
            description: 'Learn modern web development with React and Next.js from scratch. This hands-on workshop covers component architecture, state management, routing, and deployment. Perfect for students and alumni looking to build modern web applications. Our experienced instructor will guide you through real-world projects and best practices. By the end, you will have built and deployed your own full-stack application.',
            location: 'Terna Engineering College, Nerul - Computer Lab 301',
            startDate: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 40,
            isPaid: true,
            price: '₹499',
            imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 94,
            title: 'Python Programming & Data Science Bootcamp',
            description: 'Master Python programming and dive into data science fundamentals. This comprehensive workshop covers Python basics, pandas, NumPy, data visualization with matplotlib and seaborn. Learn how to clean, analyze, and visualize data effectively. Industry experts will share real-world case studies and career opportunities in data science. Includes hands-on exercises with actual datasets from various domains.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 50,
            isPaid: true,
            price: '₹999',
            imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 58,
            title: 'Machine Learning Workshop - From Basics to Deployment',
            description: 'Comprehensive ML workshop covering supervised and unsupervised learning algorithms. Learn to build, train, and deploy machine learning models using scikit-learn and TensorFlow. Topics include regression, classification, clustering, and neural networks. We will work on real-world projects including image recognition and predictive analytics. Participants will deploy their ML models to cloud platforms by the end of the workshop.',
            location: 'Terna Campus Auditorium',
            startDate: new Date(now.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 35 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 45,
            isPaid: true,
            price: '₹1499',
            imageUrl: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 73,
            title: 'Cloud Computing with AWS - Hands-on Workshop',
            description: 'Learn cloud computing fundamentals with Amazon Web Services. This workshop covers EC2, S3, Lambda, RDS, and deployment strategies. Perfect for students preparing for cloud certifications and alumni working in DevOps. We will build and deploy scalable applications using AWS services. Hands-on labs include setting up VPC, load balancers, and auto-scaling groups. Industry best practices for security and cost optimization will be covered.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 20 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 35,
            isPaid: true,
            price: '₹999',
            imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 98,
            title: 'DevOps Essentials - CI/CD Pipeline Workshop',
            description: 'Master DevOps practices and build automated CI/CD pipelines. Learn Git workflows, Docker containerization, Kubernetes orchestration, and Jenkins automation. This workshop is designed for developers looking to streamline their deployment process. We will set up complete DevOps pipelines from code commit to production deployment. Topics include infrastructure as code, monitoring, and logging best practices. Participants will receive DevOps toolkit and resources.',
            location: 'Terna Engineering College, Nerul - Lab 205',
            startDate: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 30,
            isPaid: true,
            price: '₹1499',
            imageUrl: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 62,
            title: 'UI/UX Design Workshop - Figma & Design Thinking',
            description: 'Learn user-centered design principles and master Figma for creating stunning interfaces. This workshop covers design thinking methodology, wireframing, prototyping, and user testing. Perfect for students interested in product design and UX careers. We will work on real design challenges and create portfolio-worthy projects. Topics include color theory, typography, accessibility, and responsive design. Industry designers will review your work and provide feedback.',
            location: 'WeWork Bangalore - Creative Studio',
            startDate: new Date(now.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 18 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 35,
            isPaid: true,
            price: '₹799',
            imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 3,
            title: 'Mobile App Development with Flutter',
            description: 'Build cross-platform mobile applications using Flutter and Dart. This hands-on workshop covers widget architecture, state management, API integration, and app deployment. Learn to create beautiful, performant apps for both iOS and Android from a single codebase. We will build a complete social media app during the workshop. Topics include Firebase integration, push notifications, and app store deployment. Perfect for aspiring mobile developers.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 40,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
            status: 'approved',
            branch: 'IT',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 81,
            title: 'Blockchain & Web3 Development Workshop',
            description: 'Explore blockchain technology and build decentralized applications. Learn Solidity programming, smart contract development, and Web3 integration. This workshop covers Ethereum, NFTs, DeFi protocols, and the future of decentralized internet. We will deploy smart contracts on test networks and build a complete dApp. Topics include cryptography basics, consensus mechanisms, and blockchain security. Industry experts will discuss career opportunities in Web3.',
            location: 'Terna Engineering College, Nerul - Seminar Hall',
            startDate: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 30,
            isPaid: true,
            price: '₹1499',
            imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 96,
            title: 'Advanced CAD Workshop - SolidWorks Masterclass',
            description: 'Master 3D modeling and engineering design with SolidWorks. This workshop covers parametric modeling, assembly design, simulation, and technical drawings. Perfect for mechanical and civil engineering students. Learn industry-standard CAD practices used in product design and manufacturing. We will work on real engineering projects including mechanism design and FEA analysis. Participants will create portfolio-ready design projects.',
            location: 'Terna Campus - CAD Lab',
            startDate: new Date(now.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 28 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 25,
            isPaid: true,
            price: '₹799',
            imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 69,
            title: 'Cybersecurity Workshop - Ethical Hacking Basics',
            description: 'Learn cybersecurity fundamentals and ethical hacking techniques. This workshop covers network security, vulnerability assessment, penetration testing, and security best practices. We will explore common security vulnerabilities and how to protect against them. Hands-on labs include using Kali Linux, Wireshark, and security testing tools. Topics include web application security, OWASP Top 10, and incident response. Perfect for students interested in security careers.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 32 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 32 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 45,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 54,
            title: 'Game Development Workshop - Unity & C#',
            description: 'Create your own games using Unity game engine and C# programming. This workshop covers game physics, character controllers, AI, and game mechanics. Learn to build 2D and 3D games from concept to deployment. We will create a complete platformer game during the workshop. Topics include animation, particle systems, sound design, and monetization strategies. Perfect for students passionate about game development.',
            location: 'Terna Engineering College, Nerul - Gaming Lab',
            startDate: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 30,
            isPaid: true,
            price: '₹999',
            imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 101,
            title: 'IoT Workshop - Building Smart Devices',
            description: 'Build Internet of Things applications using Arduino, Raspberry Pi, and cloud platforms. This hands-on workshop covers sensors, actuators, communication protocols, and IoT architectures. Learn to create smart home devices, environmental monitoring systems, and industrial IoT solutions. We will integrate IoT devices with mobile apps and web dashboards. Topics include MQTT, REST APIs, data visualization, and edge computing. Participants will build and take home their own IoT project.',
            location: 'Terna Campus - Electronics Lab',
            startDate: new Date(now.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 48 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 35,
            isPaid: true,
            price: '₹1299',
            imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // WEBINARS (10 events)
        {
            organizerId: 75,
            title: 'AI/ML Career Path - Industry Expert Panel',
            description: 'Join our expert panel discussion on building successful careers in Artificial Intelligence and Machine Learning. Industry leaders from Google, Microsoft, and leading AI startups will share their journey and insights. Learn about required skills, certifications, interview preparation, and career growth strategies. We will discuss emerging trends in AI including LLMs, computer vision, and reinforcement learning. Q&A session will address your specific career questions and concerns.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 150,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 88,
            title: 'From Campus to Corporate - Alumni Success Stories',
            description: 'Hear inspiring success stories from our distinguished alumni who are now leading tech professionals at top companies. Learn how they navigated their career journey from college to corporate success. They will share practical advice on skill development, networking, interview preparation, and career transitions. Topics include overcoming challenges, finding mentors, and creating opportunities. This motivational webinar will inspire you to achieve your career goals.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 22 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 200,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 93,
            title: 'Placement Preparation Masterclass - Crack Your Dream Job',
            description: 'Comprehensive placement preparation session covering aptitude, technical interviews, HR rounds, and salary negotiation. Learn proven strategies to excel in campus placements and off-campus opportunities. Industry recruiters will share what they look for in candidates. We will cover resume building, LinkedIn optimization, and personal branding. Topics include data structures, algorithms, system design, and behavioral questions. Mock interview tips and common mistakes to avoid will be discussed.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 17 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 17 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 180,
            isPaid: true,
            price: '₹199',
            imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 65,
            title: 'Entrepreneurship 101 - Building Your Startup',
            description: 'Learn how to build and scale a successful startup from experienced entrepreneurs and VCs. This webinar covers ideation, market validation, MVP development, and fundraising strategies. Successful alumni entrepreneurs will share their startup journey including failures and learnings. Topics include business models, customer acquisition, team building, and pitching to investors. We will discuss the startup ecosystem in India and opportunities for student entrepreneurs.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 120,
            isPaid: true,
            price: '₹299',
            imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 99,
            title: 'Data Engineering at Scale - Real World Practices',
            description: 'Deep dive into data engineering practices used at leading tech companies. Learn about building data pipelines, data warehousing, ETL processes, and big data technologies. Industry experts will discuss Spark, Kafka, Airflow, and modern data stack. Topics include data modeling, stream processing, data quality, and performance optimization. We will cover career paths in data engineering and required skills. Real-world case studies from production systems will be shared.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 38 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 38 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 100,
            isPaid: true,
            price: '₹499',
            imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 72,
            title: 'Product Management Career Roadmap',
            description: 'Discover how to transition into product management roles at top tech companies. Learn about product management frameworks, user research, roadmap planning, and stakeholder management. Industry PMs from FAANG companies will share their experience and insights. We will cover how engineers can transition to PM roles and required skills. Topics include product metrics, A/B testing, feature prioritization, and go-to-market strategies. Career advice and interview preparation tips will be provided.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 26 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 26 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 150,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 5,
            title: 'Cloud Architecture Best Practices - AWS & Azure',
            description: 'Learn cloud architecture patterns and best practices from certified cloud architects. This webinar covers microservices, serverless, containerization, and multi-cloud strategies. We will discuss real-world architecture decisions and trade-offs. Topics include high availability, disaster recovery, security, and cost optimization. Industry experts will share lessons learned from large-scale cloud migrations. Career opportunities for cloud architects and required certifications will be discussed.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 44 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 44 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 130,
            isPaid: true,
            price: '₹399',
            imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 84,
            title: 'Masters Abroad - Complete Guide to MS Applications',
            description: 'Comprehensive guide to pursuing Masters degree abroad from alumni studying at top universities. Learn about university selection, GRE/TOEFL preparation, SOP writing, and LOR strategies. We will cover application timelines, scholarships, visa process, and financial planning. Alumni from MIT, Stanford, CMU, and other top universities will share their application journey. Topics include choosing specialization, finding research opportunities, and adapting to life abroad.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 34 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 34 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 200,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 91,
            title: 'FinTech Revolution - Career Opportunities',
            description: 'Explore the booming FinTech industry and career opportunities in digital banking, payments, and blockchain. Industry leaders from PayTM, PhonePe, and FinTech startups will discuss the sector. Learn about required skills for roles in payments engineering, risk management, and regulatory tech. We will cover emerging trends like DeFi, digital currencies, and embedded finance. Topics include financial modeling, compliance, and cybersecurity in FinTech. Career paths and interview preparation will be discussed.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 52 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 140,
            isPaid: true,
            price: '₹299',
            imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 78,
            title: 'Open Source Contributions - Getting Started',
            description: 'Learn how to contribute to open source projects and build your developer profile. This webinar covers finding projects, understanding codebases, making first contributions, and engaging with communities. Maintainers of popular open source projects will share insights. We will discuss Git workflows, code review process, and communication best practices. Topics include GSoC, outreach programs, and career benefits of open source. Live demo of making a contribution will be shown.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 160,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // MEETUPS (8 events)
        {
            organizerId: 56,
            title: 'Alumni Meetup Bangalore 2024',
            description: 'Join fellow Terna alumni based in Bangalore for an evening of networking and reconnection. This casual meetup is perfect for catching up with old friends and making new connections. We will share career updates, discuss industry trends, and explore collaboration opportunities. Light refreshments will be provided. Whether you are a recent graduate or experienced professional, all alumni are welcome. RSVP to help us plan the event better.',
            location: 'WeWork Bangalore - Community Lounge',
            startDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 35,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 63,
            title: 'Tech Talk & Coffee - Mumbai Chapter',
            description: 'Informal tech meetup over coffee for Mumbai-based alumni and students. Share your latest projects, discuss emerging technologies, and learn from each other. This month we will have short lightning talks on interesting tech topics. Perfect opportunity for mentorship, collaboration, and knowledge sharing. Students preparing for placements can get career advice from experienced alumni. Bring your questions and be ready for engaging technical discussions.',
            location: 'Coffee House, Vashi - Private Room',
            startDate: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 25,
            isPaid: true,
            price: '₹99',
            imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 70,
            title: 'Startup Founders Networking Evening',
            description: 'Exclusive networking event for alumni entrepreneurs and aspiring founders. Share your startup journey, discuss challenges, and explore potential collaborations. Successful founders will share their experiences and lessons learned. Perfect for finding co-founders, advisors, and early customers. We will have structured networking sessions and open discussions. Light dinner will be provided. This is a great opportunity to build your entrepreneurial network.',
            location: 'Google Office, Mumbai - Event Space',
            startDate: new Date(now.getTime() + 36 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 36 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 30,
            isPaid: true,
            price: '₹299',
            imageUrl: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 86,
            title: 'Women in Tech - Networking & Mentorship',
            description: 'Empowering meetup for women in technology from our alumni network. Connect with successful women tech professionals, share experiences, and build meaningful relationships. We will discuss career challenges, work-life balance, and strategies for growth. Senior women leaders will offer mentorship and guidance. Topics include negotiation skills, leadership development, and breaking glass ceilings. This supportive environment encourages open dialogue and mutual support.',
            location: 'Microsoft Office, Pune - Conference Room',
            startDate: new Date(now.getTime() + 42 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 42 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 40,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 59,
            title: 'Design Community Meetup',
            description: 'Monthly gathering for designers and design enthusiasts from our alumni community. Share portfolio work, discuss design trends, and get feedback on your projects. We will have design critiques, tool demos, and collaborative brainstorming sessions. Perfect for UX/UI designers, graphic designers, and anyone interested in design. Network with design professionals from leading companies. Light snacks and beverages provided.',
            location: 'WeWork Bangalore - Creative Studio',
            startDate: new Date(now.getTime() + 27 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 27 * 24 * 60 * 60 * 1000 + 2.5 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 30,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1558403194-611308249627?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 77,
            title: 'Data Science Community Meetup',
            description: 'Join data scientists and ML engineers for knowledge sharing and networking. Present your data science projects, discuss ML challenges, and learn about latest techniques. We will have technical deep-dives into real-world ML applications. Perfect for both beginners and experienced professionals. Topics include model deployment, MLOps, and production best practices. Opportunity to find collaborators for kaggle competitions and projects.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() + 47 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 47 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 40,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 52,
            title: 'Product Managers Roundtable',
            description: 'Intimate roundtable discussion for product managers across different companies and domains. Share product challenges, discuss frameworks, and learn from each other. We will have case study discussions and collaborative problem-solving. Topics include product discovery, prioritization, metrics, and stakeholder management. Perfect for PMs at all experience levels. Network with PMs from top tech companies and startups.',
            location: 'Coffee House, Vashi - Conference Room',
            startDate: new Date(now.getTime() + 39 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 39 * 24 * 60 * 60 * 1000 + 2.5 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 20,
            isPaid: true,
            price: '₹199',
            imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 82,
            title: 'DevOps & SRE Community Gathering',
            description: 'Connect with DevOps engineers and SREs from our alumni network. Discuss infrastructure challenges, share automation scripts, and learn about reliability practices. We will have presentations on incident management, observability, and chaos engineering. Perfect for sharing tools, techniques, and war stories. Network with professionals working on large-scale distributed systems. Topics include Kubernetes, monitoring, and cloud infrastructure.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() + 54 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 54 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 35,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // CONFERENCES (5 events)
        {
            organizerId: 104,
            title: 'Annual Tech Symposium 2024',
            description: 'Premier technology conference bringing together students, alumni, faculty, and industry leaders. This three-day event features keynotes from tech giants, technical workshops, paper presentations, and hackathons. Topics span AI, cloud computing, blockchain, cybersecurity, and emerging technologies. Network with 300+ attendees including recruiters from top companies. Student projects will be showcased and best innovations awarded. Industry panels will discuss future of technology and career opportunities. Register early for discounted rates.',
            location: 'Terna Campus Auditorium & Labs',
            startDate: new Date(now.getTime() + 65 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 67 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'conference',
            maxAttendees: 300,
            isPaid: true,
            price: '₹1499',
            imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 2,
            title: 'International Conference on AI & Data Science',
            description: 'Two-day international conference featuring renowned researchers and industry practitioners in AI and Data Science. Peer-reviewed paper presentations, poster sessions, and workshops on cutting-edge research. Keynotes from professors at MIT, Stanford, and IITs. Topics include deep learning, NLP, computer vision, and ethical AI. Networking sessions with researchers and opportunities to collaborate on research projects. Student research papers will be published in proceedings. Early bird registration available.',
            location: 'Terna Engineering College, Nerul - Main Auditorium',
            startDate: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 76 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'conference',
            maxAttendees: 250,
            isPaid: true,
            price: '₹2999',
            imageUrl: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 97,
            title: 'Engineering Innovation Summit',
            description: 'Cross-disciplinary engineering conference showcasing innovations across all engineering domains. Features include technical exhibitions, project demonstrations, and industry collaborations. Mechanical, electronics, civil, and computer engineering projects will be presented. Corporate sponsors will scout for talent and discuss internship opportunities. Panel discussions on Industry 4.0, sustainable engineering, and future technologies. Awards for best innovations and promising startups. Great platform for students to present final year projects.',
            location: 'Terna Campus - Multiple Venues',
            startDate: new Date(now.getTime() + 58 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 59 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'conference',
            maxAttendees: 200,
            isPaid: true,
            price: '₹999',
            imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 103,
            title: 'Cybersecurity & Privacy Conference',
            description: 'Specialized conference on cybersecurity, data privacy, and information security. Expert talks on latest security threats, defense strategies, and compliance requirements. Hands-on workshops on penetration testing, security auditing, and incident response. CTF competition with prizes for winners. Industry professionals will discuss career paths in security. Topics include zero trust, cloud security, and GDPR compliance. Networking with security professionals from finance, healthcare, and tech sectors.',
            location: 'Online & Hybrid - Terna Campus',
            startDate: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'conference',
            maxAttendees: 180,
            isPaid: true,
            price: '₹1999',
            imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 106,
            title: 'Startup & Entrepreneurship Conclave',
            description: 'Three-day conclave bringing together entrepreneurs, investors, and aspiring founders. Pitch competitions, mentorship sessions, and funding opportunities for student startups. Successful alumni founders will share their journey and lessons learned. VCs and angel investors will discuss investment criteria and trends. Workshops on business planning, legal aspects, and go-to-market strategies. Startup expo showcasing student ventures and innovations. Perfect platform to find co-founders, mentors, and early customers.',
            location: 'Terna Engineering College, Nerul',
            startDate: new Date(now.getTime() + 80 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 82 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'conference',
            maxAttendees: 220,
            isPaid: true,
            price: '₹1299',
            imageUrl: 'https://images.unsplash.com/photo-1560439514-4e9645039924?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // SOCIAL EVENTS (7 events)
        {
            organizerId: 61,
            title: 'Annual Alumni Reunion 2024',
            description: 'Grand reunion bringing together alumni from all batches for a memorable evening. Reconnect with old friends, relive college memories, and make new connections. Cultural performances, music, dinner, and awards for notable alumni achievements. Batch photo sessions and memorabilia displays. Faculty members will join to celebrate our community. Spouses and families welcome. This is the most anticipated event of the year. Book your tickets early as spots are limited.',
            location: 'Terna Campus - Open Ground & Auditorium',
            startDate: new Date(now.getTime() + 85 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 85 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 400,
            isPaid: true,
            price: '₹999',
            imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 95,
            title: 'Terna TechFest 2024',
            description: 'Annual technical and cultural festival featuring competitions, exhibitions, and performances. Hackathons, coding contests, robotics competitions, and project showcases. Cultural events including music, dance, drama, and fashion shows. Food stalls, games, and entertainment throughout the day. Alumni are invited as judges and mentors. Corporate sponsors will have stalls for recruitment and brand promotion. Open to all colleges with exciting prizes worth lakhs. Three days of non-stop fun and learning.',
            location: 'Terna Engineering College, Nerul - Campus Wide',
            startDate: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 92 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 500,
            isPaid: true,
            price: '₹499',
            imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 68,
            title: 'Sports Day - Alumni vs Students',
            description: 'Exciting sports day featuring friendly matches between alumni and current students. Cricket, football, basketball, badminton, and other indoor games. Team building activities and fun challenges for all age groups. Refreshments and lunch provided for all participants. Awards for winning teams and best players. Perfect opportunity for alumni to relive their sports days and interact with students. Families and supporters welcome to cheer. Register your team early.',
            location: 'Terna Sports Complex',
            startDate: new Date(now.getTime() + 31 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 31 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 200,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 4,
            title: 'Cultural Night - Music & Dance Extravaganza',
            description: 'Evening of music, dance, and entertainment celebrating our diverse culture. Live performances by alumni artists and student groups. Classical and contemporary music, dance performances, and stand-up comedy. Food stalls serving various cuisines and desserts. Open mic session for spontaneous performances. Perfect family-friendly event to unwind and enjoy. Networking in a relaxed and festive atmosphere. Limited seats available, register soon.',
            location: 'Terna Campus Auditorium',
            startDate: new Date(now.getTime() + 46 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 46 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 300,
            isPaid: true,
            price: '₹299',
            imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 89,
            title: 'Diwali Celebration - Alumni Get-together',
            description: 'Festive Diwali celebration bringing our alumni family together. Traditional ceremonies, rangoli competition, and diya decoration. Delicious festive food, sweets, and snacks. Cultural performances and music. Kids activities including games and face painting. Lucky draw and prizes for participants. Ethnic wear encouraged for the festive spirit. Perfect occasion to celebrate with your college family. Bring your family along for a memorable evening.',
            location: 'Terna Campus - Main Ground',
            startDate: new Date(now.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 24 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 250,
            isPaid: true,
            price: '₹199',
            imageUrl: 'https://images.unsplash.com/photo-1605811625636-ffe79aef55b8?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 76,
            title: 'New Year Party 2025 - Alumni Bash',
            description: 'Ring in the new year with fellow Ternites at our exclusive alumni party. DJ night with music spanning decades, dance floor, and live entertainment. Gala dinner with multiple cuisine options and unlimited beverages. Photo booths and fun activities throughout the night. Countdown to midnight with fireworks and celebrations. Dress code - cocktail attire. This sold-out event from last year is back by popular demand. Limited tickets available, book now.',
            location: 'Hotel Ramada, Navi Mumbai - Banquet Hall',
            startDate: new Date(now.getTime() + 95 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 95 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 200,
            isPaid: true,
            price: '₹2999',
            imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 100,
            title: 'Picnic & Adventure Day - Family Fun',
            description: 'Day-long picnic and adventure outing for alumni and their families. Activities include trekking, zip-lining, rope courses, and water sports. Kids play area with supervised activities and games. Team building exercises and group challenges. Breakfast, lunch, and evening snacks included. Transportation arranged from college. Perfect opportunity to bond with family and reconnect with alumni friends. Safety equipment and trained instructors provided. Book early as seats fill up fast.',
            location: 'Imagica Theme Park, Lonavala',
            startDate: new Date(now.getTime() + 63 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 63 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 150,
            isPaid: true,
            price: '₹1499',
            imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Past Events (20% - 8 events)
        {
            organizerId: 64,
            title: 'React Fundamentals Workshop',
            description: 'Comprehensive workshop on React fundamentals covering components, hooks, and state management. Participants built a complete todo application with modern React patterns. The workshop included best practices for code organization and performance optimization. Hands-on exercises helped solidify concepts. Alumni shared real-world React experiences from their companies. All participants received course materials and code repositories.',
            location: 'Terna Engineering College, Nerul - Lab 301',
            startDate: new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 35,
            isPaid: true,
            price: '₹499',
            imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 95 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 102,
            title: 'Career Guidance Webinar - Landing Your First Job',
            description: 'Extremely helpful webinar where senior alumni shared their placement experiences and tips. Topics included resume writing, LinkedIn optimization, and interview preparation. Mock interview sessions helped students identify areas for improvement. HR professionals explained what recruiters look for in candidates. The Q&A session addressed specific concerns about salary negotiation and job offers. Highly rated by attendees.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 120,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 65 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 57,
            title: 'Mumbai Alumni Networking Evening',
            description: 'Successful networking meetup for Mumbai-based alumni. Over 30 alumni from various batches and companies attended. Great discussions about tech trends and career opportunities. Several mentorship connections were formed. Students got valuable career advice and internship leads. Light refreshments and friendly atmosphere made it memorable. Many requested making this a monthly event.',
            location: 'Coffee House, Vashi',
            startDate: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 30,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 75 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 80 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 92,
            title: 'Python Data Analysis Workshop',
            description: 'Intensive workshop on data analysis using Python, pandas, and matplotlib. Participants learned to clean and analyze real datasets. Topics included data visualization, statistical analysis, and reporting. Everyone completed a project analyzing sales data. Alumni data scientists shared industry best practices. Great hands-on learning experience with practical takeaways.',
            location: 'Online - MS Teams',
            startDate: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 40,
            isPaid: true,
            price: '₹799',
            imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 65 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 70 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 6,
            title: 'Annual Sports Meet 2024',
            description: 'Fantastic sports day with participation from 150+ alumni and students. Cricket and football matches were highly competitive and entertaining. Basketball and badminton tournaments saw great sportsmanship. Alumni teams won most matches but students put up strong fights. Lunch and refreshments kept everyone energized. Awards ceremony celebrated winners and participation. Everyone had a great time reliving their sports days.',
            location: 'Terna Sports Complex',
            startDate: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 180,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 55 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 80,
            title: 'Design Thinking Workshop for Product Innovation',
            description: 'Engaging workshop on design thinking methodology for solving real problems. Teams worked on actual challenges and developed innovative solutions. The double diamond process was thoroughly explained and practiced. Prototyping sessions helped bring ideas to life. Alumni product managers shared how they use design thinking in their work. Participants left with frameworks they can immediately apply.',
            location: 'Terna Campus - Innovation Lab',
            startDate: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 30,
            isPaid: true,
            price: '₹699',
            imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 71,
            title: 'Tech Career Panel - Breaking into FAANG',
            description: 'Inspiring panel discussion with alumni working at Google, Amazon, and Microsoft. They shared their interview experiences and preparation strategies. Topics included coding practice, system design, and behavioral rounds. Real interview questions were discussed with solutions. Career progression at big tech companies was explained. Many students reported feeling motivated and clear about their goals after attending.',
            location: 'Online - Zoom',
            startDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
            category: 'webinar',
            maxAttendees: 150,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 105,
            title: 'Ganesh Chaturthi Celebration',
            description: 'Beautiful cultural celebration of Ganesh Chaturthi with the alumni community. Traditional ceremonies and prayers were followed by cultural performances. Delicious prasad and festive food was served to all. Kids enjoyed art and craft activities. The evening concluded with aarti and distribution of sweets. Over 200 alumni and families attended making it a grand success. The sense of community and tradition was heartwarming.',
            location: 'Terna Campus Auditorium',
            startDate: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'social',
            maxAttendees: 220,
            isPaid: false,
            price: null,
            imageUrl: 'https://images.unsplash.com/photo-1580193483125-6d5ca8f98d01?w=800',
            status: 'approved',
            branch: null,
            approvedBy: 1,
            approvedAt: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
            createdAt: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        },

        // Pending Events (5% - 2 events)
        {
            organizerId: 55,
            title: 'Quantum Computing Workshop',
            description: 'Introduction to quantum computing concepts and programming. Learn about qubits, quantum gates, and quantum algorithms. Hands-on session using IBM Quantum Experience. Topics include superposition, entanglement, and quantum applications. Perfect for students interested in cutting-edge technology. Industry experts will explain practical applications and career opportunities. Programming experience recommended but not required.',
            location: 'Terna Engineering College, Nerul',
            startDate: new Date(now.getTime() + 72 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 72 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
            category: 'workshop',
            maxAttendees: 40,
            isPaid: true,
            price: '₹1499',
            imageUrl: null,
            status: 'pending',
            branch: 'Computer Engineering',
            approvedBy: null,
            approvedAt: null,
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            organizerId: 87,
            title: 'Photography Masterclass & Photo Walk',
            description: 'Learn photography basics and advanced techniques from professional photographers. Topics include composition, lighting, exposure, and post-processing. Practical photo walk around campus to apply learnings. Camera gear discussion and recommendations. Perfect for hobbyists and aspiring photographers. Edit and critique session for best photos. All types of cameras welcome including smartphones.',
            location: 'Terna Campus & Surroundings',
            startDate: new Date(now.getTime() + 68 * 24 * 60 * 60 * 1000).toISOString(),
            endDate: new Date(now.getTime() + 68 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
            category: 'meetup',
            maxAttendees: 25,
            isPaid: true,
            price: '₹299',
            imageUrl: null,
            status: 'pending',
            branch: null,
            approvedBy: null,
            approvedAt: null,
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(events).values(sampleEvents);
    
    console.log('✅ Events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});