import { db } from '@/db';
import { jobs } from '@/db/schema';

async function main() {
    const sampleJobs = [
        // FULL-TIME POSITIONS (30 jobs)
        {
            postedById: 52,
            title: 'Software Development Engineer - Backend',
            company: 'Amazon',
            description: 'We are looking for a talented Backend Engineer to join our e-commerce platform team. You will be responsible for designing and developing scalable microservices, optimizing database queries, and ensuring high availability of our systems. Work with cutting-edge technologies and contribute to solutions used by millions of customers daily.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹15-22 LPA',
            skills: '["Java", "Spring Boot", "Microservices", "AWS", "Redis", "PostgreSQL"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-20T10:30:00Z').toISOString(),
            createdAt: new Date('2024-11-18T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-18T23:59:59Z').toISOString(),
        },
        {
            postedById: 55,
            title: 'Frontend Developer (React)',
            company: 'Razorpay',
            description: 'Join our frontend team to build intuitive and performant user interfaces for our payment gateway platform. You will work on complex React applications, implement pixel-perfect designs, and optimize performance for millions of transactions. Experience with TypeScript and modern frontend tooling is essential.',
            location: 'Bangalore/Remote',
            jobType: 'full-time',
            salary: '₹12-18 LPA',
            skills: '["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux", "REST API"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-22T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-20T11:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-20T23:59:59Z').toISOString(),
        },
        {
            postedById: 58,
            title: 'Data Scientist - ML/AI',
            company: 'Google',
            description: 'We are seeking a Data Scientist to work on machine learning models for our advertising platform. You will analyze large datasets, build predictive models, and deploy ML solutions at scale. Strong background in statistics, Python, and deep learning frameworks required. Join a team pushing the boundaries of AI.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹25-35 LPA',
            skills: '["Python", "TensorFlow", "PyTorch", "Machine Learning", "Deep Learning", "SQL", "Big Data"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-25T09:15:00Z').toISOString(),
            createdAt: new Date('2024-11-23T08:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-23T23:59:59Z').toISOString(),
        },
        {
            postedById: 61,
            title: 'Mechanical Design Engineer',
            company: 'Siemens',
            description: 'Looking for a Mechanical Design Engineer to work on industrial automation projects. You will be responsible for 3D modeling, FEA analysis, and design optimization of mechanical systems. Experience with AutoCAD, SolidWorks, and manufacturing processes is required. Opportunity to work on innovative automation solutions.',
            location: 'Pune',
            jobType: 'full-time',
            salary: '₹8-12 LPA',
            skills: '["AutoCAD", "SolidWorks", "CATIA", "FEA", "CAD", "Manufacturing"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-19T15:30:00Z').toISOString(),
            createdAt: new Date('2024-11-17T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-17T23:59:59Z').toISOString(),
        },
        {
            postedById: 64,
            title: 'Civil Site Engineer',
            company: 'L&T Construction',
            description: 'Join our infrastructure development team as a Civil Site Engineer. You will oversee construction activities, ensure quality standards, coordinate with contractors, and manage project timelines. Experience in residential or commercial construction projects preferred. Great opportunity for hands-on experience in large-scale projects.',
            location: 'Mumbai',
            jobType: 'full-time',
            salary: '₹6-8 LPA',
            skills: '["AutoCAD", "Project Management", "Site Supervision", "Structural Analysis", "Construction Management"]',
            status: 'approved',
            branch: 'Civil Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-21T11:00:00Z').toISOString(),
            createdAt: new Date('2024-11-19T09:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-19T23:59:59Z').toISOString(),
        },
        {
            postedById: 67,
            title: 'Product Manager - B2B SaaS',
            company: 'Freshworks',
            description: 'We are hiring a Product Manager to lead our B2B SaaS products. You will define product strategy, work with engineering teams, conduct user research, and drive product roadmap. Strong understanding of SaaS business models and agile methodologies required. Shape products used by thousands of businesses worldwide.',
            location: 'Chennai',
            jobType: 'full-time',
            salary: '₹18-25 LPA',
            skills: '["Product Management", "Agile", "User Research", "Data Analysis", "Roadmap Planning", "B2B SaaS"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-01T10:00:00Z').toISOString(),
            createdAt: new Date('2024-11-29T08:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-29T23:59:59Z').toISOString(),
        },
        {
            postedById: 70,
            title: 'DevOps Engineer',
            company: 'Swiggy',
            description: 'Join our DevOps team to build and maintain infrastructure for our food delivery platform. You will work on CI/CD pipelines, container orchestration, monitoring solutions, and cloud infrastructure. Experience with Kubernetes, Docker, and AWS is essential. Help us scale systems handling millions of daily orders.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹15-20 LPA',
            skills: '["Kubernetes", "Docker", "AWS", "CI/CD", "Terraform", "Python", "Linux"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-03T14:30:00Z').toISOString(),
            createdAt: new Date('2024-12-01T11:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-01T23:59:59Z').toISOString(),
        },
        {
            postedById: 73,
            title: 'Full Stack Developer',
            company: 'Zomato',
            description: 'We are looking for a Full Stack Developer to work on our restaurant management platform. You will build features end-to-end, from database design to frontend implementation. Strong knowledge of Node.js, React, and MongoDB required. Work in a fast-paced environment and see your code impact millions of users.',
            location: 'Delhi NCR',
            jobType: 'full-time',
            salary: '₹12-18 LPA',
            skills: '["Node.js", "React", "MongoDB", "Express", "JavaScript", "TypeScript", "REST API"]',
            status: 'approved',
            branch: 'Information Technology',
            approvedBy: 1,
            approvedAt: new Date('2024-12-05T09:00:00Z').toISOString(),
            createdAt: new Date('2024-12-03T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-03T23:59:59Z').toISOString(),
        },
        {
            postedById: 76,
            title: 'Electronics Design Engineer',
            company: 'Texas Instruments',
            description: 'Join our analog design team to develop cutting-edge semiconductor products. You will work on circuit design, simulation, layout verification, and testing of analog ICs. Strong understanding of analog electronics and experience with design tools like Cadence required. Opportunity to work on products powering the next generation of electronics.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹10-15 LPA',
            skills: '["Analog Design", "VLSI", "Cadence", "Circuit Design", "PCB Design", "Signal Processing"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-28T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-26T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-26T23:59:59Z').toISOString(),
        },
        {
            postedById: 79,
            title: 'QA Automation Engineer',
            company: 'Flipkart',
            description: 'We are hiring a QA Automation Engineer to ensure quality of our e-commerce platform. You will design test frameworks, write automated tests, perform API testing, and integrate tests into CI/CD pipelines. Experience with Selenium, Java, and performance testing tools required. Join our mission to deliver bug-free experiences.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹8-12 LPA',
            skills: '["Selenium", "Java", "TestNG", "API Testing", "Performance Testing", "Jenkins", "Automation"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-02T15:00:00Z').toISOString(),
            createdAt: new Date('2024-11-30T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-30T23:59:59Z').toISOString(),
        },
        {
            postedById: 82,
            title: 'Business Analyst',
            company: 'Accenture',
            description: 'Looking for a Business Analyst to work with enterprise clients on digital transformation projects. You will gather requirements, analyze business processes, create documentation, and bridge the gap between business and technology teams. Strong analytical and communication skills essential. Work on diverse projects across industries.',
            location: 'Pune',
            jobType: 'full-time',
            salary: '₹8-12 LPA',
            skills: '["Business Analysis", "Requirements Gathering", "SQL", "Excel", "Process Mapping", "Agile"]',
            status: 'approved',
            branch: 'Information Technology',
            approvedBy: 1,
            approvedAt: new Date('2024-11-27T10:30:00Z').toISOString(),
            createdAt: new Date('2024-11-25T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-25T23:59:59Z').toISOString(),
        },
        {
            postedById: 85,
            title: 'Mobile App Developer (React Native)',
            company: 'CRED',
            description: 'Join our mobile team to build delightful user experiences for our fintech app. You will develop features for iOS and Android platforms using React Native, optimize app performance, and implement engaging animations. Strong JavaScript skills and mobile development experience required. Work on an app with millions of active users.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹15-22 LPA',
            skills: '["React Native", "JavaScript", "TypeScript", "iOS", "Android", "Mobile Development", "Redux"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-02T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-02T23:59:59Z').toISOString(),
        },
        {
            postedById: 54,
            title: 'Cloud Solutions Architect',
            company: 'Microsoft',
            description: 'We are seeking a Cloud Solutions Architect to design and implement enterprise cloud solutions on Azure. You will work with customers to understand their requirements, architect scalable solutions, and guide implementation. Deep knowledge of Azure services, networking, and security required. Shape cloud adoption for major enterprises.',
            location: 'Hyderabad',
            jobType: 'full-time',
            salary: '₹25-35 LPA',
            skills: '["Azure", "Cloud Architecture", "Kubernetes", "Microservices", "DevOps", "Security", "Networking"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-24T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-22T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-22T23:59:59Z').toISOString(),
        },
        {
            postedById: 57,
            title: 'Structural Design Engineer',
            company: 'L&T',
            description: 'Join our structural engineering team to design buildings, bridges, and infrastructure projects. You will perform structural analysis, prepare detailed drawings, coordinate with architects, and ensure compliance with building codes. Proficiency in STAAD Pro and Revit required. Work on landmark projects shaping India\'s infrastructure.',
            location: 'Chennai',
            jobType: 'full-time',
            salary: '₹7-10 LPA',
            skills: '["STAAD Pro", "AutoCAD", "Revit", "Structural Analysis", "Concrete Design", "Steel Design"]',
            status: 'approved',
            branch: 'Civil Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-26T12:00:00Z').toISOString(),
            createdAt: new Date('2024-11-24T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-24T23:59:59Z').toISOString(),
        },
        {
            postedById: 60,
            title: 'Embedded Systems Engineer',
            company: 'Robert Bosch',
            description: 'We are looking for an Embedded Systems Engineer to develop firmware for automotive applications. You will write embedded C code, work with microcontrollers, debug hardware-software issues, and optimize performance. Experience with RTOS and automotive protocols required. Contribute to next-generation automotive technologies.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹10-15 LPA',
            skills: '["Embedded C", "Microcontrollers", "RTOS", "CAN Protocol", "Debugging", "ARM"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-01T09:30:00Z').toISOString(),
            createdAt: new Date('2024-11-29T11:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-29T23:59:59Z').toISOString(),
        },
        {
            postedById: 63,
            title: 'Data Analyst',
            company: 'Paytm',
            description: 'Join our analytics team to derive insights from payment transaction data. You will create dashboards, perform statistical analysis, identify trends, and support data-driven decision making. Strong SQL and Python skills required along with business acumen. Help optimize our payment platform serving millions of merchants.',
            location: 'Noida',
            jobType: 'full-time',
            salary: '₹8-12 LPA',
            skills: '["SQL", "Python", "Tableau", "Excel", "Data Analysis", "Statistics", "Data Visualization"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-30T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-28T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-28T23:59:59Z').toISOString(),
        },
        {
            postedById: 66,
            title: 'Network Security Engineer',
            company: 'Cisco',
            description: 'We are hiring a Network Security Engineer to design and implement security solutions for enterprise networks. You will configure firewalls, implement VPNs, monitor security incidents, and conduct vulnerability assessments. Strong knowledge of network protocols and security best practices required. Protect critical infrastructure for global enterprises.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹12-18 LPA',
            skills: '["Network Security", "Firewalls", "VPN", "Cisco", "Security Protocols", "Penetration Testing"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-29T15:00:00Z').toISOString(),
            createdAt: new Date('2024-11-27T11:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-27T23:59:59Z').toISOString(),
        },
        {
            postedById: 69,
            title: 'Manufacturing Engineer',
            company: 'Tata Motors',
            description: 'Looking for a Manufacturing Engineer to optimize production processes for automotive components. You will implement lean manufacturing principles, improve quality standards, reduce waste, and work on automation projects. Knowledge of Six Sigma and manufacturing processes essential. Contribute to making vehicles more efficient and reliable.',
            location: 'Pune',
            jobType: 'full-time',
            salary: '₹7-10 LPA',
            skills: '["Lean Manufacturing", "Six Sigma", "Process Optimization", "Quality Control", "Automation", "Production Planning"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-03T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-01T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-01T23:59:59Z').toISOString(),
        },
        {
            postedById: 72,
            title: 'UI/UX Designer',
            company: 'PhonePe',
            description: 'Join our design team to create intuitive user experiences for our digital payment platform. You will conduct user research, create wireframes and prototypes, design interfaces, and collaborate with product teams. Strong portfolio demonstrating mobile app design required. Design experiences that make payments simple for millions of Indians.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹12-18 LPA',
            skills: '["UI Design", "UX Design", "Figma", "User Research", "Prototyping", "Mobile Design", "Design Systems"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-02T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-30T13:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-30T23:59:59Z').toISOString(),
        },
        {
            postedById: 75,
            title: 'Python Backend Developer',
            company: 'Zoho',
            description: 'We are looking for a Python Backend Developer to build scalable APIs and microservices. You will design database schemas, implement business logic, optimize queries, and integrate third-party services. Strong knowledge of Django/Flask and PostgreSQL required. Work on products serving millions of businesses globally.',
            location: 'Chennai',
            jobType: 'full-time',
            salary: '₹8-14 LPA',
            skills: '["Python", "Django", "Flask", "PostgreSQL", "REST API", "Redis", "Microservices"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T10:30:00Z').toISOString(),
            createdAt: new Date('2024-12-02T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-02T23:59:59Z').toISOString(),
        },
        {
            postedById: 78,
            title: 'HVAC Design Engineer',
            company: 'Johnson Controls',
            description: 'Join our HVAC engineering team to design heating, ventilation, and air conditioning systems for commercial buildings. You will perform load calculations, select equipment, create detailed drawings, and ensure energy efficiency. Experience with HAP and AutoCAD MEP required. Design sustainable HVAC solutions for modern buildings.',
            location: 'Mumbai',
            jobType: 'full-time',
            salary: '₹6-9 LPA',
            skills: '["HVAC Design", "HAP", "AutoCAD MEP", "Load Calculations", "Energy Modeling", "MEP"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-25T11:00:00Z').toISOString(),
            createdAt: new Date('2024-11-23T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-23T23:59:59Z').toISOString(),
        },
        {
            postedById: 81,
            title: 'Cybersecurity Analyst',
            company: 'TCS',
            description: 'We are hiring a Cybersecurity Analyst to protect our clients\' digital assets. You will monitor security alerts, investigate incidents, implement security controls, and conduct risk assessments. Knowledge of SIEM tools and security frameworks required. Help organizations defend against evolving cyber threats.',
            location: 'Hyderabad',
            jobType: 'full-time',
            salary: '₹7-11 LPA',
            skills: '["Cybersecurity", "SIEM", "Incident Response", "Risk Assessment", "Security Frameworks", "Threat Analysis"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-28T14:30:00Z').toISOString(),
            createdAt: new Date('2024-11-26T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-26T23:59:59Z').toISOString(),
        },
        {
            postedById: 84,
            title: 'Power Electronics Engineer',
            company: 'ABB',
            description: 'Looking for a Power Electronics Engineer to work on industrial drive systems. You will design power conversion circuits, simulate designs, test prototypes, and optimize efficiency. Strong understanding of power semiconductors and control systems required. Contribute to energy-efficient industrial automation solutions.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹9-14 LPA',
            skills: '["Power Electronics", "Circuit Design", "MATLAB", "Simulink", "Control Systems", "IGBT"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-01T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-29T10:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-29T23:59:59Z').toISOString(),
        },
        {
            postedById: 87,
            title: 'Site Reliability Engineer',
            company: 'Netflix',
            description: 'Join our SRE team to ensure reliability and performance of our streaming platform. You will build monitoring systems, automate operations, troubleshoot production issues, and improve system resilience. Experience with distributed systems and cloud platforms essential. Help deliver seamless streaming to millions of viewers worldwide.',
            location: 'Remote',
            jobType: 'full-time',
            salary: '₹30-45 LPA',
            skills: '["SRE", "Kubernetes", "AWS", "Monitoring", "Automation", "Python", "Distributed Systems"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-05T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-03T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-02-03T23:59:59Z').toISOString(),
        },
        {
            postedById: 53,
            title: 'Blockchain Developer',
            company: 'Polygon',
            description: 'We are looking for a Blockchain Developer to build decentralized applications on our Layer 2 scaling solution. You will write smart contracts, develop DApps, integrate with Web3 libraries, and optimize gas costs. Strong knowledge of Solidity and Ethereum required. Shape the future of blockchain scalability.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹18-28 LPA',
            skills: '["Solidity", "Ethereum", "Web3", "Smart Contracts", "DApp Development", "Blockchain"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-27T15:30:00Z').toISOString(),
            createdAt: new Date('2024-11-25T14:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-25T23:59:59Z').toISOString(),
        },
        {
            postedById: 56,
            title: 'Quality Assurance Engineer - Civil',
            company: 'Larsen & Toubro',
            description: 'Join our QA team to ensure construction quality standards on infrastructure projects. You will conduct site inspections, review test reports, verify material quality, and ensure compliance with specifications. Knowledge of IS codes and construction practices required. Work on prestigious infrastructure projects across India.',
            location: 'Delhi NCR',
            jobType: 'full-time',
            salary: '₹5-8 LPA',
            skills: '["Quality Assurance", "Construction Quality", "Site Inspection", "IS Codes", "Material Testing"]',
            status: 'approved',
            branch: 'Civil Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T11:30:00Z').toISOString(),
            createdAt: new Date('2024-12-02T10:30:00Z').toISOString(),
            expiresAt: new Date('2025-02-02T23:59:59Z').toISOString(),
        },
        {
            postedById: 59,
            title: 'Machine Learning Engineer',
            company: 'Uber',
            description: 'We are hiring a Machine Learning Engineer to work on our pricing and demand forecasting systems. You will develop ML models, conduct experiments, deploy models to production, and monitor performance. Strong Python skills and experience with ML frameworks required. Impact millions of rides daily with your algorithms.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹22-32 LPA',
            skills: '["Machine Learning", "Python", "TensorFlow", "Scikit-learn", "MLOps", "A/B Testing", "Statistics"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-23T10:00:00Z').toISOString(),
            createdAt: new Date('2024-11-21T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-21T23:59:59Z').toISOString(),
        },
        {
            postedById: 62,
            title: 'CAD Design Engineer',
            company: 'Mahindra & Mahindra',
            description: 'Looking for a CAD Design Engineer to work on automotive component design. You will create 3D models, prepare manufacturing drawings, conduct tolerance analysis, and support prototype development. Proficiency in CATIA and GD&T required. Be part of designing next-generation automotive components.',
            location: 'Pune',
            jobType: 'full-time',
            salary: '₹6-9 LPA',
            skills: '["CATIA", "AutoCAD", "3D Modeling", "GD&T", "Tolerance Analysis", "Product Design"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-26T09:30:00Z').toISOString(),
            createdAt: new Date('2024-11-24T08:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-24T23:59:59Z').toISOString(),
        },
        {
            postedById: 65,
            title: 'RF Engineer',
            company: 'Qualcomm',
            description: 'Join our wireless communications team as an RF Engineer. You will design RF circuits, perform signal analysis, optimize antenna performance, and conduct electromagnetic simulations. Strong understanding of RF theory and experience with ADS/HFSS required. Work on cutting-edge 5G and wireless technologies.',
            location: 'Hyderabad',
            jobType: 'full-time',
            salary: '₹12-18 LPA',
            skills: '["RF Design", "Antenna Design", "ADS", "HFSS", "Signal Processing", "Wireless Communications"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-03T12:00:00Z').toISOString(),
            createdAt: new Date('2024-12-01T10:30:00Z').toISOString(),
            expiresAt: new Date('2025-02-01T23:59:59Z').toISOString(),
        },
        {
            postedById: 68,
            title: 'Infrastructure Engineer',
            company: 'Wipro',
            description: 'We are hiring an Infrastructure Engineer to manage IT infrastructure for enterprise clients. You will configure servers, maintain networks, implement backup solutions, and troubleshoot issues. Knowledge of Windows Server, Linux, and virtualization required. Support digital transformation for Fortune 500 companies.',
            location: 'Bangalore',
            jobType: 'full-time',
            salary: '₹6-10 LPA',
            skills: '["Linux", "Windows Server", "VMware", "Networking", "Backup Solutions", "Troubleshooting"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-29T11:00:00Z').toISOString(),
            createdAt: new Date('2024-11-27T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-27T23:59:59Z').toISOString(),
        },

        // INTERNSHIP POSITIONS (15 jobs)
        {
            postedById: 71,
            title: 'Software Engineering Intern - Summer 2025',
            company: 'Microsoft',
            description: 'Join our summer internship program to work on real-world projects in cloud computing and AI. You will collaborate with experienced engineers, write production code, and contribute to features used by millions. Looking for students passionate about technology with strong programming fundamentals. Mentorship and learning opportunities guaranteed.',
            location: 'Hyderabad',
            jobType: 'internship',
            salary: '₹25,000-35,000/month',
            skills: '["Java", "Python", "Data Structures", "Algorithms", "OOP"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-05T14:00:00Z').toISOString(),
            createdAt: new Date('2024-12-03T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-15T23:59:59Z').toISOString(),
        },
        {
            postedById: 74,
            title: 'Data Science Intern',
            company: 'Flipkart',
            description: 'Looking for a Data Science Intern to work on customer analytics and recommendation systems. You will analyze large datasets, build predictive models, and create visualizations. Strong Python and SQL skills required along with coursework in statistics or machine learning. Great opportunity to apply classroom learning to real problems.',
            location: 'Bangalore',
            jobType: 'internship',
            salary: '₹20,000-30,000/month',
            skills: '["Python", "SQL", "Pandas", "NumPy", "Machine Learning", "Statistics"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-02T11:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-20T23:59:59Z').toISOString(),
        },
        {
            postedById: 77,
            title: 'Frontend Development Intern',
            company: 'Razorpay',
            description: 'Join our frontend team for a 6-month internship building payment interfaces. You will work with React, implement responsive designs, and optimize performance. Basic knowledge of JavaScript and React required. Learn from experienced developers and build features impacting thousands of businesses. Pre-placement offer for outstanding performers.',
            location: 'Bangalore/Remote',
            jobType: 'internship',
            salary: '₹18,000-25,000/month',
            skills: '["React", "JavaScript", "HTML", "CSS", "Git"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-30T15:00:00Z').toISOString(),
            createdAt: new Date('2024-11-28T13:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-10T23:59:59Z').toISOString(),
        },
        {
            postedById: 80,
            title: 'Mechanical Design Intern',
            company: 'Hero MotoCorp',
            description: 'Looking for a Mechanical Design Intern to support our R&D team. You will assist in 3D modeling, create part drawings, participate in design reviews, and learn automotive design processes. Proficiency in SolidWorks required. Hands-on experience with motorcycle component design and exposure to manufacturing processes.',
            location: 'Delhi NCR',
            jobType: 'internship',
            salary: '₹15,000-20,000/month',
            skills: '["SolidWorks", "AutoCAD", "3D Modeling", "Drafting"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-27T12:00:00Z').toISOString(),
            createdAt: new Date('2024-11-25T11:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-05T23:59:59Z').toISOString(),
        },
        {
            postedById: 83,
            title: 'Civil Engineering Intern',
            company: 'Larsen & Toubro',
            description: 'Join our construction projects team as a Civil Engineering Intern. You will assist site engineers, learn construction practices, prepare daily progress reports, and understand project management. Interest in infrastructure development and willingness to work on site required. Excellent learning opportunity at India\'s largest construction company.',
            location: 'Mumbai',
            jobType: 'internship',
            salary: '₹12,000-18,000/month',
            skills: '["AutoCAD", "Construction Knowledge", "Site Surveying"]',
            status: 'approved',
            branch: 'Civil Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-02T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-30T11:30:00Z').toISOString(),
            expiresAt: new Date('2025-01-15T23:59:59Z').toISOString(),
        },
        {
            postedById: 86,
            title: 'Product Management Intern',
            company: 'Swiggy',
            description: 'Looking for a Product Management Intern to work with our restaurant-partner products team. You will conduct user research, analyze metrics, write product requirements, and support feature launches. Strong analytical skills and passion for product development required. Learn product management from ground up at a leading food-tech company.',
            location: 'Bangalore',
            jobType: 'internship',
            salary: '₹22,000-30,000/month',
            skills: '["Product Management", "User Research", "Data Analysis", "Excel", "Communication"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-03T09:30:00Z').toISOString(),
            createdAt: new Date('2024-12-01T08:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-25T23:59:59Z').toISOString(),
        },
        {
            postedById: 89,
            title: 'Electronics Design Intern',
            company: 'Samsung',
            description: 'Join our hardware team for a summer internship in consumer electronics design. You will work on circuit design, PCB layout, component selection, and testing. Basic knowledge of analog/digital electronics required. Exposure to cutting-edge consumer electronics development and mentorship from experienced engineers.',
            location: 'Noida',
            jobType: 'internship',
            salary: '₹20,000-28,000/month',
            skills: '["Circuit Design", "PCB Design", "Electronics", "Multisim"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-28T10:00:00Z').toISOString(),
            createdAt: new Date('2024-11-26T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-08T23:59:59Z').toISOString(),
        },
        {
            postedById: 54,
            title: 'Backend Development Intern',
            company: 'Zomato',
            description: 'We are hiring Backend Development Interns to work on our restaurant management APIs. You will build RESTful services, write database queries, implement business logic, and learn scalable architecture. Knowledge of Node.js or Python required. Work on systems handling millions of daily requests. Duration: 6 months.',
            location: 'Delhi NCR',
            jobType: 'internship',
            salary: '₹20,000-28,000/month',
            skills: '["Node.js", "Python", "REST API", "MongoDB", "SQL"]',
            status: 'approved',
            branch: 'Information Technology',
            approvedBy: 1,
            approvedAt: new Date('2024-12-01T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-29T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-18T23:59:59Z').toISOString(),
        },
        {
            postedById: 57,
            title: 'UI/UX Design Intern',
            company: 'CRED',
            description: 'Looking for a UI/UX Design Intern to work on our mobile app interfaces. You will create wireframes, design mockups, prototype interactions, and participate in user testing. Portfolio demonstrating design work required. Learn from award-winning designers and contribute to one of India\'s most beautifully designed apps.',
            location: 'Bangalore',
            jobType: 'internship',
            salary: '₹18,000-25,000/month',
            skills: '["Figma", "UI Design", "Prototyping", "Mobile Design"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-25T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-23T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-12T23:59:59Z').toISOString(),
        },
        {
            postedById: 60,
            title: 'DevOps Intern',
            company: 'PhonePe',
            description: 'Join our DevOps team for a hands-on internship in cloud infrastructure and automation. You will work with Docker, Kubernetes, CI/CD pipelines, and monitoring tools. Basic knowledge of Linux and scripting required. Learn DevOps practices at a company processing billions of transactions monthly. Duration: 6 months.',
            location: 'Bangalore',
            jobType: 'internship',
            salary: '₹22,000-32,000/month',
            skills: '["Linux", "Docker", "Git", "Shell Scripting", "AWS"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T15:00:00Z').toISOString(),
            createdAt: new Date('2024-12-02T14:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-22T23:59:59Z').toISOString(),
        },
        {
            postedById: 63,
            title: 'Quality Assurance Intern',
            company: 'Infosys',
            description: 'Looking for a QA Intern to test enterprise software applications. You will write test cases, perform manual testing, report bugs, and learn automation testing. Attention to detail and analytical mindset required. Training provided on industry-standard testing tools and methodologies. Duration: 5 months.',
            location: 'Pune',
            jobType: 'internship',
            salary: '₹15,000-22,000/month',
            skills: '["Manual Testing", "Test Cases", "Bug Reporting", "SQL"]',
            status: 'approved',
            branch: 'Information Technology',
            approvedBy: 1,
            approvedAt: new Date('2024-11-26T11:00:00Z').toISOString(),
            createdAt: new Date('2024-11-24T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-06T23:59:59Z').toISOString(),
        },
        {
            postedById: 66,
            title: 'Business Analyst Intern',
            company: 'Capgemini',
            description: 'Join our consulting team as a Business Analyst Intern. You will gather requirements, analyze data, create process flows, and support project teams. Strong Excel and presentation skills required. Exposure to enterprise clients and various industries. Learn business analysis in a consulting environment. Duration: 6 months.',
            location: 'Mumbai',
            jobType: 'internship',
            salary: '₹18,000-25,000/month',
            skills: '["Excel", "PowerPoint", "Business Analysis", "SQL", "Communication"]',
            status: 'approved',
            branch: 'Information Technology',
            approvedBy: 1,
            approvedAt: new Date('2024-12-05T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-03T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-28T23:59:59Z').toISOString(),
        },
        {
            postedById: 69,
            title: 'Machine Learning Intern',
            company: 'Freshworks',
            description: 'We are hiring ML Interns to work on AI-powered customer support features. You will build ML models, experiment with NLP techniques, and deploy models to production. Python and machine learning coursework required. Work on real-world AI applications with structured mentorship. Pre-placement offers for exceptional performers.',
            location: 'Chennai',
            jobType: 'internship',
            salary: '₹20,000-30,000/month',
            skills: '["Python", "Machine Learning", "NLP", "TensorFlow", "Scikit-learn"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-29T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-27T13:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-16T23:59:59Z').toISOString(),
        },
        {
            postedById: 72,
            title: 'Embedded Systems Intern',
            company: 'Texas Instruments',
            description: 'Looking for an Embedded Systems Intern to work on IoT and sensor applications. You will program microcontrollers, interface sensors, debug firmware, and learn embedded development best practices. Knowledge of C programming and basic electronics required. Hands-on experience with ARM-based systems. Duration: 6 months.',
            location: 'Bangalore',
            jobType: 'internship',
            salary: '₹18,000-26,000/month',
            skills: '["C Programming", "Microcontrollers", "Embedded Systems", "Arduino"]',
            status: 'approved',
            branch: 'Electronics Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-02T10:00:00Z').toISOString(),
            createdAt: new Date('2024-11-30T09:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-19T23:59:59Z').toISOString(),
        },
        {
            postedById: 75,
            title: 'Content Marketing Intern',
            company: 'Paytm',
            description: 'Join our marketing team as a Content Marketing Intern. You will create blog posts, social media content, email campaigns, and help with SEO. Strong writing skills and creativity required. Learn digital marketing at scale with India\'s leading fintech company. Opportunity to see your content reach millions of users. Duration: 4 months.',
            location: 'Noida/Remote',
            jobType: 'internship',
            salary: '₹15,000-22,000/month',
            skills: '["Content Writing", "Social Media", "SEO", "Digital Marketing", "Canva"]',
            status: 'pending',
            branch: 'Computer Engineering',
            approvedBy: null,
            approvedAt: null,
            createdAt: new Date('2024-12-05T15:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-30T23:59:59Z').toISOString(),
        },

        // PART-TIME POSITIONS (8 jobs)
        {
            postedById: 78,
            title: 'Freelance Full Stack Developer',
            company: 'TechStart Solutions',
            description: 'Looking for a freelance full stack developer for a 3-month project building a SaaS platform. You will work remotely, attend weekly meetings, and deliver features on milestone basis. Experience with MERN stack required. Flexible working hours. Payment on milestone completion. Potential for long-term engagement.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹40,000-60,000/month',
            skills: '["React", "Node.js", "MongoDB", "Express", "TypeScript"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-03T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-01T10:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-15T23:59:59Z').toISOString(),
        },
        {
            postedById: 81,
            title: 'Part-Time Data Analyst',
            company: 'DataInsights Consulting',
            description: 'Seeking a part-time data analyst to work 20 hours per week on client projects. You will analyze datasets, create dashboards, and present insights. Strong SQL and visualization skills required. Flexible schedule, work from home. Projects include retail analytics, customer segmentation, and performance tracking. Contract duration: 6 months.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹30,000-45,000/month',
            skills: '["SQL", "Python", "Tableau", "Excel", "Data Analysis"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-28T15:00:00Z').toISOString(),
            createdAt: new Date('2024-11-26T14:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-10T23:59:59Z').toISOString(),
        },
        {
            postedById: 84,
            title: 'Freelance Mobile App Developer',
            company: 'AppVentures',
            description: 'Looking for a freelance mobile app developer to build iOS and Android apps. You will work on design implementation, API integration, and app store deployment. React Native or Flutter experience required. Project-based engagement with flexible hours. Portfolio of published apps preferred. Multiple projects available.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹50,000-80,000/month',
            skills: '["React Native", "Flutter", "Mobile Development", "API Integration"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-04T13:00:00Z').toISOString(),
            createdAt: new Date('2024-12-02T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-20T23:59:59Z').toISOString(),
        },
        {
            postedById: 87,
            title: 'Part-Time UI/UX Designer',
            company: 'DesignStudio Pro',
            description: 'Seeking a part-time UI/UX designer for ongoing client projects. You will create wireframes, design interfaces, conduct user research, and deliver design systems. 15-20 hours per week commitment. Experience with Figma required. Work with startups and established companies. Competitive rates and flexible schedule.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹35,000-50,000/month',
            skills: '["Figma", "UI Design", "UX Design", "Prototyping", "User Research"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-30T12:00:00Z').toISOString(),
            createdAt: new Date('2024-11-28T11:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-12T23:59:59Z').toISOString(),
        },
        {
            postedById: 90,
            title: 'Freelance Technical Writer',
            company: 'TechDocs Agency',
            description: 'Looking for a freelance technical writer to create documentation for software products. You will write API docs, user guides, tutorials, and technical blogs. Strong technical background and excellent writing skills required. Flexible hours, remote work. Payment per project. Experience with developer documentation preferred.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹25,000-40,000/month',
            skills: '["Technical Writing", "Documentation", "Markdown", "API Documentation", "Git"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-01T15:00:00Z').toISOString(),
            createdAt: new Date('2024-11-29T14:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-17T23:59:59Z').toISOString(),
        },
        {
            postedById: 56,
            title: 'Part-Time CAD Designer',
            company: 'MechDesign Consultancy',
            description: 'Seeking a part-time CAD designer for mechanical component design projects. You will create 3D models, prepare manufacturing drawings, and perform basic simulations. Work 15-20 hours per week remotely. SolidWorks proficiency required. Projects include product design, jigs and fixtures, and machine components. Flexible schedule.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹20,000-35,000/month',
            skills: '["SolidWorks", "AutoCAD", "3D Modeling", "Technical Drawing"]',
            status: 'approved',
            branch: 'Mechanical Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-11-27T13:00:00Z').toISOString(),
            createdAt: new Date('2024-11-25T12:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-08T23:59:59Z').toISOString(),
        },
        {
            postedById: 59,
            title: 'Freelance Python Developer',
            company: 'CodeCraft Solutions',
            description: 'Looking for a freelance Python developer for automation and web scraping projects. You will build scripts, automate workflows, develop APIs, and integrate systems. Work on diverse projects with flexible hours. Experience with Django/Flask and web scraping libraries required. Payment on project completion. Multiple projects available.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹35,000-55,000/month',
            skills: '["Python", "Django", "Flask", "Web Scraping", "REST API", "Automation"]',
            status: 'approved',
            branch: 'Computer Engineering',
            approvedBy: 1,
            approvedAt: new Date('2024-12-02T14:00:00Z').toISOString(),
            createdAt: new Date('2024-11-30T13:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-25T23:59:59Z').toISOString(),
        },
        {
            postedById: 62,
            title: 'Part-Time Digital Marketing Specialist',
            company: 'GrowthHack Marketing',
            description: 'Seeking a part-time digital marketing specialist to manage campaigns for small businesses. You will handle social media, run ads, create content, and track analytics. 20 hours per week commitment. Experience with Google Ads and Facebook Ads required. Work remotely with flexible schedule. Performance bonuses available.',
            location: 'Remote',
            jobType: 'part-time',
            salary: '₹25,000-40,000/month',
            skills: '["Digital Marketing", "Social Media Marketing", "Google Ads", "Facebook Ads", "SEO", "Analytics"]',
            status: 'pending',
            branch: 'Computer Engineering',
            approvedBy: null,
            approvedAt: null,
            createdAt: new Date('2024-12-04T16:00:00Z').toISOString(),
            expiresAt: new Date('2025-01-28T23:59:59Z').toISOString(),
        },
    ];

    await db.insert(jobs).values(sampleJobs);
    
    console.log('✅ Jobs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});