import { db } from '@/db';
import { mentorshipRequests } from '@/db/schema';

async function main() {
    const sampleMentorshipRequests = [
        // PENDING REQUESTS (Recent, last 2 weeks)
        {
            studentId: 2,
            mentorId: 52,
            topic: 'Career path in software engineering',
            message: 'Hello! I\'m a third-year CS student passionate about software development. I\'ve built several full-stack projects and am now preparing for placements. I would really appreciate your guidance on career opportunities in software engineering and how to prepare for technical interviews at top companies. Your experience at Microsoft would be invaluable to me.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'pending',
            createdAt: new Date('2024-12-20').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 5,
            mentorId: 95,
            topic: 'Guidance on Masters abroad',
            message: 'Hi Professor! I\'m a final year student interested in pursuing a Masters in Computer Science abroad. I have a good academic record and some research experience. I would love your guidance on choosing universities, specializations, and the application process. Your insights on research opportunities would be extremely helpful.',
            preferredTime: null,
            status: 'pending',
            createdAt: new Date('2024-12-22').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 8,
            mentorId: 58,
            topic: 'Machine learning project guidance',
            message: 'Hello! I\'m working on my final year project in machine learning and computer vision. I\'ve completed Andrew Ng\'s course and built a few projects. I would appreciate your guidance on best practices, choosing the right algorithms, and deploying ML models. Your experience at Google AI would be incredibly valuable.',
            preferredTime: 'Weekend mornings',
            status: 'pending',
            createdAt: new Date('2024-12-18').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 12,
            mentorId: 65,
            topic: 'DevOps and cloud computing career',
            message: 'Hi! I\'m a third-year student interested in DevOps and cloud technologies. I\'ve learned Docker, Kubernetes basics and AWS fundamentals. I would love your guidance on career opportunities in DevOps, certifications worth pursuing, and how to build practical experience. Your journey to becoming a DevOps engineer would inspire me.',
            preferredTime: 'Flexible on weekdays',
            status: 'pending',
            createdAt: new Date('2024-12-23').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 15,
            mentorId: 70,
            topic: 'Best practices for React development',
            message: 'Hello! I\'m learning React and modern frontend development. I\'ve built a few projects but want to learn industry best practices, state management patterns, and performance optimization. I would appreciate your guidance on becoming a strong frontend developer. Your experience at Meta would be extremely helpful.',
            preferredTime: null,
            status: 'pending',
            createdAt: new Date('2024-12-21').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 18,
            mentorId: 92,
            topic: 'PhD research opportunities',
            message: 'Hi Professor! I\'m a final year student with a strong interest in research. I have published one paper and worked on several research projects. I would love your guidance on pursuing a PhD, choosing research areas, and preparing competitive applications. Your experience in academia would be invaluable.',
            preferredTime: 'Any time convenient for you',
            status: 'pending',
            createdAt: new Date('2024-12-19').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 22,
            mentorId: 75,
            topic: 'Transitioning from college to corporate',
            message: 'Hello! I\'m in my final year and have an offer from a tech company. I would appreciate your guidance on transitioning from college to corporate life, what to expect in the first few months, and how to make a strong start. Your experience would really help me prepare mentally and professionally.',
            preferredTime: 'Saturday afternoon',
            status: 'pending',
            createdAt: new Date('2024-12-24').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 25,
            mentorId: 80,
            topic: 'System design for scalable applications',
            message: 'Hi! I\'m preparing for senior engineer roles and need guidance on system design. I understand basics but struggle with designing scalable systems and making trade-offs. I would love your mentorship on system design patterns, distributed systems, and interview preparation. Your experience at Amazon would be perfect for this.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'pending',
            createdAt: new Date('2024-12-25').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 28,
            mentorId: 85,
            topic: 'How to prepare for product management roles',
            message: 'Hello! I\'m a third-year student interested in transitioning to product management. I have strong technical skills and leadership experience. I would appreciate your guidance on building product sense, understanding user needs, and preparing for PM interviews. Your journey from engineering to product management would inspire me.',
            preferredTime: null,
            status: 'pending',
            createdAt: new Date('2024-12-26').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 31,
            mentorId: 98,
            topic: 'Building strong DSA fundamentals',
            message: 'Hi Professor! I\'m struggling with data structures and algorithms despite practicing regularly. I would love your guidance on building strong fundamentals, approaching problems systematically, and improving problem-solving skills. Your teaching experience would be extremely helpful in identifying my weak areas.',
            preferredTime: 'Weekend mornings',
            status: 'pending',
            createdAt: new Date('2024-12-27').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 34,
            mentorId: 53,
            topic: 'Getting started with open source',
            message: 'Hello! I want to contribute to open source projects to build my profile and learn from real-world codebases. I have good programming skills but don\'t know where to start. I would appreciate your guidance on finding beginner-friendly projects, making meaningful contributions, and building a strong GitHub profile.',
            preferredTime: 'Flexible on weekdays',
            status: 'pending',
            createdAt: new Date('2024-12-28').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 37,
            mentorId: 62,
            topic: 'Choosing between startups and big companies',
            message: 'Hi! I have offers from both a startup and a large tech company for my first job. I\'m confused about which path to choose. I would love your perspective on the pros and cons of each, career growth opportunities, and what might suit someone early in their career. Your diverse experience would really help.',
            preferredTime: null,
            status: 'pending',
            createdAt: new Date('2024-12-29').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 40,
            mentorId: 68,
            topic: 'Learning full-stack development roadmap',
            message: 'Hello! I want to become a full-stack developer but feel overwhelmed by the number of technologies. I know basics of frontend and backend. I would appreciate your guidance on creating a learning roadmap, which technologies to focus on, and how to build projects that demonstrate full-stack skills effectively.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'pending',
            createdAt: new Date('2024-12-30').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 43,
            mentorId: 103,
            topic: 'Research methodology and paper writing',
            message: 'Hi Professor! I\'m working on my research project and struggling with methodology and writing. I have interesting findings but need guidance on structuring my paper, conducting rigorous analysis, and presenting results effectively. Your experience in academic research would be invaluable for my growth.',
            preferredTime: 'Saturday afternoon',
            status: 'pending',
            createdAt: new Date('2024-12-31').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 46,
            mentorId: 78,
            topic: 'Technical interview preparation for FAANG',
            message: 'Hello! I\'m preparing for FAANG interviews and would really appreciate guidance on technical interview preparation. I\'ve been practicing DSA but want to learn from someone who has been through the process. Could we discuss preparation strategies, common patterns, and how to handle system design rounds effectively?',
            preferredTime: 'Any time convenient for you',
            status: 'pending',
            createdAt: new Date('2025-01-01').toISOString(),
            respondedAt: null,
        },
        {
            studentId: 49,
            mentorId: 88,
            topic: 'Building a career in data science',
            message: 'Hi! I\'m interested in data science and have completed several online courses. I would love your guidance on building practical experience, working on real-world projects, and understanding what companies look for in data scientists. Your transition from academia to industry in data science would be very inspiring.',
            preferredTime: 'Weekend mornings',
            status: 'pending',
            createdAt: new Date('2025-01-02').toISOString(),
            respondedAt: null,
        },

        // ACCEPTED REQUESTS (Mentor agreed to help)
        {
            studentId: 3,
            mentorId: 55,
            topic: 'Resume and LinkedIn optimization',
            message: 'Hello! I\'m updating my resume and LinkedIn for placement season. I would appreciate your guidance on highlighting projects effectively, writing impactful descriptions, and optimizing my LinkedIn profile. Your experience in recruiting and your strong profile would be extremely helpful.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-11-20').toISOString(),
            respondedAt: new Date('2024-11-22').toISOString(),
        },
        {
            studentId: 4,
            mentorId: 60,
            topic: 'Behavioral interview strategies',
            message: 'Hi! I\'m preparing for interviews and need help with behavioral questions. I struggle with structuring my answers and showcasing leadership experiences. I would love your guidance on STAR method, common questions, and how to present myself confidently. Your interview experience would be invaluable.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-11-15').toISOString(),
            respondedAt: new Date('2024-11-18').toISOString(),
        },
        {
            studentId: 6,
            mentorId: 54,
            topic: 'Career guidance in software development',
            message: 'Hello! I\'m a second-year student trying to figure out my career path. I enjoy coding but am unsure about specializations. I would appreciate your guidance on different career paths in software development, skills to focus on, and how to gain relevant experience early. Your journey would really help me.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-11-25').toISOString(),
            respondedAt: new Date('2024-11-27').toISOString(),
        },
        {
            studentId: 7,
            mentorId: 57,
            topic: 'Mobile app development career',
            message: 'Hi! I\'m interested in mobile app development and have learned React Native basics. I would love your guidance on career opportunities in mobile development, choosing between native and cross-platform, and building a strong portfolio. Your experience at Uber would be perfect for understanding industry needs.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-12-01').toISOString(),
            respondedAt: new Date('2024-12-03').toISOString(),
        },
        {
            studentId: 9,
            mentorId: 63,
            topic: 'Backend development and API design',
            message: 'Hello! I\'m focusing on backend development and want to learn industry best practices. I know Node.js and Express basics but want to understand scalable architecture, API design patterns, and database optimization. Your experience at Netflix with distributed systems would be incredibly valuable.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-11-28').toISOString(),
            respondedAt: new Date('2024-12-01').toISOString(),
        },
        {
            studentId: 10,
            mentorId: 94,
            topic: 'Choosing universities and specializations',
            message: 'Hi Professor! I\'m planning to apply for Masters and need guidance on choosing universities and specializations. I\'m interested in AI/ML but also considering other areas. Your experience in academia and research would help me make an informed decision about my graduate studies.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-12-05').toISOString(),
            respondedAt: new Date('2024-12-07').toISOString(),
        },
        {
            studentId: 11,
            mentorId: 67,
            topic: 'Cloud architecture and AWS certification',
            message: 'Hello! I want to build a career in cloud computing and am preparing for AWS certifications. I would appreciate your guidance on the certification path, hands-on practice strategies, and understanding cloud architecture patterns. Your experience as a cloud architect would be extremely helpful.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-11-18').toISOString(),
            respondedAt: new Date('2024-11-20').toISOString(),
        },
        {
            studentId: 13,
            mentorId: 72,
            topic: 'Frontend performance optimization',
            message: 'Hi! I\'m working on complex frontend applications and want to learn performance optimization techniques. I understand React well but need guidance on code splitting, lazy loading, and optimizing bundle size. Your work on performance-critical applications would be perfect for this mentorship.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-12-08').toISOString(),
            respondedAt: new Date('2024-12-10').toISOString(),
        },
        {
            studentId: 14,
            mentorId: 76,
            topic: 'Cybersecurity career path',
            message: 'Hello! I\'m fascinated by cybersecurity and ethical hacking. I\'ve done some CTF challenges but want to understand career opportunities in security. I would love your guidance on building security skills, certifications, and getting into security roles. Your experience in security engineering would be invaluable.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-11-22').toISOString(),
            respondedAt: new Date('2024-11-25').toISOString(),
        },
        {
            studentId: 16,
            mentorId: 82,
            topic: 'Data engineering and ETL pipelines',
            message: 'Hi! I\'m interested in data engineering and want to learn about building data pipelines, ETL processes, and working with big data technologies. I have programming skills but need guidance on data engineering tools and best practices. Your experience at Airbnb would be extremely helpful.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-12-02').toISOString(),
            respondedAt: new Date('2024-12-06').toISOString(),
        },
        {
            studentId: 17,
            mentorId: 96,
            topic: 'Academic research and publications',
            message: 'Hi Professor! I\'m interested in research and want to publish papers. I have some project ideas but need guidance on conducting research, writing papers, and getting published. Your extensive publication record would help me understand the academic research process better.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-11-30').toISOString(),
            respondedAt: new Date('2024-12-02').toISOString(),
        },
        {
            studentId: 19,
            mentorId: 56,
            topic: 'Building SaaS products',
            message: 'Hello! I want to build and launch my own SaaS product. I have technical skills but need guidance on product development, market validation, and monetization strategies. Your experience building products from scratch would be incredibly valuable for my entrepreneurial journey.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-12-12').toISOString(),
            respondedAt: new Date('2024-12-15').toISOString(),
        },
        {
            studentId: 20,
            mentorId: 61,
            topic: 'Game development career',
            message: 'Hi! I\'m passionate about game development and have made some small games. I would love your guidance on career opportunities in gaming, choosing between indie and AAA studios, and building a strong portfolio. Your experience in the gaming industry would be perfect for understanding this field.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-11-12').toISOString(),
            respondedAt: new Date('2024-11-14').toISOString(),
        },
        {
            studentId: 21,
            mentorId: 66,
            topic: 'Microservices architecture',
            message: 'Hello! I want to learn about microservices architecture and distributed systems. I understand monolithic applications but need guidance on breaking down services, inter-service communication, and deployment strategies. Your experience at Netflix would be extremely helpful for understanding large-scale systems.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-12-06').toISOString(),
            respondedAt: new Date('2024-12-09').toISOString(),
        },
        {
            studentId: 23,
            mentorId: 71,
            topic: 'UI/UX design for developers',
            message: 'Hi! I\'m a developer who wants to improve design skills. I can build features but struggle with creating intuitive and beautiful interfaces. I would appreciate your guidance on design principles, user experience, and tools. Your work on user-facing products would help me become a better full-stack developer.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-11-20').toISOString(),
            respondedAt: new Date('2024-11-23').toISOString(),
        },
        {
            studentId: 24,
            mentorId: 99,
            topic: 'Teaching and academic career',
            message: 'Hi Professor! I\'m considering an academic career and teaching. I enjoy helping others learn and have tutored many students. I would love your guidance on pursuing a teaching career, PhD opportunities, and balancing research with teaching. Your experience in academia would be invaluable.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-12-14').toISOString(),
            respondedAt: new Date('2024-12-16').toISOString(),
        },
        {
            studentId: 26,
            mentorId: 73,
            topic: 'Blockchain and Web3 development',
            message: 'Hello! I\'m interested in blockchain technology and Web3. I understand basics but want to learn smart contract development, DeFi protocols, and career opportunities in this space. Your experience in blockchain would help me understand practical applications and career paths in Web3.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-11-26').toISOString(),
            respondedAt: new Date('2024-11-28').toISOString(),
        },
        {
            studentId: 27,
            mentorId: 79,
            topic: 'Technical leadership and team management',
            message: 'Hi! I\'m leading a technical team for my college project and finding it challenging. I would appreciate your guidance on technical leadership, managing team dynamics, code reviews, and decision making. Your experience as an engineering manager would be extremely helpful.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-12-10').toISOString(),
            respondedAt: new Date('2024-12-13').toISOString(),
        },
        {
            studentId: 29,
            mentorId: 84,
            topic: 'Career transition to product management',
            message: 'Hello! I\'m a developer interested in product management. I have good technical skills and user empathy. I would love your guidance on transitioning from engineering to PM, building product sense, and preparing for PM roles. Your journey from tech to product would really inspire me.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-11-24').toISOString(),
            respondedAt: new Date('2024-11-27').toISOString(),
        },
        {
            studentId: 30,
            mentorId: 89,
            topic: 'AI/ML engineering career',
            message: 'Hi! I\'m passionate about AI and machine learning. I\'ve taken courses and built projects but want guidance on career opportunities, specializations, and building production ML systems. Your experience in AI engineering would help me understand what it takes to succeed in this field.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-12-04').toISOString(),
            respondedAt: new Date('2024-12-07').toISOString(),
        },
        {
            studentId: 32,
            mentorId: 59,
            topic: 'Competitive programming and contests',
            message: 'Hello! I want to improve my competitive programming skills and perform better in contests. I can solve easy problems but struggle with medium ones. I would appreciate your guidance on practice strategies, problem-solving techniques, and preparing for contests like ACM ICPC.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-11-16').toISOString(),
            respondedAt: new Date('2024-11-19').toISOString(),
        },
        {
            studentId: 33,
            mentorId: 64,
            topic: 'Site reliability engineering',
            message: 'Hi! I\'m interested in SRE and want to learn about maintaining reliable systems at scale. I have development experience but need guidance on monitoring, incident management, and SRE practices. Your experience in SRE at Google would be extremely valuable for understanding this role.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-12-16').toISOString(),
            respondedAt: new Date('2024-12-18').toISOString(),
        },
        {
            studentId: 35,
            mentorId: 69,
            topic: 'Mobile testing and quality assurance',
            message: 'Hello! I want to build a career in quality assurance and testing. I understand manual testing basics but want to learn automation, CI/CD, and testing best practices. Your experience in QA at top companies would help me understand modern testing approaches and career growth in this field.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-11-28').toISOString(),
            respondedAt: new Date('2024-12-01').toISOString(),
        },
        {
            studentId: 36,
            mentorId: 74,
            topic: 'Database design and optimization',
            message: 'Hi! I want to become proficient in database design and optimization. I know SQL basics but need guidance on schema design, indexing strategies, and query optimization. Your experience with large-scale databases would be extremely helpful for understanding database engineering.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-12-08').toISOString(),
            respondedAt: new Date('2024-12-11').toISOString(),
        },
        {
            studentId: 38,
            mentorId: 81,
            topic: 'Technical writing and documentation',
            message: 'Hello! I want to improve my technical writing skills for documentation and blog posts. I can write code but struggle with explaining concepts clearly. I would appreciate your guidance on technical writing, creating documentation, and sharing knowledge effectively.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-11-14').toISOString(),
            respondedAt: new Date('2024-11-17').toISOString(),
        },
        {
            studentId: 39,
            mentorId: 100,
            topic: 'Research paper review and improvement',
            message: 'Hi Professor! I\'ve written a draft of my research paper but need help improving it. I would appreciate your feedback on structure, writing quality, and technical content. Your experience reviewing papers would help me understand what makes a strong publication.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-12-12').toISOString(),
            respondedAt: new Date('2024-12-14').toISOString(),
        },
        {
            studentId: 41,
            mentorId: 77,
            topic: 'IoT and embedded systems',
            message: 'Hello! I\'m interested in IoT and embedded systems. I have basic electronics knowledge but want to learn about IoT platforms, sensor integration, and building connected devices. Your experience in IoT would help me understand career opportunities in this emerging field.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-11-22').toISOString(),
            respondedAt: new Date('2024-11-25').toISOString(),
        },
        {
            studentId: 42,
            mentorId: 83,
            topic: 'Business intelligence and analytics',
            message: 'Hi! I want to build a career in business intelligence and analytics. I have programming skills and understand basic statistics. I would love your guidance on BI tools, data visualization, and understanding business metrics. Your experience in analytics would be extremely valuable.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-12-02').toISOString(),
            respondedAt: new Date('2024-12-05').toISOString(),
        },
        {
            studentId: 44,
            mentorId: 86,
            topic: 'Agile methodologies and scrum',
            message: 'Hello! I want to understand agile development and scrum practices. I\'ve worked on waterfall projects but need to learn modern development methodologies. I would appreciate your guidance on agile practices, sprint planning, and team collaboration in agile environments.',
            preferredTime: 'Weekend mornings',
            status: 'accepted',
            createdAt: new Date('2024-11-18').toISOString(),
            respondedAt: new Date('2024-11-21').toISOString(),
        },
        {
            studentId: 45,
            mentorId: 91,
            topic: 'Natural language processing',
            message: 'Hi! I\'m fascinated by NLP and want to build a career in this field. I\'ve done basic NLP projects but want to learn about transformers, LLMs, and production NLP systems. Your research in NLP would help me understand both research and industry applications.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'accepted',
            createdAt: new Date('2024-12-10').toISOString(),
            respondedAt: new Date('2024-12-13').toISOString(),
        },
        {
            studentId: 47,
            mentorId: 87,
            topic: 'Computer vision applications',
            message: 'Hello! I\'m working on computer vision projects and want to learn about real-world applications. I understand CNNs but need guidance on object detection, image segmentation, and deploying CV models. Your experience in computer vision would be incredibly valuable.',
            preferredTime: null,
            status: 'accepted',
            createdAt: new Date('2024-11-26').toISOString(),
            respondedAt: new Date('2024-11-29').toISOString(),
        },
        {
            studentId: 48,
            mentorId: 104,
            topic: 'Laboratory techniques and experimentation',
            message: 'Hi Professor! I\'m working on experimental research and need guidance on laboratory techniques, experimental design, and data collection. I would appreciate your mentorship on conducting rigorous experiments and analyzing results. Your lab experience would be extremely helpful.',
            preferredTime: 'Saturday afternoon',
            status: 'accepted',
            createdAt: new Date('2024-12-06').toISOString(),
            respondedAt: new Date('2024-12-09').toISOString(),
        },
        {
            studentId: 50,
            mentorId: 90,
            topic: 'Quantum computing fundamentals',
            message: 'Hello! I\'m intrigued by quantum computing and want to learn about quantum algorithms and applications. I have strong math background but need guidance on getting started with quantum computing. Your research in quantum computing would help me understand this emerging field.',
            preferredTime: 'Flexible on weekdays',
            status: 'accepted',
            createdAt: new Date('2024-11-20').toISOString(),
            respondedAt: new Date('2024-11-23').toISOString(),
        },

        // REJECTED REQUESTS (Mentor couldn't commit)
        {
            studentId: 2,
            mentorId: 65,
            topic: 'Cloud computing career guidance',
            message: 'Hello! I\'m interested in learning about cloud computing and would appreciate your guidance on getting started with cloud platforms and certifications. Your experience in cloud architecture would be really helpful for my career planning.',
            preferredTime: 'Weekend mornings',
            status: 'rejected',
            createdAt: new Date('2024-10-15').toISOString(),
            respondedAt: new Date('2024-10-20').toISOString(),
        },
        {
            studentId: 7,
            mentorId: 82,
            topic: 'Data pipeline development',
            message: 'Hi! I want to learn about building data pipelines and ETL processes. I would love your mentorship on data engineering best practices and tools. Your work at Airbnb on data infrastructure would be extremely valuable.',
            preferredTime: null,
            status: 'rejected',
            createdAt: new Date('2024-10-25').toISOString(),
            respondedAt: new Date('2024-10-30').toISOString(),
        },
        {
            studentId: 14,
            mentorId: 58,
            topic: 'AI research opportunities',
            message: 'Hello! I\'m interested in AI research and want to understand research opportunities in machine learning. I would appreciate your guidance on research methodology and career paths in AI research. Your experience at Google AI would be perfect.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'rejected',
            createdAt: new Date('2024-11-05').toISOString(),
            respondedAt: new Date('2024-11-10').toISOString(),
        },
        {
            studentId: 19,
            mentorId: 72,
            topic: 'Frontend architecture patterns',
            message: 'Hi! I want to learn about frontend architecture for large applications. I would love your guidance on state management, component design, and scalability. Your work on frontend systems would be incredibly helpful.',
            preferredTime: 'Saturday afternoon',
            status: 'rejected',
            createdAt: new Date('2024-11-08').toISOString(),
            respondedAt: new Date('2024-11-13').toISOString(),
        },
        {
            studentId: 28,
            mentorId: 56,
            topic: 'Startup founding and entrepreneurship',
            message: 'Hello! I want to start my own tech startup and would appreciate your guidance on founding a company, raising funding, and building products. Your entrepreneurial experience would be extremely valuable for my journey.',
            preferredTime: 'Flexible on weekdays',
            status: 'rejected',
            createdAt: new Date('2024-11-12').toISOString(),
            respondedAt: new Date('2024-11-18').toISOString(),
        },
        {
            studentId: 35,
            mentorId: 88,
            topic: 'Data science project mentorship',
            message: 'Hi! I\'m working on a data science project and need guidance on feature engineering, model selection, and evaluation. I would appreciate your mentorship on building end-to-end data science solutions.',
            preferredTime: 'Weekend mornings',
            status: 'rejected',
            createdAt: new Date('2024-10-28').toISOString(),
            respondedAt: new Date('2024-11-02').toISOString(),
        },

        // COMPLETED REQUESTS (Mentorship sessions concluded)
        {
            studentId: 4,
            mentorId: 52,
            topic: 'Technical interview preparation',
            message: 'Hello! I\'m preparing for technical interviews at top companies. I would really appreciate your guidance on DSA preparation, problem-solving approaches, and interview strategies. Your journey to Microsoft would be incredibly inspiring.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'completed',
            createdAt: new Date('2024-09-15').toISOString(),
            respondedAt: new Date('2024-09-18').toISOString(),
        },
        {
            studentId: 11,
            mentorId: 60,
            topic: 'Software engineering best practices',
            message: 'Hi! I want to learn industry best practices for software development including clean code, testing, and code reviews. Your experience at Amazon would help me understand professional software engineering standards.',
            preferredTime: 'Saturday afternoon',
            status: 'completed',
            createdAt: new Date('2024-09-20').toISOString(),
            respondedAt: new Date('2024-09-23').toISOString(),
        },
        {
            studentId: 16,
            mentorId: 97,
            topic: 'Research project guidance',
            message: 'Hi Professor! I\'m working on my undergraduate research project and need guidance on research methodology, literature review, and presenting findings. Your research experience would be extremely helpful.',
            preferredTime: null,
            status: 'completed',
            createdAt: new Date('2024-08-10').toISOString(),
            respondedAt: new Date('2024-08-13').toISOString(),
        },
        {
            studentId: 23,
            mentorId: 70,
            topic: 'React and modern frontend development',
            message: 'Hello! I\'m learning React and want to understand modern frontend development practices. I would love your guidance on hooks, state management, and building scalable applications. Your experience at Meta would be perfect.',
            preferredTime: 'Flexible on weekdays',
            status: 'completed',
            createdAt: new Date('2024-10-01').toISOString(),
            respondedAt: new Date('2024-10-04').toISOString(),
        },
        {
            studentId: 31,
            mentorId: 75,
            topic: 'Career transition and job search',
            message: 'Hi! I\'m starting my job search and would appreciate guidance on the hiring process, negotiations, and making good career decisions. Your experience would help me navigate my first job search effectively.',
            preferredTime: 'Weekend mornings',
            status: 'completed',
            createdAt: new Date('2024-09-05').toISOString(),
            respondedAt: new Date('2024-09-08').toISOString(),
        },
        {
            studentId: 38,
            mentorId: 101,
            topic: 'Academic career and PhD preparation',
            message: 'Hi Professor! I\'m considering a PhD and academic career. I would love your guidance on choosing research topics, applying to programs, and understanding academic life. Your experience would be invaluable.',
            preferredTime: 'Weekday evenings after 6 PM',
            status: 'completed',
            createdAt: new Date('2024-08-25').toISOString(),
            respondedAt: new Date('2024-08-28').toISOString(),
        },
    ];

    await db.insert(mentorshipRequests).values(sampleMentorshipRequests);
    
    console.log('✅ Mentorship requests seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});