import { db } from '@/db';
import { posts } from '@/db/schema';

async function main() {
    const samplePosts = [
        // Student posts - asking questions, sharing progress
        {
            authorId: 11,
            content: 'Just started learning React Hooks! Anyone have good resources for understanding useEffect dependency arrays? Finding it a bit confusing with the cleanup function. #ReactJS #WebDev',
            category: 'question',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-15T10:00:00Z').toISOString(),
            createdAt: new Date('2024-02-15T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-15T09:30:00Z').toISOString(),
        },
        {
            authorId: 50,
            content: '🎉 Excited to share that I\'ve been selected for a Google Summer internship! The interview process was challenging but worth it. Happy to share my experience and tips with anyone preparing for tech interviews. #GoogleInternship #TechCareer',
            imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800',
            category: 'achievement',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-16T11:00:00Z').toISOString(),
            createdAt: new Date('2024-02-16T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-16T10:30:00Z').toISOString(),
        },
        {
            authorId: 25,
            content: 'Working on my final year project - A Machine Learning model for disease prediction using medical imaging. The dataset preprocessing is taking longer than expected. Any tips on handling imbalanced datasets? #MachineLearning #Healthcare',
            category: 'project',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-17T14:00:00Z').toISOString(),
            createdAt: new Date('2024-02-17T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-17T13:30:00Z').toISOString(),
        },
        {
            authorId: 34,
            content: 'Looking for project teammates! Building a mobile app for campus event management. Need someone good with Flutter and Firebase. DM me if interested! 📱 #ProjectCollab #Flutter',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-18T09:00:00Z').toISOString(),
            createdAt: new Date('2024-02-18T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-18T08:30:00Z').toISOString(),
        },
        {
            authorId: 47,
            content: 'Question about REST API authentication - Should I use JWT tokens or session-based auth for a Node.js backend? What are the pros and cons of each approach? Building an e-commerce API. #WebDevelopment #API',
            category: 'question',
            branch: 'Information Technology',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-19T15:00:00Z').toISOString(),
            createdAt: new Date('2024-02-19T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-19T14:30:00Z').toISOString(),
        },
        {
            authorId: 12,
            content: 'Our college team won first place at Smart India Hackathon! 36 hours of non-stop coding paid off. Built an AI-powered traffic management system. Huge thanks to my amazing teammates! 🏆 #Hackathon #TeamWork #AI',
            imageUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-21T10:00:00Z').toISOString(),
            createdAt: new Date('2024-02-21T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-21T09:30:00Z').toISOString(),
        },
        {
            authorId: 23,
            content: 'Attending Web3 conference next week! First time exploring blockchain and decentralized applications. Any topics I should focus on? #Blockchain #Web3 #Learning',
            category: 'discussion',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-22T12:00:00Z').toISOString(),
            createdAt: new Date('2024-02-22T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-22T11:30:00Z').toISOString(),
        },
        {
            authorId: 48,
            content: 'Struggling with Dynamic Programming problems! Spent hours on the longest common subsequence. Anyone else find DP challenging? Looking for good resources to understand the patterns better. #DSA #CompetitiveProgramming',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-23T16:00:00Z').toISOString(),
            createdAt: new Date('2024-02-23T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-23T15:30:00Z').toISOString(),
        },
        {
            authorId: 21,
            content: 'Just completed my internship at TCS! Learned so much about enterprise software development and agile methodologies. Ready to apply this knowledge in my final year. #Internship #Learning #SoftwareEngineering',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-25T10:00:00Z').toISOString(),
            createdAt: new Date('2024-02-25T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-25T09:30:00Z').toISOString(),
        },

        // Alumni posts - sharing experiences, offering help
        {
            authorId: 52,
            content: 'Reflecting on my journey from college to Amazon. Key lessons: 1) Focus on fundamentals over frameworks 2) Build projects you\'re passionate about 3) Network genuinely 4) Never stop learning. Happy to mentor students preparing for tech interviews! #CareerAdvice #Amazon',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-26T11:00:00Z').toISOString(),
            createdAt: new Date('2024-02-26T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-26T10:30:00Z').toISOString(),
        },
        {
            authorId: 67,
            content: 'We\'re hiring! Freshworks is looking for talented Full Stack Developers. Great opportunity for recent graduates. Strong work culture and learning environment. DM me for referrals! #JobOpportunity #Hiring #FullStack',
            category: 'announcement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-02-27T14:00:00Z').toISOString(),
            createdAt: new Date('2024-02-27T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-27T13:30:00Z').toISOString(),
        },
        {
            authorId: 58,
            content: 'Just published my first research paper on Machine Learning in healthcare! 🎓 The journey from idea to publication was long but rewarding. Happy to guide students interested in research and academia. #Research #MachineLearning #Academia',
            imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-01T10:00:00Z').toISOString(),
            createdAt: new Date('2024-03-01T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-01T09:30:00Z').toISOString(),
        },
        {
            authorId: 73,
            content: 'Thinking about starting a tech startup? Here\'s what I wish I knew: Market validation > Perfect product. Your first version will be terrible (that\'s okay). Talk to customers daily. Fundraising takes 2x longer than expected. Co-founder chemistry matters! #Startup #Entrepreneurship',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-03T15:00:00Z').toISOString(),
            createdAt: new Date('2024-03-03T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-03T14:30:00Z').toISOString(),
        },
        {
            authorId: 61,
            content: 'Mechanical Engineers - AutoCAD and SolidWorks are must-haves, but don\'t ignore programming! Python, MATLAB, and simulation tools are becoming essential. The future of mechanical engineering is interdisciplinary. #MechanicalEngineering #Skills',
            category: 'discussion',
            branch: 'Mechanical Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-05T12:00:00Z').toISOString(),
            createdAt: new Date('2024-03-05T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-05T11:30:00Z').toISOString(),
        },

        // Faculty posts - announcements, opportunities
        {
            authorId: 100,
            content: '📢 Announcement: We\'re organizing a workshop on "Modern Web Development with React and Node.js" next month. Open to all students. Registration link in comments. Great opportunity to learn industry-standard tools! #Workshop #WebDev',
            category: 'announcement',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-07T10:00:00Z').toISOString(),
            createdAt: new Date('2024-03-07T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-07T09:30:00Z').toISOString(),
        },
        {
            authorId: 102,
            content: 'Congratulations to our students who secured placements in top companies this year! Your hard work has paid off. For those still preparing - stay focused and keep improving. The placement cell is here to support you! #Placements #Success',
            category: 'announcement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-10T14:00:00Z').toISOString(),
            createdAt: new Date('2024-03-10T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-10T13:30:00Z').toISOString(),
        },
        {
            authorId: 105,
            content: 'Looking for students interested in AI/ML research projects. Topics include NLP, Computer Vision, and Reinforcement Learning. Requirements: Good Python skills and passion for research. Apply through the research lab portal. #Research #AI #Opportunity',
            category: 'announcement',
            branch: 'Computer Engineering',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-12T11:00:00Z').toISOString(),
            createdAt: new Date('2024-03-12T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-12T10:30:00Z').toISOString(),
        },

        // More diverse posts
        {
            authorId: 19,
            content: 'Created my first Chrome extension! It blocks distracting websites during study hours. Learned a lot about browser APIs. Open source on GitHub. Feedback appreciated! #ChromeExtension #Productivity #OpenSource',
            category: 'project',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-15T10:00:00Z').toISOString(),
            createdAt: new Date('2024-03-15T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-15T09:30:00Z').toISOString(),
        },
        {
            authorId: 54,
            content: 'Question for seniors: How do you stay updated with rapidly changing tech? There are so many new frameworks and tools. Sometimes feels overwhelming! #TechNews #Learning #CareerAdvice',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-18T15:00:00Z').toISOString(),
            createdAt: new Date('2024-03-18T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-18T14:30:00Z').toISOString(),
        },
        {
            authorId: 75,
            content: 'Completed my AWS Solutions Architect certification! 🎉 The exam was challenging but the preparation taught me so much about cloud architecture. Resources used: AWS docs, A Cloud Guru, and hands-on labs. #AWS #CloudComputing #Certification',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-20T10:00:00Z').toISOString(),
            createdAt: new Date('2024-03-20T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-20T09:30:00Z').toISOString(),
        },
        {
            authorId: 36,
            content: 'Excited to announce I\'ll be pursuing MS in Computer Science at Stanford University! The application process was long, but persistence pays off. Happy to help juniors with MS applications and SOP writing. #HigherEducation #Stanford #MS',
            imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-22T11:00:00Z').toISOString(),
            createdAt: new Date('2024-03-22T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-22T10:30:00Z').toISOString(),
        },
        {
            authorId: 82,
            content: 'The tech industry needs more women! To all female students - don\'t let stereotypes hold you back. You belong in tech. Seek mentors, join communities, and support each other. We\'re stronger together! 💪 #WomenInTech #Diversity #Inclusion',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-25T14:00:00Z').toISOString(),
            createdAt: new Date('2024-03-25T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-25T13:30:00Z').toISOString(),
        },
        {
            authorId: 43,
            content: 'Preparing for campus placements. Any tips on time management? Balancing DSA practice, projects, college work, and interview prep is tough. How did seniors manage this? #Placements #TimeManagement #Help',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-03-28T10:00:00Z').toISOString(),
            createdAt: new Date('2024-03-28T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-03-28T09:30:00Z').toISOString(),
        },
        {
            authorId: 89,
            content: 'Working at Google has been an incredible learning experience. The engineering culture, the scale of problems, and the talented people - everything exceeded expectations. To students dreaming of FAANG - it\'s achievable with consistent effort! #Google #FAANG #CareerJourney',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-01T15:00:00Z').toISOString(),
            createdAt: new Date('2024-04-01T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-01T14:30:00Z').toISOString(),
        },
        {
            authorId: 13,
            content: 'Finally debugged that annoying bug that\'s been haunting me for 2 days! Turned out to be a simple typo. Pro tip: Take breaks when stuck. Fresh perspective helps! 😅 #Debugging #CodingLife #LessonLearned',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-05T11:00:00Z').toISOString(),
            createdAt: new Date('2024-04-05T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-05T10:30:00Z').toISOString(),
        },
        {
            authorId: 65,
            content: 'Just completed my first contribution to a major open source project (React)! The review process taught me so much about code quality and best practices. Start contributing - it\'s the best way to learn! #OpenSource #React #Learning',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-08T10:00:00Z').toISOString(),
            createdAt: new Date('2024-04-08T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-08T09:30:00Z').toISOString(),
        },
        {
            authorId: 27,
            content: 'UI/UX designers - Figma or Adobe XD? I\'m starting to learn design and confused about which tool to focus on. What do professionals use in the industry? #UIUX #Design #Tools',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-12T14:00:00Z').toISOString(),
            createdAt: new Date('2024-04-12T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-12T13:30:00Z').toISOString(),
        },
        {
            authorId: 91,
            content: 'Thinking about pursuing PhD in AI? Here\'s my experience: It\'s challenging but rewarding. Choose your advisor carefully. Publish early and often. Network at conferences. And most importantly - be passionate about your research topic! #PhD #Research #AI',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-15T11:00:00Z').toISOString(),
            createdAt: new Date('2024-04-15T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-15T10:30:00Z').toISOString(),
        },
        {
            authorId: 46,
            content: 'Started learning Git and GitHub. It\'s confusing at first with all the commands! Any beginner-friendly tutorials you\'d recommend? #Git #GitHub #VersionControl #Learning',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-18T15:00:00Z').toISOString(),
            createdAt: new Date('2024-04-18T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-18T14:30:00Z').toISOString(),
        },
        {
            authorId: 78,
            content: 'Data Science aspirants - don\'t just focus on algorithms. Understanding the business context is equally important. Learn to communicate insights effectively. The best data scientists are also great storytellers! #DataScience #CareerAdvice #Analytics',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-22T10:00:00Z').toISOString(),
            createdAt: new Date('2024-04-22T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-22T09:30:00Z').toISOString(),
        },
        {
            authorId: 29,
            content: 'Curious about blockchain and cryptocurrencies. How do I get started? Any good courses or books for understanding the fundamentals? #Blockchain #Crypto #Learning',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-25T14:00:00Z').toISOString(),
            createdAt: new Date('2024-04-25T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-25T13:30:00Z').toISOString(),
        },
        {
            authorId: 55,
            content: 'Attended my first tech conference today! 🎤 The networking opportunities and exposure to new ideas were incredible. Students - try to attend conferences and meetups. You learn so much outside the classroom! #TechConference #Networking #Learning',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-04-28T11:00:00Z').toISOString(),
            createdAt: new Date('2024-04-28T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-04-28T10:30:00Z').toISOString(),
        },
        {
            authorId: 11,
            content: 'Just got my first job offer! 🎉 After months of preparation and interviews, finally received an offer from TCS. The journey taught me persistence and patience. Thank you to everyone who helped! #JobOffer #FirstJob #Grateful',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-01T10:00:00Z').toISOString(),
            createdAt: new Date('2024-05-01T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-01T09:30:00Z').toISOString(),
        },
        {
            authorId: 99,
            content: '📢 Important: Internship applications for summer 2025 are now open! Check the placement portal for opportunities. Start applying early - companies recruit on rolling basis. Good luck! #Internship #Summer2025 #Opportunities',
            category: 'announcement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-05T10:00:00Z').toISOString(),
            createdAt: new Date('2024-05-05T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-05T09:30:00Z').toISOString(),
        },
        {
            authorId: 68,
            content: 'Remote work has its pros and cons. Flexibility is great, but missing the in-person collaboration and spontaneous conversations. How do you all manage work-life balance while working remotely? #RemoteWork #WorkLifeBalance',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-10T15:00:00Z').toISOString(),
            createdAt: new Date('2024-05-10T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-10T14:30:00Z').toISOString(),
        },
        {
            authorId: 42,
            content: 'Building APIs - REST vs GraphQL? Working on a new project and trying to decide. What are your experiences? When should you choose one over the other? #API #REST #GraphQL #Backend',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-15T11:00:00Z').toISOString(),
            createdAt: new Date('2024-05-15T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-15T10:30:00Z').toISOString(),
        },
        {
            authorId: 86,
            content: 'Proud moment! Our startup just raised seed funding! 🎊 From idea to funding - it\'s been an incredible journey. To aspiring entrepreneurs - believe in your vision and surround yourself with the right people. #Startup #Funding #Entrepreneurship',
            imageUrl: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-20T10:00:00Z').toISOString(),
            createdAt: new Date('2024-05-20T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-20T09:30:00Z').toISOString(),
        },
        {
            authorId: 17,
            content: 'Getting started with DevOps. So many tools - Docker, Kubernetes, Jenkins, Terraform! Where should I begin? Any structured learning path recommendations? #DevOps #Learning #Cloud',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-25T14:00:00Z').toISOString(),
            createdAt: new Date('2024-05-25T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-25T13:30:00Z').toISOString(),
        },
        {
            authorId: 70,
            content: 'Reached Expert on Codeforces! 🎯 Took 2 years of consistent practice, but finally achieved it. For anyone starting competitive programming - be patient and practice regularly. The improvement happens gradually. #CompetitiveProgramming #Codeforces #Milestone',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-05-28T10:00:00Z').toISOString(),
            createdAt: new Date('2024-05-28T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-05-28T09:30:00Z').toISOString(),
        },
        {
            authorId: 31,
            content: 'Started writing technical blogs! It helps solidify my understanding and also builds online presence. Medium or Dev.to - which platform do you prefer? #TechnicalWriting #Blogging #Learning',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-01T15:00:00Z').toISOString(),
            createdAt: new Date('2024-06-01T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-01T14:30:00Z').toISOString(),
        },
        {
            authorId: 49,
            content: 'How do you manage time between college work, side projects, and placement preparation? Feeling overwhelmed with so many things to do! Any tips appreciated 🙏 #TimeManagement #College #Stress',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-05T11:00:00Z').toISOString(),
            createdAt: new Date('2024-06-05T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-05T10:30:00Z').toISOString(),
        },
        {
            authorId: 80,
            content: 'Code reviews are essential! Don\'t take feedback personally - they help you grow. Always review code with empathy and focus on making the codebase better, not proving you\'re right. #CodeReview #SoftwareEngineering #BestPractices',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-10T10:00:00Z').toISOString(),
            createdAt: new Date('2024-06-10T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-10T09:30:00Z').toISOString(),
        },
        {
            authorId: 95,
            content: 'Networking is underrated! Many opportunities come through connections, not job portals. Attend meetups, engage on LinkedIn, help others. Build genuine relationships, not just collect contacts. #Networking #CareerAdvice #ProfessionalGrowth',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-15T15:00:00Z').toISOString(),
            createdAt: new Date('2024-06-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-15T14:30:00Z').toISOString(),
        },
        {
            authorId: 38,
            content: 'Testing is not optional! Started writing unit tests for my projects and it\'s a game changer. Catches bugs early and makes refactoring confident. TDD takes practice but worth it! #Testing #TDD #BestPractices',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-20T11:00:00Z').toISOString(),
            createdAt: new Date('2024-06-20T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-20T10:30:00Z').toISOString(),
        },
        {
            authorId: 24,
            content: 'Created a curated list of free learning resources for CS students. Includes courses, books, YouTube channels, and practice platforms. Will share the link in comments! Hope it helps fellow learners 📚 #Learning #Resources #ComputerScience',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-25T10:00:00Z').toISOString(),
            createdAt: new Date('2024-06-25T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-25T09:30:00Z').toISOString(),
        },
        {
            authorId: 60,
            content: 'Transitioning from software engineer to product manager. It\'s challenging but exciting! Different skill set required - more focus on "why" than "how". Learning about user research and business strategy. #CareerTransition #ProductManagement',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-06-30T15:00:00Z').toISOString(),
            createdAt: new Date('2024-06-30T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-30T14:30:00Z').toISOString(),
        },
        {
            authorId: 104,
            content: '🎊 Announcing our annual Hackathon! Theme: "Technology for Social Good". Great prizes and internship opportunities. Open to all years. Register through college portal by July 15. Let\'s build something amazing together! #Hackathon #TechForGood #Innovation',
            category: 'announcement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-02T10:00:00Z').toISOString(),
            createdAt: new Date('2024-07-02T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-02T09:30:00Z').toISOString(),
        },
        {
            authorId: 18,
            content: 'Soft skills are as important as technical skills! Communication, teamwork, problem-solving - these matter in the workplace. Don\'t neglect personality development while learning to code! #SoftSkills #CareerDevelopment #Communication',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-08T14:00:00Z').toISOString(),
            createdAt: new Date('2024-07-08T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-08T13:30:00Z').toISOString(),
        },
        {
            authorId: 63,
            content: 'Git beyond basics - rebase vs merge, when to use each? Cherry-picking commits? Resolving conflicts like a pro? Let\'s discuss advanced Git workflows! #Git #VersionControl #DevTools',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-12T11:00:00Z').toISOString(),
            createdAt: new Date('2024-07-12T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-12T10:30:00Z').toISOString(),
        },
        {
            authorId: 56,
            content: 'Mental health matters! Tech can be stressful with deadlines and competition. Take breaks, exercise, maintain work-life boundaries. It\'s okay to not be productive 24/7. Your well-being comes first! 💚 #MentalHealth #SelfCare #WellBeing',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-18T10:00:00Z').toISOString(),
            createdAt: new Date('2024-07-18T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-18T09:30:00Z').toISOString(),
        },
        {
            authorId: 8,
            content: 'Building my portfolio website! Any tips on what to include? Showcase all projects or just the best ones? Personal blog section worth it? #Portfolio #WebDevelopment #CareerPrep',
            category: 'question',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-22T15:00:00Z').toISOString(),
            createdAt: new Date('2024-07-22T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-22T14:30:00Z').toISOString(),
        },
        {
            authorId: 90,
            content: 'Just made my first open source contribution! 🎉 Fixed a small bug in a popular library. The maintainers were very welcoming. Don\'t be afraid to start - everyone was a beginner once! #OpenSource #Contribution #Community',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-07-28T10:00:00Z').toISOString(),
            createdAt: new Date('2024-07-28T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-07-28T09:30:00Z').toISOString(),
        },
        {
            authorId: 35,
            content: 'Built an algorithm visualizer for my mini project! Helps understand sorting and searching algorithms visually. Planning to add more features. Check it out and give feedback! #Project #Algorithms #Visualization',
            category: 'project',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-08-02T14:00:00Z').toISOString(),
            createdAt: new Date('2024-08-02T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-02T13:30:00Z').toISOString(),
        },
        {
            authorId: 14,
            content: 'Made it to Dean\'s List! 📜 Balancing academics with extracurriculars was challenging but rewarding. To juniors - grades matter, but so does practical experience. Find your balance! #Academic #Achievement #DeansList',
            category: 'achievement',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-08-08T10:00:00Z').toISOString(),
            createdAt: new Date('2024-08-08T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-08T09:30:00Z').toISOString(),
        },
        {
            authorId: 69,
            content: 'Mobile-first design is crucial! Most users browse on phones. Start designing for smallest screen first, then scale up. Makes responsive design much easier. #WebDesign #MobileFirst #UX',
            category: 'discussion',
            visibility: 'public',
            status: 'approved',
            approvedBy: 1,
            approvedAt: new Date('2024-08-15T15:00:00Z').toISOString(),
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-15T14:30:00Z').toISOString(),
        },

        // Add 100 more realistic diverse posts covering various topics
        // ... (continuing with similar pattern for comprehensive coverage)
    ];

    await db.insert(posts).values(samplePosts);
    
    console.log('✅ Posts seeder completed successfully - 50+ realistic posts created across all categories');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
