import { db } from '@/db';
import { rsvps } from '@/db/schema';

async function main() {
    const sampleRSVPs = [
        // Event 1: React Advanced Workshop (eventId: 1) - Popular, 28 RSVPs
        { eventId: 1, userId: 2, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-05').toISOString() },
        { eventId: 1, userId: 5, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-06').toISOString() },
        { eventId: 1, userId: 8, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-07').toISOString() },
        { eventId: 1, userId: 12, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-08').toISOString() },
        { eventId: 1, userId: 15, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-09').toISOString() },
        { eventId: 1, userId: 18, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-01-10').toISOString() },
        { eventId: 1, userId: 22, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-11').toISOString() },
        { eventId: 1, userId: 25, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-12').toISOString() },
        { eventId: 1, userId: 28, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-13').toISOString() },
        { eventId: 1, userId: 32, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-14').toISOString() },
        { eventId: 1, userId: 35, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-15').toISOString() },
        { eventId: 1, userId: 38, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-16').toISOString() },
        { eventId: 1, userId: 42, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-17').toISOString() },
        { eventId: 1, userId: 45, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-18').toISOString() },
        { eventId: 1, userId: 48, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-19').toISOString() },
        { eventId: 1, userId: 52, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-07').toISOString() },
        { eventId: 1, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-08').toISOString() },
        { eventId: 1, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-09').toISOString() },
        { eventId: 1, userId: 62, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-10').toISOString() },
        { eventId: 1, userId: 65, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-11').toISOString() },
        { eventId: 1, userId: 68, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-12').toISOString() },
        { eventId: 1, userId: 72, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-13').toISOString() },
        { eventId: 1, userId: 75, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-14').toISOString() },
        { eventId: 1, userId: 78, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-15').toISOString() },
        { eventId: 1, userId: 82, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-16').toISOString() },
        { eventId: 1, userId: 92, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-06').toISOString() },
        { eventId: 1, userId: 95, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-07').toISOString() },
        { eventId: 1, userId: 3, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-01-10').toISOString() },

        // Event 2: Python ML Bootcamp (eventId: 2) - Popular, 25 RSVPs
        { eventId: 2, userId: 4, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-12').toISOString() },
        { eventId: 2, userId: 7, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-13').toISOString() },
        { eventId: 2, userId: 10, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-14').toISOString() },
        { eventId: 2, userId: 13, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-15').toISOString() },
        { eventId: 2, userId: 16, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-16').toISOString() },
        { eventId: 2, userId: 19, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-17').toISOString() },
        { eventId: 2, userId: 23, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-18').toISOString() },
        { eventId: 2, userId: 26, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-01-19').toISOString() },
        { eventId: 2, userId: 29, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-20').toISOString() },
        { eventId: 2, userId: 33, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-21').toISOString() },
        { eventId: 2, userId: 36, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-22').toISOString() },
        { eventId: 2, userId: 39, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-23').toISOString() },
        { eventId: 2, userId: 43, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-24').toISOString() },
        { eventId: 2, userId: 46, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-25').toISOString() },
        { eventId: 2, userId: 49, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-26').toISOString() },
        { eventId: 2, userId: 53, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-14').toISOString() },
        { eventId: 2, userId: 56, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-15').toISOString() },
        { eventId: 2, userId: 59, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-16').toISOString() },
        { eventId: 2, userId: 63, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-17').toISOString() },
        { eventId: 2, userId: 66, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-18').toISOString() },
        { eventId: 2, userId: 69, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-19').toISOString() },
        { eventId: 2, userId: 73, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-20').toISOString() },
        { eventId: 2, userId: 93, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-13').toISOString() },
        { eventId: 2, userId: 96, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-01-14').toISOString() },
        { eventId: 2, userId: 6, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-01-15').toISOString() },

        // Event 3: Cloud Computing AWS Workshop (eventId: 3) - 20 RSVPs
        { eventId: 3, userId: 2, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-05').toISOString() },
        { eventId: 3, userId: 8, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-06').toISOString() },
        { eventId: 3, userId: 11, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-07').toISOString() },
        { eventId: 3, userId: 14, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-08').toISOString() },
        { eventId: 3, userId: 17, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-09').toISOString() },
        { eventId: 3, userId: 21, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-10').toISOString() },
        { eventId: 3, userId: 24, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 3, userId: 27, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 3, userId: 31, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-13').toISOString() },
        { eventId: 3, userId: 34, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-14').toISOString() },
        { eventId: 3, userId: 37, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-15').toISOString() },
        { eventId: 3, userId: 41, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-16').toISOString() },
        { eventId: 3, userId: 44, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-17').toISOString() },
        { eventId: 3, userId: 54, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-07').toISOString() },
        { eventId: 3, userId: 57, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-08').toISOString() },
        { eventId: 3, userId: 60, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-09').toISOString() },
        { eventId: 3, userId: 64, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-10').toISOString() },
        { eventId: 3, userId: 67, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 3, userId: 94, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-06').toISOString() },
        { eventId: 3, userId: 97, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-07').toISOString() },

        // Event 4: DevOps & CI/CD Masterclass (eventId: 4) - Past event, 22 RSVPs
        { eventId: 4, userId: 3, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-15').toISOString() },
        { eventId: 4, userId: 9, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-16').toISOString() },
        { eventId: 4, userId: 12, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-17').toISOString() },
        { eventId: 4, userId: 15, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-18').toISOString() },
        { eventId: 4, userId: 18, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-19').toISOString() },
        { eventId: 4, userId: 22, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-20').toISOString() },
        { eventId: 4, userId: 25, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-21').toISOString() },
        { eventId: 4, userId: 28, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-22').toISOString() },
        { eventId: 4, userId: 32, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-23').toISOString() },
        { eventId: 4, userId: 35, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-24').toISOString() },
        { eventId: 4, userId: 38, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-25').toISOString() },
        { eventId: 4, userId: 42, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-26').toISOString() },
        { eventId: 4, userId: 45, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-27').toISOString() },
        { eventId: 4, userId: 55, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-18').toISOString() },
        { eventId: 4, userId: 58, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-19').toISOString() },
        { eventId: 4, userId: 62, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-20').toISOString() },
        { eventId: 4, userId: 65, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-21').toISOString() },
        { eventId: 4, userId: 68, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-22').toISOString() },
        { eventId: 4, userId: 92, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-16').toISOString() },
        { eventId: 4, userId: 95, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-17').toISOString() },
        { eventId: 4, userId: 5, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2023-11-28').toISOString() },
        { eventId: 4, userId: 20, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2023-11-20').toISOString() },

        // Event 5: Career Growth Webinar (eventId: 5) - Webinar, 35 RSVPs
        { eventId: 5, userId: 2, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-10').toISOString() },
        { eventId: 5, userId: 5, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 5, userId: 8, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 5, userId: 11, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-13').toISOString() },
        { eventId: 5, userId: 14, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-14').toISOString() },
        { eventId: 5, userId: 17, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-15').toISOString() },
        { eventId: 5, userId: 21, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-16').toISOString() },
        { eventId: 5, userId: 24, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-17').toISOString() },
        { eventId: 5, userId: 27, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-18').toISOString() },
        { eventId: 5, userId: 30, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-19').toISOString() },
        { eventId: 5, userId: 33, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-20').toISOString() },
        { eventId: 5, userId: 36, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-21').toISOString() },
        { eventId: 5, userId: 39, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-22').toISOString() },
        { eventId: 5, userId: 43, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-23').toISOString() },
        { eventId: 5, userId: 46, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-24').toISOString() },
        { eventId: 5, userId: 49, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-25').toISOString() },
        { eventId: 5, userId: 52, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 5, userId: 55, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-13').toISOString() },
        { eventId: 5, userId: 58, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-14').toISOString() },
        { eventId: 5, userId: 61, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-15').toISOString() },
        { eventId: 5, userId: 64, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-16').toISOString() },
        { eventId: 5, userId: 67, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-17').toISOString() },
        { eventId: 5, userId: 70, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-18').toISOString() },
        { eventId: 5, userId: 73, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-19').toISOString() },
        { eventId: 5, userId: 76, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-20').toISOString() },
        { eventId: 5, userId: 79, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-21').toISOString() },
        { eventId: 5, userId: 82, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-22').toISOString() },
        { eventId: 5, userId: 85, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-23').toISOString() },
        { eventId: 5, userId: 88, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-24').toISOString() },
        { eventId: 5, userId: 91, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-25').toISOString() },
        { eventId: 5, userId: 93, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 5, userId: 96, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 5, userId: 99, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-13').toISOString() },
        { eventId: 5, userId: 102, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-02-14').toISOString() },
        { eventId: 5, userId: 4, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-02-15').toISOString() },

        // Event 6: Cybersecurity Essentials (eventId: 6) - IT students, 18 RSVPs
        { eventId: 6, userId: 6, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-08').toISOString() },
        { eventId: 6, userId: 9, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-09').toISOString() },
        { eventId: 6, userId: 13, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-10').toISOString() },
        { eventId: 6, userId: 16, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 6, userId: 19, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 6, userId: 23, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-13').toISOString() },
        { eventId: 6, userId: 26, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-14').toISOString() },
        { eventId: 6, userId: 29, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-02-15').toISOString() },
        { eventId: 6, userId: 33, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-16').toISOString() },
        { eventId: 6, userId: 36, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-17').toISOString() },
        { eventId: 6, userId: 39, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-18').toISOString() },
        { eventId: 6, userId: 43, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-19').toISOString() },
        { eventId: 6, userId: 46, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-20').toISOString() },
        { eventId: 6, userId: 53, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-10').toISOString() },
        { eventId: 6, userId: 56, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-11').toISOString() },
        { eventId: 6, userId: 59, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-12').toISOString() },
        { eventId: 6, userId: 94, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-09').toISOString() },
        { eventId: 6, userId: 10, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-02-14').toISOString() },

        // Event 7: Mobile App Development (eventId: 7) - IT students, 16 RSVPs
        { eventId: 7, userId: 7, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-01').toISOString() },
        { eventId: 7, userId: 10, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-02').toISOString() },
        { eventId: 7, userId: 13, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-03').toISOString() },
        { eventId: 7, userId: 16, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-04').toISOString() },
        { eventId: 7, userId: 20, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-05').toISOString() },
        { eventId: 7, userId: 23, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-06').toISOString() },
        { eventId: 7, userId: 26, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-07').toISOString() },
        { eventId: 7, userId: 30, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-08').toISOString() },
        { eventId: 7, userId: 33, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-09').toISOString() },
        { eventId: 7, userId: 36, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 7, userId: 40, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 7, userId: 43, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 7, userId: 54, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-03').toISOString() },
        { eventId: 7, userId: 57, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-04').toISOString() },
        { eventId: 7, userId: 60, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-05').toISOString() },
        { eventId: 7, userId: 95, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-02').toISOString() },

        // Event 8: IoT Workshop (eventId: 8) - Electronics students, 15 RSVPs
        { eventId: 8, userId: 4, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-20').toISOString() },
        { eventId: 8, userId: 7, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-21').toISOString() },
        { eventId: 8, userId: 11, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-22').toISOString() },
        { eventId: 8, userId: 14, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-23').toISOString() },
        { eventId: 8, userId: 17, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-24').toISOString() },
        { eventId: 8, userId: 21, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-25').toISOString() },
        { eventId: 8, userId: 24, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-02-26').toISOString() },
        { eventId: 8, userId: 27, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-27').toISOString() },
        { eventId: 8, userId: 31, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-28').toISOString() },
        { eventId: 8, userId: 34, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-01').toISOString() },
        { eventId: 8, userId: 37, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-02').toISOString() },
        { eventId: 8, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-22').toISOString() },
        { eventId: 8, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-23').toISOString() },
        { eventId: 8, userId: 96, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-02-21').toISOString() },
        { eventId: 8, userId: 8, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-02-25').toISOString() },

        // Event 9: Alumni Networking Meetup (eventId: 9) - Past event, Alumni heavy, 18 RSVPs
        { eventId: 9, userId: 52, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-05').toISOString() },
        { eventId: 9, userId: 55, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-06').toISOString() },
        { eventId: 9, userId: 58, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-07').toISOString() },
        { eventId: 9, userId: 61, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-08').toISOString() },
        { eventId: 9, userId: 64, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-09').toISOString() },
        { eventId: 9, userId: 67, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-10').toISOString() },
        { eventId: 9, userId: 70, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-11').toISOString() },
        { eventId: 9, userId: 73, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-12').toISOString() },
        { eventId: 9, userId: 76, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-13').toISOString() },
        { eventId: 9, userId: 79, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-14').toISOString() },
        { eventId: 9, userId: 82, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-15').toISOString() },
        { eventId: 9, userId: 85, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-16').toISOString() },
        { eventId: 9, userId: 88, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-17').toISOString() },
        { eventId: 9, userId: 2, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-10').toISOString() },
        { eventId: 9, userId: 5, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-11').toISOString() },
        { eventId: 9, userId: 8, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-12').toISOString() },
        { eventId: 9, userId: 93, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-06').toISOString() },
        { eventId: 9, userId: 53, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2023-12-18').toISOString() },

        // Event 10: Annual Tech Conference (eventId: 10) - Past event, Conference, 30 RSVPs
        { eventId: 10, userId: 2, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-15').toISOString() },
        { eventId: 10, userId: 5, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-16').toISOString() },
        { eventId: 10, userId: 8, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-17').toISOString() },
        { eventId: 10, userId: 11, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-18').toISOString() },
        { eventId: 10, userId: 14, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-19').toISOString() },
        { eventId: 10, userId: 17, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-20').toISOString() },
        { eventId: 10, userId: 21, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-21').toISOString() },
        { eventId: 10, userId: 24, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-22').toISOString() },
        { eventId: 10, userId: 27, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-23').toISOString() },
        { eventId: 10, userId: 30, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-24').toISOString() },
        { eventId: 10, userId: 33, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-25').toISOString() },
        { eventId: 10, userId: 36, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-26').toISOString() },
        { eventId: 10, userId: 39, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-27').toISOString() },
        { eventId: 10, userId: 42, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-28').toISOString() },
        { eventId: 10, userId: 45, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-29').toISOString() },
        { eventId: 10, userId: 52, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-17').toISOString() },
        { eventId: 10, userId: 55, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-18').toISOString() },
        { eventId: 10, userId: 58, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-19').toISOString() },
        { eventId: 10, userId: 61, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-20').toISOString() },
        { eventId: 10, userId: 64, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-21').toISOString() },
        { eventId: 10, userId: 67, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-22').toISOString() },
        { eventId: 10, userId: 70, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-23').toISOString() },
        { eventId: 10, userId: 73, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-24').toISOString() },
        { eventId: 10, userId: 76, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-25').toISOString() },
        { eventId: 10, userId: 92, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-15').toISOString() },
        { eventId: 10, userId: 95, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-16').toISOString() },
        { eventId: 10, userId: 98, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-17').toISOString() },
        { eventId: 10, userId: 101, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-18').toISOString() },
        { eventId: 10, userId: 104, status: 'attended', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-19').toISOString() },
        { eventId: 10, userId: 3, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2023-10-30').toISOString() },

        // Event 11: Blockchain Technology Webinar (eventId: 11) - Webinar, 32 RSVPs
        { eventId: 11, userId: 4, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-05').toISOString() },
        { eventId: 11, userId: 7, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-06').toISOString() },
        { eventId: 11, userId: 10, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-07').toISOString() },
        { eventId: 11, userId: 13, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-08').toISOString() },
        { eventId: 11, userId: 16, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-09').toISOString() },
        { eventId: 11, userId: 19, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 11, userId: 22, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 11, userId: 25, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 11, userId: 28, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-13').toISOString() },
        { eventId: 11, userId: 31, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-14').toISOString() },
        { eventId: 11, userId: 34, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 11, userId: 37, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-16').toISOString() },
        { eventId: 11, userId: 40, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-17').toISOString() },
        { eventId: 11, userId: 44, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-18').toISOString() },
        { eventId: 11, userId: 47, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-19').toISOString() },
        { eventId: 11, userId: 50, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-20').toISOString() },
        { eventId: 11, userId: 53, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-07').toISOString() },
        { eventId: 11, userId: 56, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-08').toISOString() },
        { eventId: 11, userId: 59, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-09').toISOString() },
        { eventId: 11, userId: 62, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 11, userId: 65, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 11, userId: 68, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 11, userId: 71, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-13').toISOString() },
        { eventId: 11, userId: 74, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-14').toISOString() },
        { eventId: 11, userId: 77, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 11, userId: 80, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-16').toISOString() },
        { eventId: 11, userId: 83, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-17').toISOString() },
        { eventId: 11, userId: 86, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-18').toISOString() },
        { eventId: 11, userId: 94, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-06').toISOString() },
        { eventId: 11, userId: 97, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-07').toISOString() },
        { eventId: 11, userId: 100, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-08').toISOString() },
        { eventId: 11, userId: 12, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-03-10').toISOString() },

        // Event 12: Data Science Fundamentals (eventId: 12) - Workshop, 22 RSVPs
        { eventId: 12, userId: 3, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 12, userId: 6, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 12, userId: 9, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 12, userId: 12, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-13').toISOString() },
        { eventId: 12, userId: 15, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-14').toISOString() },
        { eventId: 12, userId: 18, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 12, userId: 22, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-16').toISOString() },
        { eventId: 12, userId: 25, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-17').toISOString() },
        { eventId: 12, userId: 28, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-03-18').toISOString() },
        { eventId: 12, userId: 32, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-19').toISOString() },
        { eventId: 12, userId: 35, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-20').toISOString() },
        { eventId: 12, userId: 38, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-21').toISOString() },
        { eventId: 12, userId: 42, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-22').toISOString() },
        { eventId: 12, userId: 45, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-23').toISOString() },
        { eventId: 12, userId: 48, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-24').toISOString() },
        { eventId: 12, userId: 54, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 12, userId: 57, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-13').toISOString() },
        { eventId: 12, userId: 60, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-14').toISOString() },
        { eventId: 12, userId: 63, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 12, userId: 93, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 12, userId: 96, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 12, userId: 20, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-03-16').toISOString() },

        // Event 13: CAD Modeling Workshop (eventId: 13) - Mechanical students, 12 RSVPs
        { eventId: 13, userId: 5, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-08').toISOString() },
        { eventId: 13, userId: 8, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-09').toISOString() },
        { eventId: 13, userId: 11, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 13, userId: 14, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 13, userId: 17, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-12').toISOString() },
        { eventId: 13, userId: 21, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-03-13').toISOString() },
        { eventId: 13, userId: 24, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-14').toISOString() },
        { eventId: 13, userId: 27, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 13, userId: 31, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-16').toISOString() },
        { eventId: 13, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-10').toISOString() },
        { eventId: 13, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-11').toISOString() },
        { eventId: 13, userId: 97, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-09').toISOString() },

        // Event 14: Cultural Fest Social Event (eventId: 14) - Past event, Social, 25 RSVPs
        { eventId: 14, userId: 2, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-20').toISOString() },
        { eventId: 14, userId: 5, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-21').toISOString() },
        { eventId: 14, userId: 8, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-22').toISOString() },
        { eventId: 14, userId: 11, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-23').toISOString() },
        { eventId: 14, userId: 14, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-24').toISOString() },
        { eventId: 14, userId: 17, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-25').toISOString() },
        { eventId: 14, userId: 21, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-26').toISOString() },
        { eventId: 14, userId: 24, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-27').toISOString() },
        { eventId: 14, userId: 27, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-28').toISOString() },
        { eventId: 14, userId: 30, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-29').toISOString() },
        { eventId: 14, userId: 33, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-30').toISOString() },
        { eventId: 14, userId: 36, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-01').toISOString() },
        { eventId: 14, userId: 39, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-02').toISOString() },
        { eventId: 14, userId: 43, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-03').toISOString() },
        { eventId: 14, userId: 46, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-12-04').toISOString() },
        { eventId: 14, userId: 52, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-22').toISOString() },
        { eventId: 14, userId: 55, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-23').toISOString() },
        { eventId: 14, userId: 58, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-24').toISOString() },
        { eventId: 14, userId: 61, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-25').toISOString() },
        { eventId: 14, userId: 92, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-20').toISOString() },
        { eventId: 14, userId: 95, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-21').toISOString() },
        { eventId: 14, userId: 98, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-22').toISOString() },
        { eventId: 14, userId: 101, status: 'attended', paymentStatus: 'na', rsvpedAt: new Date('2023-11-23').toISOString() },
        { eventId: 14, userId: 3, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2023-12-05').toISOString() },
        { eventId: 14, userId: 6, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2023-11-27').toISOString() },

        // Event 15: Startup Pitch Competition (eventId: 15) - Meetup, 14 RSVPs
        { eventId: 15, userId: 4, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-20').toISOString() },
        { eventId: 15, userId: 7, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-21').toISOString() },
        { eventId: 15, userId: 10, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-22').toISOString() },
        { eventId: 15, userId: 13, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-23').toISOString() },
        { eventId: 15, userId: 16, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-24').toISOString() },
        { eventId: 15, userId: 19, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-25').toISOString() },
        { eventId: 15, userId: 23, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-26').toISOString() },
        { eventId: 15, userId: 26, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-27').toISOString() },
        { eventId: 15, userId: 53, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-22').toISOString() },
        { eventId: 15, userId: 56, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-23').toISOString() },
        { eventId: 15, userId: 59, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-24').toISOString() },
        { eventId: 15, userId: 62, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-25').toISOString() },
        { eventId: 15, userId: 93, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-21').toISOString() },
        { eventId: 15, userId: 96, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-03-22').toISOString() },

        // Event 16: VLSI Design Workshop (eventId: 16) - Electronics students, 11 RSVPs
        { eventId: 16, userId: 4, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-15').toISOString() },
        { eventId: 16, userId: 7, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-16').toISOString() },
        { eventId: 16, userId: 11, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-17').toISOString() },
        { eventId: 16, userId: 14, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-18').toISOString() },
        { eventId: 16, userId: 17, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-19').toISOString() },
        { eventId: 16, userId: 21, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-03-20').toISOString() },
        { eventId: 16, userId: 24, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-21').toISOString() },
        { eventId: 16, userId: 27, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-22').toISOString() },
        { eventId: 16, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-17').toISOString() },
        { eventId: 16, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-18').toISOString() },
        { eventId: 16, userId: 96, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-03-16').toISOString() },

        // Event 17: Full Stack Development Bootcamp (eventId: 17) - Popular, 28 RSVPs
        { eventId: 17, userId: 2, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-01').toISOString() },
        { eventId: 17, userId: 5, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-02').toISOString() },
        { eventId: 17, userId: 8, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-03').toISOString() },
        { eventId: 17, userId: 12, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-04').toISOString() },
        { eventId: 17, userId: 15, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-05').toISOString() },
        { eventId: 17, userId: 18, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-06').toISOString() },
        { eventId: 17, userId: 22, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-04-07').toISOString() },
        { eventId: 17, userId: 25, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-08').toISOString() },
        { eventId: 17, userId: 28, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-09').toISOString() },
        { eventId: 17, userId: 32, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 17, userId: 35, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 17, userId: 38, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 17, userId: 42, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-13').toISOString() },
        { eventId: 17, userId: 45, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 17, userId: 48, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 17, userId: 52, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-03').toISOString() },
        { eventId: 17, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-04').toISOString() },
        { eventId: 17, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-05').toISOString() },
        { eventId: 17, userId: 62, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-06').toISOString() },
        { eventId: 17, userId: 65, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-07').toISOString() },
        { eventId: 17, userId: 68, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-08').toISOString() },
        { eventId: 17, userId: 72, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-09').toISOString() },
        { eventId: 17, userId: 75, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 17, userId: 78, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 17, userId: 92, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-02').toISOString() },
        { eventId: 17, userId: 95, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-03').toISOString() },
        { eventId: 17, userId: 98, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-04').toISOString() },
        { eventId: 17, userId: 3, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-04-07').toISOString() },

        // Event 18: AI & Machine Learning Webinar (eventId: 18) - Webinar, 38 RSVPs
        { eventId: 18, userId: 4, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-05').toISOString() },
        { eventId: 18, userId: 7, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-06').toISOString() },
        { eventId: 18, userId: 10, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-07').toISOString() },
        { eventId: 18, userId: 13, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-08').toISOString() },
        { eventId: 18, userId: 16, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-09').toISOString() },
        { eventId: 18, userId: 19, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 18, userId: 23, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 18, userId: 26, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 18, userId: 29, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-13').toISOString() },
        { eventId: 18, userId: 33, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 18, userId: 36, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 18, userId: 39, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-16').toISOString() },
        { eventId: 18, userId: 43, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-17').toISOString() },
        { eventId: 18, userId: 46, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-18').toISOString() },
        { eventId: 18, userId: 49, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-19').toISOString() },
        { eventId: 18, userId: 53, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-07').toISOString() },
        { eventId: 18, userId: 56, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-08').toISOString() },
        { eventId: 18, userId: 59, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-09').toISOString() },
        { eventId: 18, userId: 63, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 18, userId: 66, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 18, userId: 69, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 18, userId: 73, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-13').toISOString() },
        { eventId: 18, userId: 76, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 18, userId: 79, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 18, userId: 82, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-16').toISOString() },
        { eventId: 18, userId: 85, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-17').toISOString() },
        { eventId: 18, userId: 88, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-18').toISOString() },
        { eventId: 18, userId: 91, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-19').toISOString() },
        { eventId: 18, userId: 93, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-06').toISOString() },
        { eventId: 18, userId: 96, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-07').toISOString() },
        { eventId: 18, userId: 99, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-08').toISOString() },
        { eventId: 18, userId: 102, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-09').toISOString() },
        { eventId: 18, userId: 105, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 18, userId: 2, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-20').toISOString() },
        { eventId: 18, userId: 5, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-21').toISOString() },
        { eventId: 18, userId: 8, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-22').toISOString() },
        { eventId: 18, userId: 11, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-23').toISOString() },
        { eventId: 18, userId: 6, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-04-12').toISOString() },

        // Event 19: Professional Networking Meetup (eventId: 19) - Meetup, Alumni heavy, 16 RSVPs
        { eventId: 19, userId: 52, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-10').toISOString() },
        { eventId: 19, userId: 55, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 19, userId: 58, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 19, userId: 61, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-13').toISOString() },
        { eventId: 19, userId: 64, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 19, userId: 67, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 19, userId: 70, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-16').toISOString() },
        { eventId: 19, userId: 73, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-17').toISOString() },
        { eventId: 19, userId: 76, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-18').toISOString() },
        { eventId: 19, userId: 79, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-19').toISOString() },
        { eventId: 19, userId: 2, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 19, userId: 5, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-16').toISOString() },
        { eventId: 19, userId: 8, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-17').toISOString() },
        { eventId: 19, userId: 93, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-11').toISOString() },
        { eventId: 19, userId: 96, status: 'registered', paymentStatus: 'na', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 19, userId: 53, status: 'cancelled', paymentStatus: 'na', rsvpedAt: new Date('2024-04-14').toISOString() },

        // Event 20: Embedded Systems Workshop (eventId: 20) - Electronics students, 13 RSVPs
        { eventId: 20, userId: 4, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-12').toISOString() },
        { eventId: 20, userId: 7, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-13').toISOString() },
        { eventId: 20, userId: 11, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 20, userId: 14, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 20, userId: 17, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-16').toISOString() },
        { eventId: 20, userId: 21, status: 'registered', paymentStatus: 'pending', rsvpedAt: new Date('2024-04-17').toISOString() },
        { eventId: 20, userId: 24, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-18').toISOString() },
        { eventId: 20, userId: 27, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-19').toISOString() },
        { eventId: 20, userId: 31, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-20').toISOString() },
        { eventId: 20, userId: 34, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-21').toISOString() },
        { eventId: 20, userId: 55, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-14').toISOString() },
        { eventId: 20, userId: 58, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-15').toISOString() },
        { eventId: 20, userId: 96, status: 'registered', paymentStatus: 'completed', rsvpedAt: new Date('2024-04-13').toISOString() },
    ];

    await db.insert(rsvps).values(sampleRSVPs);
    
    console.log('✅ RSVPs seeder completed successfully with 200+ event registrations');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});