import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const saltRounds = 10;
    
    // Hash passwords
    const adminPasswordHash = await bcrypt.hash('Admin@123', saltRounds);
    const studentPasswordHash = await bcrypt.hash('Student@123', saltRounds);
    const alumniPasswordHash = await bcrypt.hash('Alumni@123', saltRounds);
    const facultyPasswordHash = await bcrypt.hash('Faculty@123', saltRounds);
    
    const currentDate = new Date().toISOString();
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const fortyFiveDaysAgo = new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString();
    const sixtyDaysAgo = new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString();
    
    const sampleUsers = [
        {
            id: 1,
            email: 'admin@terna.ac.in',
            passwordHash: adminPasswordHash,
            name: 'Dr. Rajesh Kumar',
            role: 'admin',
            status: 'active',
            department: 'Administration',
            phone: '+91-9876543210',
            branch: null,
            cohort: null,
            yearOfPassing: null,
            headline: null,
            bio: null,
            skills: null,
            profileImageUrl: null,
            resumeUrl: null,
            linkedinUrl: null,
            githubUrl: null,
            approvedBy: null,
            approvedAt: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Priya Sharma',
            email: 'priya.sharma@terna.ac.in',
            passwordHash: studentPasswordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            phone: '+91-9123456789',
            headline: 'Final Year Computer Engineering Student',
            bio: 'Passionate about web development and machine learning',
            skills: JSON.stringify(['JavaScript', 'React', 'Python', 'Machine Learning']),
            linkedinUrl: 'https://linkedin.com/in/priyasharma',
            githubUrl: 'https://github.com/priyasharma',
            department: null,
            yearOfPassing: null,
            profileImageUrl: null,
            resumeUrl: null,
            approvedBy: null,
            approvedAt: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Arjun Patel',
            email: 'arjun.patel@terna.ac.in',
            passwordHash: studentPasswordHash,
            role: 'student',
            status: 'active',
            branch: 'Electronics Engineering',
            cohort: '2024-2025',
            phone: '+91-9234567890',
            headline: 'Electronics Engineering enthusiast',
            bio: 'Interested in IoT and embedded systems',
            skills: JSON.stringify(['Arduino', 'Raspberry Pi', 'C++', 'Circuit Design']),
            linkedinUrl: 'https://linkedin.com/in/arjunpatel',
            githubUrl: null,
            department: null,
            yearOfPassing: null,
            profileImageUrl: null,
            resumeUrl: null,
            approvedBy: null,
            approvedAt: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Sneha Desai',
            email: 'sneha.desai@terna.ac.in',
            passwordHash: studentPasswordHash,
            role: 'student',
            status: 'active',
            branch: 'Mechanical Engineering',
            cohort: '2023-2024',
            phone: '+91-9345678901',
            headline: 'Mechanical Engineering student specializing in CAD/CAM',
            bio: 'Focused on manufacturing and design optimization',
            skills: JSON.stringify(['AutoCAD', 'SolidWorks', 'MATLAB', '3D Printing']),
            linkedinUrl: null,
            githubUrl: null,
            department: null,
            yearOfPassing: null,
            profileImageUrl: null,
            resumeUrl: null,
            approvedBy: null,
            approvedAt: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Rahul Kapoor',
            email: 'rahul.kapoor@gmail.com',
            passwordHash: alumniPasswordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2020,
            phone: '+91-9456789012',
            headline: 'Software Engineer at Google',
            bio: 'Alumni working on cloud infrastructure at Google Cloud Platform',
            skills: JSON.stringify(['Java', 'Kubernetes', 'Docker', 'Google Cloud']),
            linkedinUrl: 'https://linkedin.com/in/rahulkapoor',
            githubUrl: 'https://github.com/rahulkapoor',
            approvedBy: 1,
            approvedAt: thirtyDaysAgo,
            department: null,
            cohort: null,
            profileImageUrl: null,
            resumeUrl: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Meera Joshi',
            email: 'meera.joshi@yahoo.com',
            passwordHash: alumniPasswordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Electronics Engineering',
            yearOfPassing: 2018,
            phone: '+91-9567890123',
            headline: 'Senior Hardware Engineer at Intel',
            bio: 'Working on next-gen processor design at Intel Corporation',
            skills: JSON.stringify(['VLSI Design', 'Verilog', 'FPGA', 'Signal Processing']),
            linkedinUrl: 'https://linkedin.com/in/meerajoshi',
            githubUrl: null,
            approvedBy: 1,
            approvedAt: fortyFiveDaysAgo,
            department: null,
            cohort: null,
            profileImageUrl: null,
            resumeUrl: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Prof. Amit Verma',
            email: 'amit.verma@terna.ac.in',
            passwordHash: facultyPasswordHash,
            role: 'faculty',
            status: 'active',
            department: 'Computer Engineering',
            phone: '+91-9678901234',
            headline: 'Associate Professor - Computer Engineering',
            bio: 'Teaching Data Structures, Algorithms, and Database Management Systems',
            skills: JSON.stringify(['Data Structures', 'Algorithms', 'Database Systems', 'Software Engineering']),
            linkedinUrl: 'https://linkedin.com/in/amitverma',
            githubUrl: null,
            approvedBy: 1,
            approvedAt: sixtyDaysAgo,
            branch: null,
            cohort: null,
            yearOfPassing: null,
            profileImageUrl: null,
            resumeUrl: null,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});