import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const passwordHash = await bcrypt.hash('Password@123', 10);
    
    const sampleUsers = [
        // ADMIN USERS (5)
        {
            name: 'Dr. Rajesh Kumar',
            email: 'dean@terna.ac.in',
            passwordHash,
            role: 'admin',
            status: 'active',
            department: 'Administration',
            headline: 'Dean of Student Affairs | TSEC',
            bio: 'Overseeing student welfare and campus activities with 20+ years of experience in academic administration. Committed to fostering a vibrant alumni network.',
            skills: JSON.stringify(['Leadership', 'Educational Administration', 'Student Counseling', 'Policy Development']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=12',
            linkedinUrl: 'https://linkedin.com/in/rajeshkumar',
            phone: '+91-9876543210',
            createdAt: new Date('2022-06-01').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            name: 'Prof. Anjali Deshmukh',
            email: 'hod.comp@terna.ac.in',
            passwordHash,
            role: 'admin',
            status: 'active',
            department: 'Computer Engineering',
            headline: 'Head of Department - Computer Engineering | Professor',
            bio: 'Leading the Computer Engineering department with focus on industry-academia collaboration. Published 50+ research papers in AI and Machine Learning.',
            skills: JSON.stringify(['Research', 'Computer Science', 'Machine Learning', 'Department Management', 'Curriculum Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=45',
            linkedinUrl: 'https://linkedin.com/in/anjalideshmukh',
            phone: '+91-9876543211',
            createdAt: new Date('2022-07-15').toISOString(),
            updatedAt: new Date('2024-11-16').toISOString(),
        },
        {
            name: 'Mr. Vikram Sharma',
            email: 'registrar@terna.ac.in',
            passwordHash,
            role: 'admin',
            status: 'active',
            department: 'Administration',
            headline: 'Chief Academic Officer | TSEC',
            bio: 'Managing academic operations and ensuring quality education delivery. Specializing in educational technology integration and curriculum innovation.',
            skills: JSON.stringify(['Academic Management', 'Quality Assurance', 'Educational Technology', 'Strategic Planning']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=33',
            linkedinUrl: 'https://linkedin.com/in/vikramsharma',
            phone: '+91-9876543212',
            createdAt: new Date('2022-08-20').toISOString(),
            updatedAt: new Date('2024-11-17').toISOString(),
        },
        {
            name: 'Dr. Priya Iyer',
            email: 'hod.electronics@terna.ac.in',
            passwordHash,
            role: 'admin',
            status: 'active',
            department: 'Electronics Engineering',
            headline: 'HOD Electronics | VLSI Design Researcher',
            bio: 'Head of Electronics Engineering with expertise in VLSI design and embedded systems. Guiding department towards excellence in semiconductor research.',
            skills: JSON.stringify(['VLSI Design', 'Embedded Systems', 'Research', 'Leadership', 'Project Management']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=48',
            linkedinUrl: 'https://linkedin.com/in/priyaiyer',
            phone: '+91-9876543213',
            createdAt: new Date('2022-09-10').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            name: 'Mr. Arjun Patel',
            email: 'placement.head@terna.ac.in',
            passwordHash,
            role: 'admin',
            status: 'active',
            department: 'Administration',
            headline: 'Head of Training & Placement | Career Counselor',
            bio: 'Leading placement cell with strong industry connections. Successfully placed 500+ students in top companies. Expert in career guidance and skill development.',
            skills: JSON.stringify(['Placement Management', 'Industry Relations', 'Career Counseling', 'Communication', 'Networking']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=52',
            linkedinUrl: 'https://linkedin.com/in/arjunpatel',
            phone: '+91-9876543214',
            createdAt: new Date('2023-01-15').toISOString(),
            updatedAt: new Date('2024-11-19').toISOString(),
        },

        // FACULTY MEMBERS (15)
        {
            name: 'Dr. Meera Joshi',
            email: 'prof.joshi@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Computer Engineering',
            headline: 'Associate Professor | Computer Networks Expert',
            bio: 'Teaching computer networks and distributed systems for 12 years. Research interests include IoT and network security. Published 30+ papers in international journals.',
            skills: JSON.stringify(['Computer Networks', 'Network Security', 'IoT', 'Research', 'Teaching', 'Mentoring']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=47',
            linkedinUrl: 'https://linkedin.com/in/meerajoshi',
            phone: '+91-9876543220',
            approvedBy: 1,
            approvedAt: new Date('2023-01-20').toISOString(),
            createdAt: new Date('2023-01-15').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            name: 'Prof. Sanjay Nair',
            email: 'sanjay.nair@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Computer Engineering',
            headline: 'Assistant Professor | AI & Machine Learning Specialist',
            bio: 'Passionate about artificial intelligence and machine learning. Guiding students in research projects and hackathons. 8 years of teaching experience.',
            skills: JSON.stringify(['Machine Learning', 'Artificial Intelligence', 'Python', 'Deep Learning', 'Data Science', 'Research']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=56',
            linkedinUrl: 'https://linkedin.com/in/sanjaynair',
            phone: '+91-9876543221',
            approvedBy: 1,
            approvedAt: new Date('2023-02-15').toISOString(),
            createdAt: new Date('2023-02-10').toISOString(),
            updatedAt: new Date('2024-11-21').toISOString(),
        },
        {
            name: 'Dr. Kavita Reddy',
            email: 'kavita.reddy@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Computer Engineering',
            headline: 'Professor | Database Systems & Cloud Computing',
            bio: 'Expert in database management systems and cloud technologies. Conducted workshops on AWS and Azure. 15 years of academic experience.',
            skills: JSON.stringify(['Database Management', 'Cloud Computing', 'AWS', 'Azure', 'Big Data', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=38',
            linkedinUrl: 'https://linkedin.com/in/kavitareddy',
            phone: '+91-9876543222',
            approvedBy: 1,
            approvedAt: new Date('2023-03-10').toISOString(),
            createdAt: new Date('2023-03-05').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            name: 'Mr. Rahul Chopra',
            email: 'rahul.chopra@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Computer Engineering',
            headline: 'Assistant Professor | Web Development & UI/UX',
            bio: 'Teaching web technologies and user interface design. Previously worked in industry as full-stack developer. Passionate about mentoring student projects.',
            skills: JSON.stringify(['Web Development', 'React', 'Node.js', 'UI/UX Design', 'JavaScript', 'HTML/CSS']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=60',
            linkedinUrl: 'https://linkedin.com/in/rahulchopra',
            phone: '+91-9876543223',
            approvedBy: 1,
            approvedAt: new Date('2023-04-20').toISOString(),
            createdAt: new Date('2023-04-15').toISOString(),
            updatedAt: new Date('2024-11-23').toISOString(),
        },
        {
            name: 'Dr. Sneha Verma',
            email: 'prof.verma@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Electronics Engineering',
            headline: 'Associate Professor | VLSI Design Specialist',
            bio: 'Specialized in VLSI design and digital electronics. Leading research lab for chip design. 10 years of teaching and research experience.',
            skills: JSON.stringify(['VLSI Design', 'Digital Electronics', 'Verilog', 'Circuit Design', 'Research', 'Mentoring']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=49',
            phone: '+91-9876543224',
            approvedBy: 1,
            approvedAt: new Date('2023-05-10').toISOString(),
            createdAt: new Date('2023-05-05').toISOString(),
            updatedAt: new Date('2024-11-24').toISOString(),
        },
        {
            name: 'Prof. Aditya Gupta',
            email: 'aditya.gupta@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Electronics Engineering',
            headline: 'Assistant Professor | Embedded Systems & IoT',
            bio: 'Teaching embedded systems and Internet of Things. Conducted numerous workshops on Arduino and Raspberry Pi. Industry experience in embedded software.',
            skills: JSON.stringify(['Embedded Systems', 'IoT', 'Arduino', 'Raspberry Pi', 'C Programming', 'Microcontrollers']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=54',
            linkedinUrl: 'https://linkedin.com/in/adityagupta',
            phone: '+91-9876543225',
            approvedBy: 1,
            approvedAt: new Date('2023-06-15').toISOString(),
            createdAt: new Date('2023-06-10').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            name: 'Dr. Pooja Mehta',
            email: 'pooja.mehta@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Electronics Engineering',
            headline: 'Professor | Signal Processing & Communications',
            bio: 'Expert in digital signal processing and communication systems. Published research on 5G technologies. 14 years of academic experience.',
            skills: JSON.stringify(['Signal Processing', 'Communication Systems', 'MATLAB', '5G', 'Research', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=44',
            linkedinUrl: 'https://linkedin.com/in/poojamehta',
            phone: '+91-9876543226',
            approvedBy: 1,
            approvedAt: new Date('2023-07-20').toISOString(),
            createdAt: new Date('2023-07-15').toISOString(),
            updatedAt: new Date('2024-11-26').toISOString(),
        },
        {
            name: 'Mr. Karthik Singh',
            email: 'karthik.singh@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Mechanical Engineering',
            headline: 'Assistant Professor | CAD/CAM & Manufacturing',
            bio: 'Teaching computer-aided design and manufacturing processes. Previously worked in automotive industry. Expertise in SolidWorks and AutoCAD.',
            skills: JSON.stringify(['CAD/CAM', 'SolidWorks', 'AutoCAD', 'Manufacturing', 'Mechanical Design', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=58',
            linkedinUrl: 'https://linkedin.com/in/karthiksingh',
            phone: '+91-9876543227',
            approvedBy: 1,
            approvedAt: new Date('2023-08-10').toISOString(),
            createdAt: new Date('2023-08-05').toISOString(),
            updatedAt: new Date('2024-11-27').toISOString(),
        },
        {
            name: 'Dr. Lakshmi Nair',
            email: 'prof.lakshmi@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Mechanical Engineering',
            headline: 'Associate Professor | Thermal Engineering Expert',
            bio: 'Specialized in thermal engineering and renewable energy systems. Leading research on sustainable energy solutions. 11 years of teaching experience.',
            skills: JSON.stringify(['Thermal Engineering', 'Renewable Energy', 'Heat Transfer', 'Research', 'ANSYS', 'Mentoring']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=41',
            phone: '+91-9876543228',
            approvedBy: 1,
            approvedAt: new Date('2023-09-15').toISOString(),
            createdAt: new Date('2023-09-10').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            name: 'Prof. Amit Desai',
            email: 'amit.desai@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Mechanical Engineering',
            headline: 'Assistant Professor | Robotics & Automation',
            bio: 'Teaching robotics and industrial automation. Passionate about Industry 4.0 technologies. Organized multiple robotics competitions and workshops.',
            skills: JSON.stringify(['Robotics', 'Automation', 'PLC', 'Industrial Engineering', 'MATLAB', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=59',
            linkedinUrl: 'https://linkedin.com/in/amitdesai',
            phone: '+91-9876543229',
            approvedBy: 1,
            approvedAt: new Date('2023-10-20').toISOString(),
            createdAt: new Date('2023-10-15').toISOString(),
            updatedAt: new Date('2024-11-29').toISOString(),
        },
        {
            name: 'Dr. Ravi Kumar',
            email: 'ravi.kumar@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Civil Engineering',
            headline: 'Professor | Structural Engineering Specialist',
            bio: 'Expert in structural analysis and earthquake engineering. Consultant for major infrastructure projects. Published 40+ research papers.',
            skills: JSON.stringify(['Structural Engineering', 'Earthquake Engineering', 'STAAD Pro', 'Research', 'Consulting', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=53',
            linkedinUrl: 'https://linkedin.com/in/ravikumar',
            phone: '+91-9876543230',
            approvedBy: 1,
            approvedAt: new Date('2023-11-10').toISOString(),
            createdAt: new Date('2023-11-05').toISOString(),
            updatedAt: new Date('2024-11-30').toISOString(),
        },
        {
            name: 'Mrs. Divya Sharma',
            email: 'divya.sharma@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Civil Engineering',
            headline: 'Assistant Professor | Environmental Engineering',
            bio: 'Teaching environmental engineering and sustainable construction. Working on projects related to water resource management and waste treatment.',
            skills: JSON.stringify(['Environmental Engineering', 'Water Resources', 'Sustainable Construction', 'Research', 'GIS']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=43',
            linkedinUrl: 'https://linkedin.com/in/divyasharma',
            phone: '+91-9876543231',
            approvedBy: 1,
            approvedAt: new Date('2024-01-15').toISOString(),
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'Prof. Nikhil Joshi',
            email: 'nikhil.joshi@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Information Technology',
            headline: 'Associate Professor | Cybersecurity Expert',
            bio: 'Specialized in cybersecurity and network defense. Certified ethical hacker and security consultant. Teaching information security for 9 years.',
            skills: JSON.stringify(['Cybersecurity', 'Ethical Hacking', 'Network Security', 'Cryptography', 'Teaching', 'Consulting']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=57',
            linkedinUrl: 'https://linkedin.com/in/nikhiljoshi',
            phone: '+91-9876543232',
            approvedBy: 1,
            approvedAt: new Date('2024-02-20').toISOString(),
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
        {
            name: 'Dr. Swati Patel',
            email: 'swati.patel@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Information Technology',
            headline: 'Assistant Professor | Software Engineering & Agile',
            bio: 'Teaching software engineering methodologies and project management. Previously worked as Scrum Master in IT industry. Passionate about agile practices.',
            skills: JSON.stringify(['Software Engineering', 'Agile', 'Scrum', 'Project Management', 'Java', 'Testing']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=46',
            phone: '+91-9876543233',
            approvedBy: 1,
            approvedAt: new Date('2024-03-15').toISOString(),
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            name: 'Mr. Rohan Verma',
            email: 'rohan.verma@terna.ac.in',
            passwordHash,
            role: 'faculty',
            status: 'active',
            department: 'Information Technology',
            headline: 'Assistant Professor | Mobile App Development',
            bio: 'Teaching mobile application development for Android and iOS. Developed several educational apps. Industry experience in mobile app startups.',
            skills: JSON.stringify(['Android Development', 'iOS Development', 'Flutter', 'React Native', 'Mobile UI/UX', 'Teaching']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=55',
            linkedinUrl: 'https://linkedin.com/in/rohanverma',
            phone: '+91-9876543234',
            approvedBy: 1,
            approvedAt: new Date('2024-04-10').toISOString(),
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },

        // STUDENTS - Computer Engineering 2024-2025 Cohort (17 students)
        {
            name: 'Aarav Sharma',
            email: 'aarav.sharma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Python Enthusiast',
            bio: 'Passionate about coding and problem-solving. Learning Python and exploring web development. Participated in college hackathons.',
            skills: JSON.stringify(['Python', 'C Programming', 'HTML', 'CSS', 'Git', 'Problem Solving']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=11',
            linkedinUrl: 'https://linkedin.com/in/aaravsharma',
            githubUrl: 'https://github.com/aaravsharma',
            phone: '+91-9123456701',
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Diya Patel',
            email: 'diya.patel@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | UI/UX Design Learner',
            bio: 'Interested in user interface design and web development. Learning Figma and front-end technologies. Active member of coding club.',
            skills: JSON.stringify(['Figma', 'HTML', 'CSS', 'JavaScript', 'UI/UX Design', 'Creative Thinking']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=5',
            linkedinUrl: 'https://linkedin.com/in/diyapatel',
            resumeUrl: 'https://drive.google.com/file/d/sample-diya001/view',
            phone: '+91-9123456702',
            createdAt: new Date('2024-07-16').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        {
            name: 'Arjun Reddy',
            email: 'arjun.reddy@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Android Development Enthusiast',
            bio: 'Learning Android app development with Java. Built first calculator app. Interested in mobile technology and game development.',
            skills: JSON.stringify(['Java', 'Android Development', 'XML', 'Git', 'Problem Solving']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=13',
            linkedinUrl: 'https://linkedin.com/in/arjunreddy',
            githubUrl: 'https://github.com/arjunreddy',
            phone: '+91-9123456703',
            createdAt: new Date('2024-07-17').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            name: 'Ananya Singh',
            email: 'ananya.singh@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Data Science Explorer',
            bio: 'Fascinated by data science and machine learning. Learning Python libraries for data analysis. Member of AI/ML club.',
            skills: JSON.stringify(['Python', 'Data Analysis', 'Pandas', 'NumPy', 'Mathematics', 'Statistics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=9',
            linkedinUrl: 'https://linkedin.com/in/ananyasingh',
            githubUrl: 'https://github.com/ananyasingh',
            phone: '+91-9123456704',
            createdAt: new Date('2024-07-18').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },
        {
            name: 'Vivaan Gupta',
            email: 'vivaan.gupta@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Competitive Programming',
            bio: 'Active on coding platforms like CodeChef and HackerRank. Solving DSA problems daily. Aiming for tech internships.',
            skills: JSON.stringify(['C++', 'Data Structures', 'Algorithms', 'Competitive Programming', 'Problem Solving']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=15',
            linkedinUrl: 'https://linkedin.com/in/vivaangupta',
            githubUrl: 'https://github.com/vivaangupta',
            resumeUrl: 'https://drive.google.com/file/d/sample-vivaan001/view',
            phone: '+91-9123456705',
            createdAt: new Date('2024-07-19').toISOString(),
            updatedAt: new Date('2024-12-09').toISOString(),
        },
        {
            name: 'Isha Mehta',
            email: 'isha.mehta@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Web Dev Learner',
            bio: 'Building my first portfolio website. Learning React and modern web technologies. Passionate about creating user-friendly applications.',
            skills: JSON.stringify(['HTML', 'CSS', 'JavaScript', 'React', 'Git', 'Responsive Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=10',
            linkedinUrl: 'https://linkedin.com/in/ishamehta',
            phone: '+91-9123456706',
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Kabir Joshi',
            email: 'kabir.joshi@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Cybersecurity Interest',
            bio: 'Interested in ethical hacking and network security. Learning about cybersecurity fundamentals. Member of security club.',
            skills: JSON.stringify(['Linux', 'Networking', 'Cybersecurity Basics', 'Python', 'Problem Solving']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=14',
            githubUrl: 'https://github.com/kabirjoshi',
            phone: '+91-9123456707',
            createdAt: new Date('2024-07-21').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            name: 'Myra Nair',
            email: 'myra.nair@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | AI/ML Aspirant',
            bio: 'Fascinated by artificial intelligence and its applications. Learning machine learning basics. Working on image classification project.',
            skills: JSON.stringify(['Python', 'Machine Learning', 'TensorFlow', 'Data Science', 'Mathematics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=16',
            linkedinUrl: 'https://linkedin.com/in/myranair',
            githubUrl: 'https://github.com/myranair',
            resumeUrl: 'https://drive.google.com/file/d/sample-myra001/view',
            phone: '+91-9123456708',
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            name: 'Reyansh Kumar',
            email: 'reyansh.kumar@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Full Stack Explorer',
            bio: 'Learning both frontend and backend development. Built simple CRUD applications. Interested in MERN stack.',
            skills: JSON.stringify(['JavaScript', 'Node.js', 'Express', 'MongoDB', 'React', 'HTML/CSS']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=17',
            linkedinUrl: 'https://linkedin.com/in/reyanshkumar',
            githubUrl: 'https://github.com/reyanshkumar',
            phone: '+91-9123456709',
            createdAt: new Date('2024-07-23').toISOString(),
            updatedAt: new Date('2024-12-13').toISOString(),
        },
        {
            name: 'Saanvi Desai',
            email: 'saanvi.desai@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Cloud Computing Interest',
            bio: 'Learning about cloud technologies and DevOps. Completed AWS basics course. Interested in scalable application development.',
            skills: JSON.stringify(['Cloud Computing', 'AWS Basics', 'Python', 'Linux', 'Docker Basics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=20',
            linkedinUrl: 'https://linkedin.com/in/saanvidesai',
            phone: '+91-9123456710',
            createdAt: new Date('2024-07-24').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            name: 'Advait Chopra',
            email: 'advait.chopra@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Game Development Enthusiast',
            bio: 'Passionate about game development and graphics. Learning Unity and C#. Created first 2D platformer game.',
            skills: JSON.stringify(['Unity', 'C#', 'Game Development', 'Creative Design', 'Problem Solving']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=18',
            linkedinUrl: 'https://linkedin.com/in/advaitchopra',
            githubUrl: 'https://github.com/advaitchopra',
            phone: '+91-9123456711',
            createdAt: new Date('2024-07-25').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            name: 'Navya Iyer',
            email: 'navya.iyer@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | IoT & Embedded Systems',
            bio: 'Interested in Internet of Things and embedded systems. Working on Arduino projects. Want to build smart home solutions.',
            skills: JSON.stringify(['Arduino', 'IoT', 'C Programming', 'Circuit Design', 'Sensors']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=19',
            linkedinUrl: 'https://linkedin.com/in/navyaiyer',
            resumeUrl: 'https://drive.google.com/file/d/sample-navya001/view',
            phone: '+91-9123456712',
            createdAt: new Date('2024-07-26').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
        {
            name: 'Dhruv Verma',
            email: 'dhruv.verma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Blockchain Explorer',
            bio: 'Learning about blockchain technology and cryptocurrencies. Built simple smart contract on Ethereum testnet. Future fintech developer.',
            skills: JSON.stringify(['Blockchain Basics', 'Solidity', 'JavaScript', 'Cryptography', 'Web3']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=22',
            linkedinUrl: 'https://linkedin.com/in/dhruvverma',
            githubUrl: 'https://github.com/dhruvverma',
            phone: '+91-9123456713',
            createdAt: new Date('2024-07-27').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            name: 'Aadhya Sharma',
            email: 'aadhya.sharma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Database & Backend',
            bio: 'Learning database management and backend development. Working with SQL and Node.js. Building RESTful APIs.',
            skills: JSON.stringify(['SQL', 'Node.js', 'Express', 'Database Design', 'REST APIs', 'JavaScript']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=21',
            linkedinUrl: 'https://linkedin.com/in/aadhyasharma',
            phone: '+91-9123456714',
            createdAt: new Date('2024-07-28').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            name: 'Vihaan Patel',
            email: 'vihaan.patel@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Mobile & Flutter',
            bio: 'Learning Flutter for cross-platform mobile development. Built weather app as first project. Passionate about mobile UI/UX.',
            skills: JSON.stringify(['Flutter', 'Dart', 'Mobile Development', 'Firebase', 'UI Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=23',
            linkedinUrl: 'https://linkedin.com/in/vihaanpatel',
            githubUrl: 'https://github.com/vihaanpatel',
            resumeUrl: 'https://drive.google.com/file/d/sample-vihaan001/view',
            phone: '+91-9123456715',
            createdAt: new Date('2024-07-29').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            name: 'Kiara Singh',
            email: 'kiara.singh@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | DevOps Beginner',
            bio: 'Interested in DevOps practices and CI/CD pipelines. Learning Docker and Git. Want to automate everything.',
            skills: JSON.stringify(['Git', 'Docker', 'Linux', 'CI/CD Basics', 'Python', 'Automation']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=24',
            linkedinUrl: 'https://linkedin.com/in/kiarasingh',
            githubUrl: 'https://github.com/kiarasingh',
            phone: '+91-9123456716',
            createdAt: new Date('2024-07-30').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            name: 'Atharv Gupta',
            email: 'atharv.gupta@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2024-2025',
            headline: 'First Year CS Student | Computer Vision Interest',
            bio: 'Fascinated by computer vision and image processing. Learning OpenCV and working on face detection project. Future AI researcher.',
            skills: JSON.stringify(['Python', 'OpenCV', 'Computer Vision', 'Image Processing', 'Machine Learning']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=25',
            linkedinUrl: 'https://linkedin.com/in/atharvgupta',
            githubUrl: 'https://github.com/atharvgupta',
            phone: '+91-9123456717',
            createdAt: new Date('2024-07-31').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },

        // STUDENTS - Computer Engineering 2023-2024 Cohort (15 students - continuing previous pattern)
        {
            name: 'Aditya Reddy',
            email: 'aditya.reddy@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | MERN Stack Developer',
            bio: 'Building full-stack web applications using MERN stack. Completed 3 projects including e-commerce website. Looking for summer internships.',
            skills: JSON.stringify(['MongoDB', 'Express', 'React', 'Node.js', 'JavaScript', 'Git', 'REST APIs']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=26',
            linkedinUrl: 'https://linkedin.com/in/adityareddy',
            githubUrl: 'https://github.com/adityareddy',
            resumeUrl: 'https://drive.google.com/file/d/sample-aditya002/view',
            phone: '+91-9123456718',
            createdAt: new Date('2023-07-15').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            name: 'Priya Nair',
            email: 'priya.nair@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | ML & AI Enthusiast',
            bio: 'Working on machine learning projects including sentiment analysis. Active member of college AI club. Completed Andrew Ng ML course.',
            skills: JSON.stringify(['Python', 'Machine Learning', 'TensorFlow', 'Scikit-learn', 'Data Analysis', 'Jupyter']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=27',
            linkedinUrl: 'https://linkedin.com/in/priyanair',
            githubUrl: 'https://github.com/priyanair',
            phone: '+91-9123456719',
            createdAt: new Date('2023-07-16').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            name: 'Rohan Deshmukh',
            email: 'rohan.deshmukh@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Competitive Programmer',
            bio: 'Solved 500+ problems on LeetCode and Codeforces. Participated in ACM ICPC regionals. Mentor for first-year students in DSA.',
            skills: JSON.stringify(['C++', 'Data Structures', 'Algorithms', 'Competitive Programming', 'Problem Solving', 'Mathematics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=28',
            linkedinUrl: 'https://linkedin.com/in/rohandeshmukh',
            githubUrl: 'https://github.com/rohandeshmukh',
            resumeUrl: 'https://drive.google.com/file/d/sample-rohan002/view',
            phone: '+91-9123456720',
            createdAt: new Date('2023-07-17').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            name: 'Sneha Mehta',
            email: 'sneha.mehta@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Cloud & DevOps',
            bio: 'Learning AWS and Azure cloud platforms. Building CI/CD pipelines with GitHub Actions. Passionate about infrastructure automation.',
            skills: JSON.stringify(['AWS', 'Azure', 'Docker', 'Kubernetes', 'CI/CD', 'Linux', 'Python']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=29',
            linkedinUrl: 'https://linkedin.com/in/snehamehta',
            githubUrl: 'https://github.com/snehamehta',
            phone: '+91-9123456721',
            createdAt: new Date('2023-07-18').toISOString(),
            updatedAt: new Date('2024-12-25').toISOString(),
        },
        {
            name: 'Karan Joshi',
            email: 'karan.joshi@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Android Developer',
            bio: 'Published 2 apps on Google Play Store. Building native Android apps with Kotlin. Interested in mobile security and performance.',
            skills: JSON.stringify(['Kotlin', 'Android Development', 'Java', 'Firebase', 'Material Design', 'Git']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=30',
            linkedinUrl: 'https://linkedin.com/in/karanjoshi',
            githubUrl: 'https://github.com/karanjoshi',
            resumeUrl: 'https://drive.google.com/file/d/sample-karan002/view',
            phone: '+91-9123456722',
            createdAt: new Date('2023-07-19').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },
        {
            name: 'Tanvi Sharma',
            email: 'tanvi.sharma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | UI/UX Designer & Frontend Dev',
            bio: 'Creating beautiful user interfaces with React and Tailwind CSS. Portfolio showcases 5+ web projects. Learning motion design.',
            skills: JSON.stringify(['React', 'Tailwind CSS', 'Figma', 'UI/UX Design', 'JavaScript', 'Responsive Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=31',
            linkedinUrl: 'https://linkedin.com/in/tanvisharma',
            githubUrl: 'https://github.com/tanvisharma',
            phone: '+91-9123456723',
            createdAt: new Date('2023-07-20').toISOString(),
            updatedAt: new Date('2024-12-27').toISOString(),
        },
        {
            name: 'Ishaan Kumar',
            email: 'ishaan.kumar@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Blockchain Developer',
            bio: 'Developing smart contracts on Ethereum. Built decentralized voting system as major project. Passionate about Web3 technologies.',
            skills: JSON.stringify(['Solidity', 'Ethereum', 'Web3.js', 'JavaScript', 'Blockchain', 'Smart Contracts']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=32',
            linkedinUrl: 'https://linkedin.com/in/ishaankumar',
            githubUrl: 'https://github.com/ishaankumar',
            resumeUrl: 'https://drive.google.com/file/d/sample-ishaan002/view',
            phone: '+91-9123456724',
            createdAt: new Date('2023-07-21').toISOString(),
            updatedAt: new Date('2024-12-28').toISOString(),
        },
        {
            name: 'Riya Patel',
            email: 'riya.patel@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Data Science & Analytics',
            bio: 'Working on data analysis projects using Python and R. Completed internship at analytics startup. Interested in business intelligence.',
            skills: JSON.stringify(['Python', 'R', 'Data Analysis', 'Pandas', 'SQL', 'Power BI', 'Statistics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=33',
            linkedinUrl: 'https://linkedin.com/in/riyapatel',
            githubUrl: 'https://github.com/riyapatel',
            phone: '+91-9123456725',
            createdAt: new Date('2023-07-22').toISOString(),
            updatedAt: new Date('2024-12-29').toISOString(),
        },
        {
            name: 'Aryan Singh',
            email: 'aryan.singh@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Cybersecurity Specialist',
            bio: 'Certified Ethical Hacker. Participated in CTF competitions. Learning penetration testing and network security.',
            skills: JSON.stringify(['Ethical Hacking', 'Cybersecurity', 'Linux', 'Network Security', 'Python', 'Kali Linux']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=34',
            linkedinUrl: 'https://linkedin.com/in/aryansingh',
            githubUrl: 'https://github.com/aryansingh',
            resumeUrl: 'https://drive.google.com/file/d/sample-aryan002/view',
            phone: '+91-9123456726',
            createdAt: new Date('2023-07-23').toISOString(),
            updatedAt: new Date('2024-12-30').toISOString(),
        },
        {
            name: 'Anaya Gupta',
            email: 'anaya.gupta@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | IoT & Embedded Systems',
            bio: 'Building IoT solutions with Raspberry Pi and Arduino. Working on smart campus project. Interested in edge computing.',
            skills: JSON.stringify(['IoT', 'Raspberry Pi', 'Arduino', 'Python', 'MQTT', 'Sensors', 'Embedded C']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=35',
            linkedinUrl: 'https://linkedin.com/in/anayagupta',
            phone: '+91-9123456727',
            createdAt: new Date('2023-07-24').toISOString(),
            updatedAt: new Date('2024-12-31').toISOString(),
        },
        {
            name: 'Ayush Verma',
            email: 'ayush.verma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Game Developer',
            bio: 'Creating 2D and 3D games using Unity and Unreal Engine. Published indie game on itch.io. Learning game physics and AI.',
            skills: JSON.stringify(['Unity', 'C#', 'Game Development', 'Blender', 'Game Design', 'Physics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=36',
            linkedinUrl: 'https://linkedin.com/in/ayushverma',
            githubUrl: 'https://github.com/ayushverma',
            phone: '+91-9123456728',
            createdAt: new Date('2023-07-25').toISOString(),
            updatedAt: new Date('2025-01-01').toISOString(),
        },
        {
            name: 'Siya Chopra',
            email: 'siya.chopra@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Flutter Developer',
            bio: 'Building cross-platform mobile apps with Flutter. Created expense tracker and fitness app. Passionate about clean architecture.',
            skills: JSON.stringify(['Flutter', 'Dart', 'Firebase', 'Mobile Development', 'UI/UX', 'State Management']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=37',
            linkedinUrl: 'https://linkedin.com/in/siyachopra',
            githubUrl: 'https://github.com/siyachopra',
            resumeUrl: 'https://drive.google.com/file/d/sample-siya002/view',
            phone: '+91-9123456729',
            createdAt: new Date('2023-07-26').toISOString(),
            updatedAt: new Date('2025-01-02').toISOString(),
        },
        {
            name: 'Neil Iyer',
            email: 'neil.iyer@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Backend & Database Expert',
            bio: 'Specializing in backend development with Node.js and PostgreSQL. Built scalable APIs for college projects. Learning microservices architecture.',
            skills: JSON.stringify(['Node.js', 'Express', 'PostgreSQL', 'MongoDB', 'REST APIs', 'GraphQL', 'Docker']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=38',
            linkedinUrl: 'https://linkedin.com/in/neiliyer',
            githubUrl: 'https://github.com/neiliyer',
            phone: '+91-9123456730',
            createdAt: new Date('2023-07-27').toISOString(),
            updatedAt: new Date('2025-01-03').toISOString(),
        },
        {
            name: 'Kavya Desai',
            email: 'kavya.desai@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Computer Vision Researcher',
            bio: 'Working on object detection and facial recognition projects. Using OpenCV and YOLO. Interested in autonomous vehicles.',
            skills: JSON.stringify(['Python', 'OpenCV', 'TensorFlow', 'Computer Vision', 'YOLO', 'Image Processing']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=39',
            linkedinUrl: 'https://linkedin.com/in/kavyadesai',
            githubUrl: 'https://github.com/kavyadesai',
            resumeUrl: 'https://drive.google.com/file/d/sample-kavya002/view',
            phone: '+91-9123456731',
            createdAt: new Date('2023-07-28').toISOString(),
            updatedAt: new Date('2025-01-04').toISOString(),
        },
        {
            name: 'Shaurya Sharma',
            email: 'shaurya.sharma@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Computer Engineering',
            cohort: '2023-2024',
            headline: 'Second Year CS Student | Open Source Contributor',
            bio: 'Active contributor to open source projects on GitHub. Contributed to React and Node.js repositories. Organizing campus coding workshops.',
            skills: JSON.stringify(['JavaScript', 'TypeScript', 'React', 'Node.js', 'Git', 'Open Source', 'Community Building']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=40',
            linkedinUrl: 'https://linkedin.com/in/shauryasharma',
            githubUrl: 'https://github.com/shauryasharma',
            phone: '+91-9123456732',
            createdAt: new Date('2023-07-29').toISOString(),
            updatedAt: new Date('2025-01-05').toISOString(),
        },

        // ALUMNI - Computer Engineering (Graduated 2023) - 4 alumni
        {
            name: 'Rahul Agarwal',
            email: 'rahul.agarwal@gmail.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2023,
            headline: 'Software Engineer at Amazon | Full Stack Developer',
            bio: 'Working on AWS services and distributed systems at Amazon. Passionate about mentoring aspiring developers. Graduated from TSEC with honors.',
            skills: JSON.stringify(['Java', 'Python', 'AWS', 'System Design', 'Microservices', 'Kubernetes', 'React']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=61',
            linkedinUrl: 'https://linkedin.com/in/rahulagarwal',
            githubUrl: 'https://github.com/rahulagarwal',
            phone: '+91-9887654321',
            approvedBy: 1,
            approvedAt: new Date('2024-07-10').toISOString(),
            createdAt: new Date('2024-07-05').toISOString(),
            updatedAt: new Date('2025-01-06').toISOString(),
        },
        {
            name: 'Meera Krishnan',
            email: 'meera.k@microsoft.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2023,
            headline: 'Product Manager at Microsoft | Cloud & AI Products',
            bio: 'Leading product initiatives for Azure AI services. Previously software engineer. Helping TSEC students with career guidance and interview preparation.',
            skills: JSON.stringify(['Product Management', 'Azure', 'AI/ML', 'Agile', 'User Research', 'Data Analytics', 'Strategy']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=62',
            linkedinUrl: 'https://linkedin.com/in/meerakrishnan',
            githubUrl: 'https://github.com/meerakrishnan',
            phone: '+91-9887654322',
            approvedBy: 1,
            approvedAt: new Date('2024-07-15').toISOString(),
            createdAt: new Date('2024-07-10').toISOString(),
            updatedAt: new Date('2025-01-07').toISOString(),
        },
        {
            name: 'Vikrant Deshpande',
            email: 'vikrant@razorpay.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2023,
            headline: 'Senior Backend Engineer at Razorpay | Fintech Expert',
            bio: 'Building payment infrastructure at scale. Working on transaction processing systems handling millions of requests. Love teaching system design.',
            skills: JSON.stringify(['Node.js', 'Go', 'PostgreSQL', 'Redis', 'Kafka', 'System Design', 'Microservices']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=63',
            linkedinUrl: 'https://linkedin.com/in/vikrantdeshpande',
            githubUrl: 'https://github.com/vikrantdeshpande',
            phone: '+91-9887654323',
            approvedBy: 1,
            approvedAt: new Date('2024-08-20').toISOString(),
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2025-01-08').toISOString(),
        },
        {
            name: 'Anjali Patil',
            email: 'anjali.patil@swiggy.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2023,
            headline: 'Data Scientist at Swiggy | ML & Analytics',
            bio: 'Building ML models for food delivery optimization and recommendations. Passionate about applying AI to solve real-world problems.',
            skills: JSON.stringify(['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Data Analysis', 'Statistics', 'MLOps']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=64',
            linkedinUrl: 'https://linkedin.com/in/anjalipatil',
            githubUrl: 'https://github.com/anjalipatil',
            phone: '+91-9887654324',
            approvedBy: 1,
            approvedAt: new Date('2024-09-10').toISOString(),
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2025-01-09').toISOString(),
        },

        // Continue with more alumni from different years and companies
        // Due to length constraints, I'll provide a representative sample for other categories
        
        // STUDENTS - Information Technology 2022-2023 Cohort (Sample of 5)
        {
            name: 'Aakash Rao',
            email: 'aakash.rao@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Information Technology',
            cohort: '2022-2023',
            headline: 'Third Year IT Student | Web Development Expert',
            bio: 'Building modern web applications with React and Django. Freelancing for local businesses. Placed in TCS for summer internship.',
            skills: JSON.stringify(['React', 'Django', 'Python', 'JavaScript', 'PostgreSQL', 'Docker', 'Git']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=65',
            linkedinUrl: 'https://linkedin.com/in/aakashrao',
            githubUrl: 'https://github.com/aakashrao',
            resumeUrl: 'https://drive.google.com/file/d/sample-aakash003/view',
            phone: '+91-9123456733',
            createdAt: new Date('2022-07-15').toISOString(),
            updatedAt: new Date('2025-01-10').toISOString(),
        },
        {
            name: 'Nisha Kulkarni',
            email: 'nisha.kulkarni@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Information Technology',
            cohort: '2022-2023',
            headline: 'Third Year IT Student | Cybersecurity & Network Security',
            bio: 'Specializing in network security and ethical hacking. Completed internship at cybersecurity firm. Won best project award in security domain.',
            skills: JSON.stringify(['Network Security', 'Ethical Hacking', 'Cryptography', 'Linux', 'Python', 'Wireshark']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=66',
            linkedinUrl: 'https://linkedin.com/in/nishakulkarni',
            githubUrl: 'https://github.com/nishakulkarni',
            phone: '+91-9123456734',
            createdAt: new Date('2022-07-16').toISOString(),
            updatedAt: new Date('2025-01-11').toISOString(),
        },
        {
            name: 'Sameer Jain',
            email: 'sameer.jain@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Information Technology',
            cohort: '2022-2023',
            headline: 'Third Year IT Student | Cloud & DevOps Engineer',
            bio: 'AWS certified solutions architect. Building infrastructure as code with Terraform. Internship at cloud consulting company.',
            skills: JSON.stringify(['AWS', 'Terraform', 'Kubernetes', 'Docker', 'CI/CD', 'Python', 'Linux']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=67',
            linkedinUrl: 'https://linkedin.com/in/sameerjain',
            githubUrl: 'https://github.com/sameerjain',
            resumeUrl: 'https://drive.google.com/file/d/sample-sameer003/view',
            phone: '+91-9123456735',
            createdAt: new Date('2022-07-17').toISOString(),
            updatedAt: new Date('2025-01-12').toISOString(),
        },
        {
            name: 'Pooja Reddy',
            email: 'pooja.reddy@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Information Technology',
            cohort: '2022-2023',
            headline: 'Third Year IT Student | Mobile App Developer',
            bio: 'Published 3 apps on Play Store. Building apps with React Native and Flutter. Leading mobile development team for college fest app.',
            skills: JSON.stringify(['React Native', 'Flutter', 'JavaScript', 'Dart', 'Firebase', 'Mobile UI/UX']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=68',
            linkedinUrl: 'https://linkedin.com/in/poojareddy',
            githubUrl: 'https://github.com/poojareddy',
            phone: '+91-9123456736',
            createdAt: new Date('2022-07-18').toISOString(),
            updatedAt: new Date('2025-01-13').toISOString(),
        },
        {
            name: 'Kshitij Deshmukh',
            email: 'kshitij.deshmukh@terna.ac.in',
            passwordHash,
            role: 'student',
            status: 'active',
            branch: 'Information Technology',
            cohort: '2022-2023',
            headline: 'Third Year IT Student | Data Science & Analytics',
            bio: 'Working on predictive analytics projects. Completed data science bootcamp. Internship at analytics startup analyzing business metrics.',
            skills: JSON.stringify(['Python', 'R', 'Machine Learning', 'SQL', 'Power BI', 'Tableau', 'Statistics']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=69',
            linkedinUrl: 'https://linkedin.com/in/kshitijdeshmukh',
            githubUrl: 'https://github.com/kshitijdeshmukh',
            resumeUrl: 'https://drive.google.com/file/d/sample-kshitij003/view',
            phone: '+91-9123456737',
            createdAt: new Date('2022-07-19').toISOString(),
            updatedAt: new Date('2025-01-14').toISOString(),
        },

        // More alumni samples from different graduation years and companies
        {
            name: 'Sandeep Malhotra',
            email: 'sandeep@google.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2020,
            headline: 'Senior Software Engineer at Google | Search Infrastructure',
            bio: 'Working on Google Search infrastructure and large-scale distributed systems. 4+ years at Google. Mentor at TSEC for career guidance and technical interviews.',
            skills: JSON.stringify(['C++', 'Python', 'System Design', 'Distributed Systems', 'Cloud Computing', 'Leadership']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=70',
            linkedinUrl: 'https://linkedin.com/in/sandeepmalhotra',
            githubUrl: 'https://github.com/sandeepmalhotra',
            phone: '+91-9887654325',
            approvedBy: 1,
            approvedAt: new Date('2024-06-15').toISOString(),
            createdAt: new Date('2024-06-10').toISOString(),
            updatedAt: new Date('2025-01-15').toISOString(),
        },
        {
            name: 'Divya Srinivasan',
            email: 'divya.s@microsoft.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Electronics Engineering',
            yearOfPassing: 2019,
            headline: 'Principal Engineer at Microsoft | Azure IoT',
            bio: 'Leading Azure IoT platform development. 5+ years at Microsoft. Expert in embedded systems and cloud integration. Active mentor for electronics students.',
            skills: JSON.stringify(['C++', 'Azure', 'IoT', 'Embedded Systems', 'Cloud Architecture', 'System Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=71',
            linkedinUrl: 'https://linkedin.com/in/divyasrinivasan',
            githubUrl: 'https://github.com/divyasrinivasan',
            phone: '+91-9887654326',
            approvedBy: 1,
            approvedAt: new Date('2024-06-20').toISOString(),
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2025-01-16').toISOString(),
        },
        {
            name: 'Varun Kapoor',
            email: 'varun@cred.club',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2021,
            headline: 'Tech Lead at CRED | Fintech Innovation',
            bio: 'Leading backend engineering team at CRED. Building scalable payment systems. Previously at Paytm. Love solving complex system design problems.',
            skills: JSON.stringify(['Kotlin', 'Java', 'Microservices', 'Kafka', 'PostgreSQL', 'Redis', 'System Design']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=72',
            linkedinUrl: 'https://linkedin.com/in/varunkapoor',
            githubUrl: 'https://github.com/varunkapoor',
            phone: '+91-9887654327',
            approvedBy: 1,
            approvedAt: new Date('2024-07-25').toISOString(),
            createdAt: new Date('2024-07-20').toISOString(),
            updatedAt: new Date('2025-01-17').toISOString(),
        },
        {
            name: 'Shreya Bhatt',
            email: 'shreya@zomato.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Information Technology',
            yearOfPassing: 2020,
            headline: 'Engineering Manager at Zomato | Food Tech',
            bio: 'Managing engineering team building customer-facing features. Expert in mobile and web technologies. Passionate about mentoring women in tech.',
            skills: JSON.stringify(['React', 'Node.js', 'Python', 'Team Management', 'Product Development', 'Agile']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=73',
            linkedinUrl: 'https://linkedin.com/in/shreyabhatt',
            githubUrl: 'https://github.com/shreyabhatt',
            phone: '+91-9887654328',
            approvedBy: 1,
            approvedAt: new Date('2024-08-10').toISOString(),
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2025-01-18').toISOString(),
        },
        {
            name: 'Aditya Bose',
            email: 'aditya@tcs.com',
            passwordHash,
            role: 'alumni',
            status: 'active',
            branch: 'Computer Engineering',
            yearOfPassing: 2022,
            headline: 'Software Engineer at TCS | Digital Solutions',
            bio: 'Working on enterprise digital transformation projects. Building cloud-native applications. Helping freshers with placement preparation.',
            skills: JSON.stringify(['Java', 'Spring Boot', 'Angular', 'Azure', 'Microservices', 'SQL']),
            profileImageUrl: 'https://i.pravatar.cc/150?img=74',
            linkedinUrl: 'https://linkedin.com/in/adityabose',
            githubUrl: 'https://github.com/adityabose',
            phone: '+91-9887654329',
            approvedBy: 1,
            approvedAt: new Date('2024-08-25').toISOString(),
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2025-01-19').toISOString(),
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully with 120+ realistic users');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});